// _bedingungen.js (COMDIS) - AHB-Bedingungen, extrahiert mit kohlrahbi (Hochfrequenz).
// Offizieller conditions-Scraper, Quelle FV2604.
var comdisBedingungen = {
  "1": { text: "wenn SG3 AJT+Z61+S_0109 oder SG3 AJT+Z62+S_0109 vorhanden", art: "voraussetzung" },
  "2": { text: "wenn SG3 AJT+Z58+S_0109 oder SG3 AJT+Z59+S_0109 oder SG3 AJT+Z60+S_0109 vorhanden", art: "voraussetzung" },
  "3": { text: "Nur MP-ID aus Sparte Strom", art: "voraussetzung" },
  "4": { text: "wenn SG3 AJT+Z58/Z59/ Z60/Z61/Z62+S_0109 vorhanden", art: "voraussetzung" },
  "5": { text: "wenn SG3 AJT+A01/A02/ A03/A04/A06/A07/A09/A12/ A15+E_0504 vorhanden", art: "voraussetzung" },
  "6": { text: "wenn SG3 AJT+A07+E_0504 vorhanden", art: "voraussetzung" },
  "7": { text: "wenn SG3 AJT+A02+E_0504 vorhanden", art: "voraussetzung" },
  "8": { text: "wenn SG3 AJT+A01/A04/ A06/A09/A12+E_0504 vorhanden", art: "voraussetzung" },
  "9": { text: "wenn SG3 AJT+A05/A10/ A11/A14+E_0504 vorhanden", art: "voraussetzung" },
  "10": { text: "wenn SG3 AJT+A03+E_0504 vorhanden", art: "voraussetzung" },
  "11": { text: "wenn SG3 AJT+A15+E_0504 vorhanden", art: "voraussetzung" },
  "12": { text: "wenn SG3 AJT+A99+S_0109 vorhanden", art: "voraussetzung" },
  "13": { text: "wenn SG3 AJT+A07+E_1008 vorhanden", art: "voraussetzung" },
  "14": { text: "wenn SG3 AJT+A02+E_1008 vorhanden", art: "voraussetzung" },
  "15": { text: "wenn SG3 AJT+A01/ A04/A06/A09+E_1008 vorhanden", art: "voraussetzung" },
  "16": { text: "wenn SG3 AJT+A03+E_1008 vorhanden", art: "voraussetzung" },
  "17": { text: "wenn SG3 AJT+A15+E_1008 vorhanden", art: "voraussetzung" },
  "18": { text: "wenn SG3 AJT+A05/ A10/A11+E_1008 vorhanden", art: "voraussetzung" },
  "19": { text: "wenn SG3 AJT+A99+E_0265/E_0271/ E_0274/E_0516/E_0520/ E_0567 vorhanden", art: "voraussetzung" },
  "20": { text: "wenn SG3 AJT+A01/ A02/A03/A04/A06/A07/A09/ A15+E_1008 vorhanden", art: "voraussetzung" },
  "21": { text: "wenn im DE3155 in demselben COM der Code EM vorhanden ist", art: "voraussetzung" },
  "22": { text: "wenn im DE3155 in demselben COM der Code TE / FX / AJ / AL vorhanden ist", art: "voraussetzung" },
  "23": { text: "Wenn MP-ID in NAD+MS (Nachrichtensender) mit Rolle MSB vorhanden", art: "voraussetzung" },
  "24": { text: "Wenn MP-ID in NAD+MR (Nachrichtenempfänger) mit Rolle ESA vorhanden", art: "voraussetzung" },
  "25": { text: "Wenn MP-ID in NAD+MR (Nachrichtenempfänger) mit Rolle LF vorhanden", art: "voraussetzung" },
  "26": { text: "Wenn MP-ID in NAD+MR (Nachrichtenempfänger) mit Rolle NB vorhanden", art: "voraussetzung" },
  "27": { text: "Wenn MP-ID in NAD+MS (Nachrichtensender) mit Rolle NB vorhanden", art: "voraussetzung" },
  "28": { text: "Angabe der Datenaustauschreferenz aus der CONTRL", art: "voraussetzung" },
  "29": { text: "Angabe der Datenaustauschreferenz aus der APERAK", art: "voraussetzung" },
  "30": { text: "Angabe der Nachrichtennummer aus der APERAK", art: "voraussetzung" },
  "31": { text: "wenn SG3 AJT+Z61+G_0089 oder SG3 AJT+Z62+G_0089 vorhanden", art: "voraussetzung" },
  "32": { text: "wenn SG3 AJT+Z58+G_0089 oder SG3 AJT+Z59+G_0089 oder SG3 AJT+Z60+G_0089 vorhanden", art: "voraussetzung" },
  "33": { text: "wenn SG3 AJT+Z58/Z59/ Z60/Z61/Z62+G_0089 vorhanden", art: "voraussetzung" },
  "34": { text: "wenn SG3 AJT+A99+G_0089 vorhanden", art: "voraussetzung" },
  "490": { text: "wenn Wert in diesem DE, an der Stelle CCYYMMDDHHMM ein Zeitpunkt aus dem angegeben Zeitraum der Tabelle Kapitel 3.5 „Übersicht gesetzliche deutsche Sommerzeit (MESZ)“ der Spalten:\n›\t„Sommerzeit (MESZ) von“ Darstellung in UTC und\n›\t„Sommerzeit (MESZ) bis“ Darstellung in UTC ist.", art: "voraussetzung" },
  "491": { text: "wenn Wert in diesem DE, an der Stelle CCYYMMDDHHMM ein Zeitpunkt aus dem angegeben Zeitraum der Tabelle Kapitel 3.6 „Übersicht gesetzliche deutsche Zeit (MEZ)“ der Spalten: \n›\t„Winterzeit (MEZ) von“ Darstellung in UTC und\n›\t„Winterzeit (MEZ) bis“ Darstellung in UTC ist.", art: "voraussetzung" },
  "492": { text: "Wenn MP-ID in NAD+MR (Nachrichtenempfänger) aus Sparte Strom", art: "voraussetzung" },
  "493": { text: "Wenn MP-ID in NAD+MR (Nachrichtenempfänger) aus Sparte Gas", art: "voraussetzung" },
  "505": { text: "Hinweis: BGM DE1004 aus der vorher per REMADV abgelehnten INVOIC-Nachricht", art: "hinweis" },
  "506": { text: "Hinweis: BGM DE1004 aus der vorher per IFTSTA abgelehnten MSCONS- Nachricht", art: "hinweis" },
  "508": { text: "Hinweis: Es darf nur eine Information im DE3148 übermittelt werden", art: "hinweis" },
  "509": { text: "Hinweis: Wenn Eingang der zugrundeliegenden Nachricht vor dem 06.06. 2025, 00:00 Uhr bestätigt wurde", art: "hinweis" },
  "510": { text: "Hinweis: Wenn Eingang der zugrundeliegenden Nachricht nach dem 06.06. 2025, 00:00 Uhr bestätigt wurde", art: "hinweis" },
  "930": { text: "Format: max. 2 Nachkommastellen", art: "format" },
  "931": { text: "Format: ZZZ = +00", art: "format" },
  "932": { text: "Format: HHMM = 2200", art: "format" },
  "933": { text: "Format: HHMM = 2300", art: "format" },
  "934": { text: "Format: HHMM = 0400", art: "format" },
  "935": { text: "Format: HHMM = 0500", art: "format" },
  "939": { text: "Format: Die Zeichenkette muss die Zeichen @ und . enthalten", art: "format" },
  "940": { text: "Format: Die Zeichenkette muss mit dem Zeichen + beginnen und danach dürfen nur noch Ziffern folgen", art: "format" },
};
if (typeof window!=='undefined') window.EdiBedingungen = Object.assign(window.EdiBedingungen||{}, comdisBedingungen);
if (typeof module!=='undefined') module.exports = comdisBedingungen;
