// _bedingungen.js (ORDERS) - AHB-Bedingungen via kohlrahbi-Parser (an unser docx-Layout adaptiert).
// parse_conditions_from_string (kohlrahbi/Hochfrequenz), Quelle AHB_ORDERS_1.1a_20260401_20260930_20260401_ooox_11934.docx.
var ordersBedingungen = {
  "1": { text: "Wenn IMD+Z03 vorhanden", art: "voraussetzung", check: {"tag": "IMD", "qual": "Z03", "neg": false} },
  "2": { text: "Wenn BGM+7 vorhanden", art: "voraussetzung", check: {"tag": "BGM", "qual": "7", "neg": false} },
  "6": { text: "Wenn MP-ID in SG2 NAD+MS mit Rolle LF vorhanden", art: "voraussetzung" },
  "7": { text: "Wenn MP-ID in SG2 NAD+MS mit Rolle NB vorhanden", art: "voraussetzung" },
  "9": { text: "Wenn bekannt", art: "voraussetzung" },
  "12": { text: "Wenn vorhanden", art: "voraussetzung" },
  "13": { text: "Wenn SG2 LOC+172 nicht vorhanden", art: "voraussetzung", check: {"tag": "LOC", "qual": "172", "neg": true} },
  "15": { text: "Wenn MP-ID in SG2 NAD+MS mit Rolle MSB vorhanden", art: "voraussetzung" },
  "16": { text: "Wenn eine untergeordnete SG vorhanden", art: "voraussetzung" },
  "17": { text: "Wenn ein Segment innerhalb der SG vorhanden", art: "voraussetzung" },
  "18": { text: "Wenn IMD++Z11 vorhanden", art: "voraussetzung", check: {"tag": "IMD", "qual": "Z11", "neg": false} },
  "19": { text: "Wenn IMD++Z12 vorhanden", art: "voraussetzung", check: {"tag": "IMD", "qual": "Z12", "neg": false} },
  "21": { text: "Wenn BGM+Z28 vorhanden", art: "voraussetzung", check: {"tag": "BGM", "qual": "Z28", "neg": false} },
  "23": { text: "Wenn MP-ID in SG2 NAD+MR mit Rolle NB vorhanden", art: "voraussetzung" },
  "24": { text: "Wenn IMD++Z35 vorhanden", art: "voraussetzung", check: {"tag": "IMD", "qual": "Z35", "neg": false} },
  "26": { text: "Wenn MP-ID in SG2 NAD+MS mit Rolle ÜNB vorhanden", art: "voraussetzung" },
  "27": { text: "Wenn MP-ID in SG2 NAD+MR mit Rolle MSB vorhanden", art: "voraussetzung" },
  "28": { text: "Wenn MP-ID in SG2 NAD+MR aus Sparte Strom", art: "voraussetzung" },
  "29": { text: "Wenn MP-ID in SG2 NAD+MR aus Sparte Gas", art: "voraussetzung" },
  "33": { text: "Wenn IMD+Z01 vorhanden", art: "voraussetzung", check: {"tag": "IMD", "qual": "Z01", "neg": false} },
  "34": { text: "Wenn IMD+Z02 vorhanden", art: "voraussetzung", check: {"tag": "IMD", "qual": "Z02", "neg": false} },
  "35": { text: "IMD++Z14+Z06 vorhanden", art: "voraussetzung" },
  "36": { text: "Wenn MP-ID in SG2 NAD+MR mit Rolle NB nicht vorhanden", art: "voraussetzung" },
  "38": { text: "Wenn FTX+Z04/Z05 vorhanden", art: "voraussetzung" },
  "45": { text: "Wenn MP-ID in SG2 NAD+MS mit Rolle MSB nicht vorhanden", art: "voraussetzung" },
  "46": { text: "Wenn SG29 IMD++Z46 vorhanden", art: "voraussetzung", check: {"tag": "IMD", "qual": "Z46", "neg": false} },
  "47": { text: "Wenn SG29 IMD++Z46 nicht vorhanden", art: "voraussetzung", check: {"tag": "IMD", "qual": "Z46", "neg": true} },
  "51": { text: "Wenn BGM+Z48 vorhanden", art: "voraussetzung", check: {"tag": "BGM", "qual": "Z48", "neg": false} },
  "54": { text: "Wenn FTX+Z06 vorhanden", art: "voraussetzung", check: {"tag": "FTX", "qual": "Z06", "neg": false} },
  "55": { text: "Wenn DTM+469 (Beginn zum nächstmöglichen Termin) nicht vorhanden", art: "voraussetzung" },
  "56": { text: "Wenn DTM+203 (Ausführungsdatum) nicht vorhanden", art: "voraussetzung" },
  "57": { text: "Wenn im selben SG2 NAD DE3124 nicht vorhanden", art: "voraussetzung" },
  "60": { text: "MP-ID nur aus Sparte Gas DE3055: 9 GS1 X 332 DE, DVGW Service & Consult GmbH X", art: "voraussetzung" },
  "61": { text: "MP-ID nur aus Sparte Strom", art: "voraussetzung" },
  "62": { text: "MP-ID mit Rolle MSB", art: "voraussetzung" },
  "63": { text: "MP-ID mit Rolle NB", art: "voraussetzung" },
  "64": { text: "Wenn SG2 NAD+Z03 nicht vorhanden", art: "voraussetzung", check: {"tag": "NAD", "qual": "Z03", "neg": true} },
  "65": { text: "Wenn FTX+Z08 vorhanden", art: "voraussetzung", check: {"tag": "FTX", "qual": "Z08", "neg": false} },
  "67": { text: "Wenn DTM+163 nicht vorhanden", art: "voraussetzung", check: {"tag": "DTM", "qual": "163", "neg": true} },
  "68": { text: "Wenn DTM+7 nicht vorhanden", art: "voraussetzung", check: {"tag": "DTM", "qual": "7", "neg": true} },
  "69": { text: "Wenn NAD+Z23 nicht vorhanden", art: "voraussetzung", check: {"tag": "NAD", "qual": "Z23", "neg": true} },
  "70": { text: "Wenn NAD+Z03 nicht vorhanden", art: "voraussetzung", check: {"tag": "NAD", "qual": "Z03", "neg": true} },
  "75": { text: "Wenn für den erforderlichen Wert keine Zählzeit benötigt wird", art: "voraussetzung" },
  "76": { text: "Wenn in derselben SG29 mit Z54 in LIN DE1229 (Erforderliches Produkt der Marktlokation) das PIA+5 DE7140 mit einem Messprodukt aus Codeliste der Konfigurationen, Kapitel 2.1.1 „Standard-Messprodukt der Marktlokation mit der Wahlmöglichkeit der Zuordnung einer Zählzeit“ vorhanden ist", art: "voraussetzung" },
  "77": { text: "Wenn im selben CCI im DE7059 der Code Z39 (Code der Zählzeitdefinition) vorhanden ist", art: "voraussetzung" },
  "78": { text: "Wenn in derselben SG29 mit Z55 in LIN DE1229 (Erforderliches Produkt der Netzlokation) das PIA+5 DE7140 mit einem Messprodukt aus Codeliste der Konfigurationen, Kapitel 2 „Codeliste der Standard-Messprodukt Strom für Werte nach Typ 1“ mit der Werteigenschaft „Blindarbeit“ vorhanden ist.", art: "voraussetzung" },
  "79": { text: "Wenn eine andere SG29 mit Z54 in LIN DE1229 (Erforderliches Produkt der Marktlokation) mit PIA+5+9991000000078:Z11 (für Wirkarbeit Lastgang 1/4 stündlich) vorhanden ist", art: "voraussetzung" },
  "80": { text: "Wenn keine andere SG29 mit Z54 in LIN DE1229 (Erforderliches Produkt der Marktlokation) mit PIA+5+9991000000078:Z11 (Wirkarbeit Lastgang 1/4 stündlich) vorhanden ist", art: "voraussetzung" },
  "81": { text: "Wenn in derselben SG29 mit Z54 in LIN DE1229 (Erforderliches Produkt der Marktlokation), das PIA+5+9991000000078:Z11 (Wirkarbeit Lastgang 1/4 stündlich) vorhanden ist", art: "voraussetzung" },
  "82": { text: "Wenn eine andere SG29 mit Z54 in LIN DE1229 (Erforderliches Produkt der Marktlokation) mit PIA+5 DE7140 mit einem Messprodukt aus Codeliste der Konfigurationen, Kapitel 2.1.1 „Standard-Messprodukt der Marktlokation mit der Wahlmöglichkeit der Zuordnung einer Zählzeit“ vorhanden ist", art: "voraussetzung" },
  "83": { text: "Wenn keine andere SG29 mit Z54 in LIN DE1229 (Erforderliches Produkt der Marktlokation) mit PIA+5 DE7140 mit einem Messprodukt aus Codeliste der Konfigurationen, Kapitel 2.1.1 „Standard-Messprodukt der Marktlokation mit der Wahlmöglichkeit der Zuordnung einer Zählzeit“ vorhanden ist", art: "voraussetzung" },
  "84": { text: "IMD++Z14+Z07 vorhanden", art: "voraussetzung" },
  "85": { text: "Wenn in derselben SG29 mit Z54 in LIN DE1229 (Erforderliches Produkt der Marktlokation), das PIA+5+9991000000086:Z11 (Wirkarbeit höchste 1/4 Stunde im Monat) vorhanden ist", art: "voraussetzung" },
  "86": { text: "Wenn in derselben SG29 mit Z19 in LIN DE1229 (Erforderliches Produkt der Messlokation) das PIA+5 DE7140 mit einem Messprodukt aus Codeliste der Konfigurationen Kapitel 2.3.1 \"Standard-Messprodukt der Messlokation mit der Wahlmöglichkeit der Zuordnung einer Zählzeit\" vorhanden ist", art: "voraussetzung" },
  "87": { text: "Wenn FTX+Z09/Z10 vorhanden", art: "voraussetzung" },
  "91": { text: "Wenn in diesem Datenelement kein anderes Paket in dieser SG30 in derselben SG29 LIN zur Möglichkeit der Angabe von mindestens einem anderen Code führt.", art: "voraussetzung" },
  "93": { text: "Wenn in derselben Nachricht eine SG29 mit Z16 in LIN DE1229 (Erforderliches Produkt der Tranche) nicht vorhanden", art: "voraussetzung" },
  "94": { text: "Wenn in derselben Nachricht eine SG29 mit Z54 in LIN DE1229 (Erforderliches Produkt der Marktlokation) nicht vorhanden", art: "voraussetzung" },
  "95": { text: "Messprodukt-Code aus dem Kapitel 2.1 \"Standard-Messprodukte der Marktlokation\" der Codeliste der Konfigurationen", art: "voraussetzung" },
  "96": { text: "Messprodukt-Code aus dem Kapitel 2.2 \"Standard-Messprodukte der Tranche\" der Codeliste der Konfigurationen", art: "voraussetzung" },
  "97": { text: "Wenn FTX+Z10 vorhanden", art: "voraussetzung", check: {"tag": "FTX", "qual": "Z10", "neg": false} },
  "99": { text: "Wenn FTX+Z08/Z10 vorhanden", art: "voraussetzung" },
  "100": { text: "Messprodukt-Code aus dem Kapitel 2.3 \"Standard-Messprodukte der Messlokation\" der Codeliste der Konfigurationen", art: "voraussetzung" },
  "101": { text: "Wenn MP-ID in SG2 NAD+MR mit Rolle MSB in der Sparte Gas nicht vorhanden", art: "voraussetzung" },
  "102": { text: "Wenn in derselben SG29 LIN das CCI+++Z25 (Geräteart Wandler) vorhanden", art: "voraussetzung" },
  "103": { text: "Wenn in derselben SG29 LIN das CCI+++Z25 (Geräteart Wandler) nicht vorhanden", art: "voraussetzung" },
  "104": { text: "Wenn MP-ID in SG2 NAD+VY mit Rolle LF vorhanden", art: "voraussetzung" },
  "105": { text: "Wenn die bisherige Konfiguration mit Zählzeiten des LF vom LF beendet werden soll", art: "voraussetzung" },
  "106": { text: "wenn IMD++Z60 (Abbestellung Messprodukt mit Zählzeitdefinition des LF) nicht vorhanden", art: "voraussetzung" },
  "107": { text: "Wenn IMD++Z57 (Abbestellung Zählzeitdefinition) nicht vorhanden", art: "voraussetzung" },
  "108": { text: "Wenn RFF+AGK (Konfigurations-ID) nicht vorhanden", art: "voraussetzung" },
  "109": { text: "Wenn LOC+172 (Meldepunkt) nicht vorhanden", art: "voraussetzung" },
  "110": { text: "wenn DTM+163 (Beginn Zeitraum für Wertanfrage) vorhanden", art: "voraussetzung" },
  "112": { text: "Wenn in derselben SG29 LIN++Z54 (Erforderliches Produkt der Marktlokation), das PIA+5+9991000000078: Z11 (Wirkarbeit Lastgang 1/4 stündlich) vorhanden ist", art: "voraussetzung" },
  "113": { text: "Wenn LIN DE1229 mit Code Z42 (Zählzeitdefinition) vorhanden", art: "voraussetzung" },
  "114": { text: "Wenn LIN DE1229 mit Code Z69 (Schaltzeitdefinition) vorhanden", art: "voraussetzung" },
  "115": { text: "Wenn LIN DE1229 mit Code Z70 (Leistungskurvendefinition) vorhanden", art: "voraussetzung" },
  "117": { text: "Wenn SG29 LIN++Z64 (Erforderliches Produkt Schaltzeitdefinitionen) vorhanden", art: "voraussetzung" },
  "118": { text: "Wenn SG29 LIN++Z65 (Erforderliches Produkt Leistungskurvendefinitionen) vorhanden", art: "voraussetzung" },
  "119": { text: "Wenn SG29 LIN++Z66 (Erforderliches Produkt Ad-hoc-Steuerkanal) vorhanden", art: "voraussetzung" },
  "120": { text: "Wenn SG29 LIN++Z67 (Erforderliches Messprodukt für Werte nach Typ 2 aus Backend) vorhanden", art: "voraussetzung" },
  "121": { text: "Wenn SG29 LIN++Z68 (Erforderliches Produkt Konfigurationserlaubnis für Werte nach Typ 2 aus SMGW) vorhanden", art: "voraussetzung" },
  "122": { text: "Wenn SG1 RFF+Z41 (Referenznummer des Vorgangs der Anmeldung nach WiM) nicht vorhanden", art: "voraussetzung" },
  "123": { text: "Wenn DTM+203 (Ausführungsdatum) nicht vorhanden", art: "voraussetzung" },
  "124": { text: "Wenn SG1 RFF+Z41 (Referenznummer des Vorgangs der Anmeldung nach WiM) vorhanden", art: "voraussetzung" },
  "125": { text: "Es sind nur die Konfigurations-Produkte erlaubt, die in der Codeliste der Konfigurationen im Kapitel 4.1 „Konfigurationsprodukte Schaltzeitdefinition“ enthalten sind.", art: "voraussetzung" },
  "126": { text: "Es sind nur die Konfigurations-Produkte erlaubt, die in der Codeliste der Konfigurationen im Kapitel 4.2 „Konfigurationsprodukte Leistungskurvendefinition“ enthalten sind.", art: "voraussetzung" },
  "127": { text: "Es sind nur die Konfigurations-Produkte erlaubt, die in der Codeliste der Konfigurationen im Kapitel 4.3 „Konfigurationsprodukte Ad-Hoc-Steuerkanal“ enthalten sind.", art: "voraussetzung" },
  "128": { text: "Es sind nur die Messprodukte erlaubt, die in der Codeliste der Konfigurationen im Kapitel 4.5 „Messprodukte für Werte nach Typ 2 aus Backend für LF und NB“ enthalten sind.", art: "voraussetzung" },
  "129": { text: "Es sind nur die Messprodukte erlaubt, die in der Codeliste der Konfigurationen im Kapitel 4.4 „Messprodukte mit Konfigurationserlaubnis für Werte nach Typ 2 aus SMGW“ enthalten sind.", art: "voraussetzung" },
  "130": { text: "Wenn in LOC+172 DE3225 (Meldepunkt) die ID einer Marktlokation angegeben ist", art: "voraussetzung" },
  "131": { text: "Wenn in LOC+172 DE3225 (Meldepunkt) die ID einer Messlokation angegeben ist", art: "voraussetzung" },
  "132": { text: "Wenn in LOC+172 DE3225 (Meldepunkt) die ID einer Netzlokation angegeben ist", art: "voraussetzung" },
  "133": { text: "Wenn in LOC+172 DE3225 (Meldepunkt) die ID einer Steuerbaren Ressource angegeben ist", art: "voraussetzung" },
  "134": { text: "Wenn die Position in der ursprünglichen Antwort auf die Bestellung aus SG1 RFF+Z42 vorhanden war und reklamiert werden soll", art: "voraussetzung" },
  "135": { text: "Wenn SG29 LIN++Z64 (Erforderliches Produkt Schaltzeitdefinitionen) nicht vorhanden", art: "voraussetzung" },
  "136": { text: "Wenn SG29 LIN++Z65 (Erforderliches Produkt Leistungskurvendefinitionen) nicht vorhanden", art: "voraussetzung" },
  "137": { text: "Wenn SG29 LIN++Z66 (Erforderliches Produkt Ad-hoc-Steuerkanal) nicht vorhanden", art: "voraussetzung" },
  "138": { text: "Wenn SG29 LIN++Z67 (Erforderliches Messprodukt für Werte nach Typ 2 aus Backend) nicht vorhanden", art: "voraussetzung" },
  "139": { text: "Wenn SG29 LIN++Z68 (Erforderliches Produkt Konfigurationserlaubnis für Werte nach Typ 2 aus SMGW) nicht vorhanden", art: "voraussetzung" },
  "140": { text: "Messprodukt-Code aus dem Kapitel 2.4 \"Standard-Messprodukte der Netzlokation\" der Codeliste der Konfigurationen", art: "voraussetzung" },
  "141": { text: "Es sind nur die Messprodukt-Position-Codes erlaubt, die in der Codeliste der Konfigurationen im Kapitel 4.7 „Art der Werte für Messprodukte nach Typ 2“ enthalten sind.", art: "voraussetzung" },
  "142": { text: "Wenn innerhalb derselben SG29 LIN im PIA+5 DE7140 (Erforderliches Produkt Konfigurationserlaubnis für Werte nach Typ 2 aus SMGW) ein Produkt angegeben ist, das in der Codeliste der Konfigurationen im Kapitel 4.4 „Messprodukte mit Konfigurationserlaubnis für Werte nach Typ 2 aus SMGW“ in der Spalte \"Auslöser\" mit dem Wert \"Bei Schwellwertunter- / -überschreitung\" gekennzeichnet ist.", art: "voraussetzung" },
  "143": { text: "Wenn in LOC+172 DE3225 (Meldepunkt) die ID einer Steuerbaren Ressource angegeben ist", art: "voraussetzung" },
  "147": { text: "wenn im DE3155 in demselben COM der Code EM vorhanden ist", art: "voraussetzung" },
  "148": { text: "wenn im DE3155 in demselben COM der Code TE / FX / AJ / AL vorhanden ist", art: "voraussetzung" },
  "152": { text: "Wenn in SG29 LIN (Erforderliches Produkt der Messlokation) das PIA+5 DE7140 mit einem Produkt-Code vorhanden ist der in der Codeliste der Konfigurationen im Kapitel 7 \"Produkte zur Bestellung einer Änderung an einer Lokation\" in der \"Spalte Bezeichnung\" mit dem Wert \"weitere Energieflussrichtung\" vorhanden ist.", art: "voraussetzung" },
  "153": { text: "Es sind nur die Produkt-Codes erlaubt, die in der Codeliste der Konfigurationen im Kapitel 7 \"Produkte zur Bestellung einer Änderung an einer Lokation\" die in der Spalte \"Ebene\" mit dem Wert \"Messlokation\" vorhanden sind.", art: "voraussetzung" },
  "154": { text: "Es sind nur die Produkt-Codes erlaubt, die in der Codeliste der Konfigurationen im Kapitel 7 \"Produkte zur Bestellung einer Änderung an einer Lokation\" die in der Spalte \"Ebene\" mit dem Wert \"Netzlokation\" vorhanden sind.", art: "voraussetzung" },
  "155": { text: "Es sind nur die Produkt-Codes erlaubt, die in der Codeliste der Konfigurationen im Kapitel 7 \"Produkte zur Bestellung einer Änderung an einer Lokation\" die in der Spalte \"Ebene\" mit dem Wert \"Steuerbare Ressource\" vorhanden sind.", art: "voraussetzung" },
  "156": { text: "Es sind weiterhin nur die Produkt-Codes erlaubt, die in der Codeliste der Konfigurationen im Kapitel 7 \"Produkte zur Bestellung einer Änderung an einer Lokation\" die in der Spalte \"Produkt gegenüber MSB von Marktrolle bestellbar\" mit einem \"X\" in der Spalte \"NB\" gekennzeichnet ist.", art: "voraussetzung" },
  "157": { text: "Es sind weiterhin nur die Produkt-Codes erlaubt, die in der Codeliste der Konfigurationen im Kapitel 7 \"Produkte zur Bestellung einer Änderung an einer Lokation\" die in der Spalte \"Produkt gegenüber MSB von Marktrolle bestellbar\" mit einem \"X\" in der Spalte \"LF\" gekennzeichnet ist.", art: "voraussetzung" },
  "158": { text: "Es sind nur die Produkt-Codes erlaubt, die in der Codeliste der Konfigurationen im Kapitel 6.2 \"Produkte zur Bestellung einer Änderung von Abrechnungsdaten\" genannt sind.", art: "voraussetzung" },
  "159": { text: "Wenn in derselben SG29 LIN im PIA+5 (Erforderliches Produkt Abrechnungsdaten) DE7140 ein Produkt-Code genannt ist, der in der Codeliste der Konfigurationen im Kapitel 6.2 \"Produkte zur Bestellung einer Änderung von Abrechnungsdaten\" in der Spalte \"Code der Produkteigenschaft (Wertebereich)\" mit einem Code befüllt ist.", art: "voraussetzung" },
  "160": { text: "Es sind nur die Codes der Produkteigenschaft zu dem in derselben SG29 LIN im PIA+5 (Erforderliches Produkt Abrechnungsdaten) DE7140 erlaubt, die in der Codeliste der Konfigurationen im Kapitel 6.2 \"Produkte zur Bestellung einer Änderung von Abrechnungsdaten\" in derselben Zeile wie der Produkt-Code stehen und in der Spalte \"Code der Produkteigenschaft (Wertebereich)\" genannt sind.", art: "voraussetzung" },
  "161": { text: "Wenn in derselben SG29 LIN (Erforderliches Produkt Abrechnungsdaten) das SG30 CAV+ZH9 (Code der Produkteigenschaft) nicht vorhanden ist.", art: "voraussetzung" },
  "162": { text: "Es ist nur der Wertebereich erlaubt, der zu dem in derselben SG29 LIN im PIA+5 (Erforderliches Produkt Abrechnungsdaten) DE7140 genannten Produkt, das in der Codeliste der Konfigurationen im Kapitel 6.2 \"Produkte zur Bestellung einer Änderung von Abrechnungsdaten\" in derselben Zeile wie der Produkt-Code in der Spalte \"Wertedetails für Position\" genannt ist.", art: "voraussetzung" },
  "163": { text: "Wenn innerhalb der Nachricht eine SG30 CCI+++ZA9 (Messprodukt für Übertragungsnetzbetreiber relevant) vorhanden ist.", art: "voraussetzung" },
  "164": { text: "Wenn die Konfiguration der in SG34 RFF+Z20 DE1154 (Referenz auf ID der Tranche) genannte Tranche innerhalb derselben SG29 LIN++Z16 (Erforderliches Produkt der Tranche) unverändert bestehen bleibt.", art: "voraussetzung" },
  "165": { text: "Wenn die Konfiguration der in SG34 RFF+Z20 DE1154 (Referenz auf ID der Tranche) genannte Tranche innerhalb derselben SG29 LIN++Z16 (Erforderliches Produkt der Tranche) aufgrund einer Zuordnung eines LF neu konfiguriert werden soll oder die Tranche neu gebildet wurde.", art: "voraussetzung" },
  "166": { text: "Wenn es sich um die Einrichtung der Konfigurationen aufgrund einer Zuordnung eines LF zu einer Tranche handelt", art: "voraussetzung" },
  "167": { text: "Wenn SG2 NAD+DP (Meldepunkt), SG3 RFF+Z20 (Referenz auf ID der Tranche) vorhanden", art: "voraussetzung" },
  "168": { text: "Wenn SG2 NAD+DP (Meldepunkt), SG3 RFF+Z20 (Referenz auf ID der Tranche) nicht vorhanden", art: "voraussetzung" },
  "169": { text: "Wenn in SG29 LIN++Z19 (Erforderliches Produkt der Messlokation) in SG30 CCI (Zugeordnete Zählzeitdefinition im DE7059 der Code Z39 (Code der Zählzeitdefinition) vorhanden ist", art: "voraussetzung" },
  "170": { text: "Wenn in derselben SG29 LIN die SG30 CCI+Z37++ZD1 (Basis zur Bildung der Tranchengröße) (Prozentual) vorhanden", art: "voraussetzung" },
  "171": { text: "Wenn in derselben SG29 LIN (Erforderliches Produkt der Tranche) das IMD+++Z64 (Leistungsbeschreibung Konfiguration) (Neukonfiguration) vorhanden ist", art: "voraussetzung" },
  "172": { text: "Wenn es sich bei der in SG2 LOC+172 DE3225 genannten Lokation um die Integration in eine Kundenanlage oder Herauslösung aus einer Kundenanlage nach §20 Abs.1d EnWG handelt. Details siehe UTILMD AHB Strom.", art: "voraussetzung" },
  "173": { text: "Wenn IMD++Z66 (Beendigung Konfiguration aufgrund Überführung der Marktlokation zu ruhender Marktlokation) vorhanden", art: "voraussetzung" },
  "174": { text: "Wenn IMD++Z67 (Aktivierung Konfiguration in der derzeit ruhenden Marktlokation) vorhanden", art: "voraussetzung" },
  "175": { text: "Wenn SG2 NAD+DP (Meldepunkt), SG3 RFF+Z59 (Referenz auf die ID der Marktlokation der Kundenanlage) vorhanden", art: "voraussetzung" },
  "176": { text: "Wenn SG2 NAD+DP (Meldepunkt), SG3 RFF+Z59 (Referenz auf die ID der Marktlokation der Kundenanlage) nicht vorhanden", art: "voraussetzung" },
  "177": { text: "Wenn IMD++Z66 (Beendigung Konfiguration aufgrund Überführung der Marktlokation zu ruhender Marktlokation) nicht vorhanden", art: "voraussetzung" },
  "178": { text: "Wenn vom NB eine Abtretungserklärung vom Kunden gewünscht ist.", art: "voraussetzung" },
  "179": { text: "Wenn in derselben SG29 LIN im PIA+5 (Erforderliches Produkt Abrechnungsdaten) DE7140 das Produkt \"Empfänger der Vergütung zur Einspeisung\" aus der Codeliste der Konfigurationen im Kapitel 6.2 \"Produkte zur Bestellung einer Änderung von Abrechnungsdaten\" genannt ist und in derselben SG29 LIN im SG30 CAV+ZH9 (Code der Produkteigenschaft) im DE7110 aus der Spalte \"Code der Produkteigenschaft (Wertebereich)\" mit dem Code \"Lieferant\" gefüllt ist.", art: "voraussetzung" },
  "180": { text: "Wenn in derselben SG29 LIN im PIA+5 (Erforderliches Produkt Abrechnungsdaten) DE7140 ein Produkt-Code genannt ist der in der Codeliste der Konfigurationen im Kapitel 6.2 \"Produkte zur Bestellung einer Änderung von Abrechnungsdaten\" in der Spalte „Wertedetails für Position“ die ggf. enthaltene Bedingung erfüllt ist.", art: "voraussetzung" },
  "181": { text: "Wenn BGM+Z93 (Bestellung eines Angebots Änderung der Technik der Lokation) vorhanden", art: "voraussetzung" },
  "182": { text: "Wenn BGM+Z12 (Änderung der Technik der Lokation) vorhanden.", art: "voraussetzung" },
  "183": { text: "Wenn MP-ID in NAD+MS aus Sparte Gas", art: "voraussetzung" },
  "492": { text: "wenn MP-ID in NAD+MR aus Sparte Strom", art: "voraussetzung" },
  "493": { text: "wenn MP-ID in NAD+MR aus Sparte Gas", art: "voraussetzung" },
  "494": { text: "Das hier genannte Datum muss der Zeitpunkt sein, zu dem das Dokument erstellt wurde, oder ein Zeitpunkt, der davor liegt.", art: "voraussetzung" },
  "495": { text: "Der Zeitpunkt muss ≤ dem Wert im DE2380 des DTM+137 sein", art: "voraussetzung" },
  "500": { text: "Hinweis: Zählpunkt der BAS", art: "hinweis" },
  "501": { text: "Hinweis: Zählpunkt der DZR", art: "hinweis" },
  "503": { text: "Hinweis: Angabe eines technischen Ansprechpartners für die Geräteübernahme", art: "hinweis" },
  "506": { text: "Hinweis: Datum, bis zu dem der MSBA zur Fortführung verpflichtet wird", art: "hinweis" },
  "514": { text: "Hinweis: Das Abonnement kann frühestens ab dem aktuellen Liefermonat beim Netzbetreiber gestartet werden.", art: "hinweis" },
  "515": { text: "Hinweis: Das angegebene Betrachtungszeitintervall bestimmt beim Start Abo bzw. Ende Abo ab bzw. bis wann (einschließlich) das Abo laufen soll.", art: "hinweis" },
  "517": { text: "Hinweis: Zählpunkt der LF-AASZR", art: "hinweis" },
  "518": { text: "Hinweis: Das angegebene Ausführungsdatum bestimmt beim Start Abo bzw. Ende Abo ab bzw. bis wann (einschließlich) das Abo laufen soll.", art: "hinweis" },
  "519": { text: "Hinweis: Bei Gas bezieht sich die Anforderung immer sowohl auf die vorläufigen Profilwerte als auch auf die endgültigen Profilwerte, falls diese bereits vorliegen.", art: "hinweis" },
  "521": { text: "Hinweis: Verwendung der ID der Marktlokation", art: "hinweis" },
  "522": { text: "Hinweis: Verwendung der ID der Messlokation", art: "hinweis" },
  "523": { text: "Hinweis: Verwendung der ID der Tranche", art: "hinweis" },
  "525": { text: "Hinweis: Wert aus BGM DE1004 der MSCONS", art: "hinweis" },
  "527": { text: "Hinweis: Zählpunkt der BG-SZR (Kategorie B)", art: "hinweis" },
  "530": { text: "Hinweis: Wert aus BGM+310 DE1004 der QUOTES mit der das Angebot erfolgt ist.", art: "hinweis" },
  "531": { text: "Hinweis: Wert aus LIN DE1082 der QUOTES, mit der das Angebot erfolgt ist", art: "hinweis" },
  "532": { text: "Hinweis: Wert aus BGM+Z29 DE1004 der QUOTES, mit der das Angebot zur Abrechnung des Messstellenbetriebs erfolgt ist.", art: "hinweis" },
  "533": { text: "Hinweis: Gerichtsvollzieher hat Termin vorgegeben", art: "hinweis" },
  "535": { text: "Hinweis: Verwendung der ID der Messlokation der Sparte Strom", art: "hinweis" },
  "536": { text: "Hinweis: Vorgangsnummer aus IDE DE7402 der UTILTS mit BGM+Z59", art: "hinweis" },
  "539": { text: "Hinweis: Es sind nur Codes von Zählzeiten aus Liste des NB anzugeben", art: "hinweis" },
  "540": { text: "Hinweis: Es sind nur Codes von Zählzeiten aus Liste des LF anzugeben", art: "hinweis" },
  "542": { text: "Hinweis: Wert aus BGM+Z57 DE1004 der QUOTES mit der das Angebot erfolgt ist.", art: "hinweis" },
  "543": { text: "Hinweis: Wert aus BGM+Z57 DE1004 der ORDERS mit der die Bestellung der Werte erfolgt ist.", art: "hinweis" },
  "545": { text: "Hinweis: Es werden nur die Messprodukte der Messlokationen angegeben, die für die in der SG2 genannte Marktlokation bzw. deren Tranchen erforderlich sind. Messprodukte an der Messlokation für weitere Marktlokationen bleiben unverändert.", art: "hinweis" },
  "547": { text: "Hinweis: Dokumentennummer aus BGM+Z60 DE1004 der UTILTS", art: "hinweis" },
  "548": { text: "Hinweis: Wenn die Änderung der Gerätekonfiguration mit einer Zählzeit übermittelt wird, ist hier die MP-ID des Eigentümers der Liste der Zählzeit einzutragen. Wenn anstatt der bisherigen Zählzeit keine Zählzeit mehr verwendet werden soll ist hier die MP-ID des Eigentümers der Liste der Zählzeit einzutragen aus welcher bisher die Zählzeit verwendet wurde.", art: "hinweis" },
  "549": { text: "Hinweis: Findet bei der Reklamation von Zählerständen immer Anwendung. Einzige Ausnahme ist, wenn es sich um die Reklamation eines fehlenden Zählerstandes aufgrund einer Turnusablesung handelt, bei welcher der MSB am Objekt der Marktlokation die Information zur \"geplanten Turnusablesung des MSB (Strom)\" in der UTILMD im SG6 DTM+752 als Ablesezeitraum (DE2379 mit Code 104 MMWW-MMWW) in den vorherigen Stammdaten übermittelt hatte, denn dann ist keine Zeitpunktangabe möglich, sondern das Zeitintervall in der Segmentausprägung DTM+163 / DTM+164 zu verwenden.", art: "hinweis" },
  "550": { text: "Hinweis: Findet nur dann Anwendung, wenn es sich um die Reklamation eines fehlenden Zählerstandes aufgrund einer Turnusablesung handelt, bei welcher der MSB am Objekt der Marktlokation die Information zur \"geplanten Turnusablesung des MSB (Strom)\" in der UTILMD im SG6 DTM+752 als Ablesezeitraum (DE2379 mit Code 104 MMWW-MMWW) in den vorherigen Stammdaten übermittelt hatte.", art: "hinweis" },
  "551": { text: "Hinweis: Die SG29 ist so oft zu wiederholen, dass alle Messprodukte und Zählzeiten genannt werden, die ab dem in DTM+203 genannten Zeitpunkt auf der Messlokation durch den MSB konfiguriert werden müssen. Nicht genannte Messprodukte sind ab dem Zeitpunkt nicht mehr in der Konfiguration enthalten.", art: "hinweis" },
  "552": { text: "Hinweis: Verwendung der ID der Netzlokation", art: "hinweis" },
  "553": { text: "Hinweis: Verwendung der ID der Steuerbaren Ressource", art: "hinweis" },
  "554": { text: "Hinweis: Wert aus BGM+Z74 DE1004 der QUOTES mit der das Angebot erfolgt ist.", art: "hinweis" },
  "555": { text: "Hinweis: Vorgangsnummer aus SG4 IDE+24 DE7402 der UTILMD mit BGM+E01 mit der die Anmeldung des MSB-Wechsels erfolgt ist.", art: "hinweis" },
  "557": { text: "Hinweis: Es werden nur die Messprodukte der Messlokationen angegeben, die für die in der SG2 genannte Netzlokation erforderlich sind. Messprodukte an der Messlokation für weitere Netzlokationen oder Marktlokationen bleiben unverändert.", art: "hinweis" },
  "558": { text: "Hinweis: Dokumentennummer aus BGM+Z78 DE1004 der UTILTS", art: "hinweis" },
  "559": { text: "Hinweis: Dokumentennummer aus BGM+Z79 DE1004 der UTILTS", art: "hinweis" },
  "560": { text: "Hinweis: Vorgangsnummer aus IDE DE7402 der UTILTS mit BGM+Z80", art: "hinweis" },
  "561": { text: "Hinweis: Vorgangsnummer aus IDE DE7402 der UTILTS mit BGM+Z81", art: "hinweis" },
  "562": { text: "Hinweis: Wert aus BGM+Z73 DE1004 der IFTSTA mit der die Antwort auf die Bestellung der Konfiguration übermittelt wurde", art: "hinweis" },
  "563": { text: "Hinweis: Vorgangsnummer aus CNI DE1490 der IFTSTA mit BGM+Z73 mit der die Antwort auf die Bestellung der Konfiguration übermittelt wurde", art: "hinweis" },
  "564": { text: "Hinweis: Für den Empfang der Werte nach Typ 2 aus dem SMGW.", art: "hinweis" },
  "566": { text: "Hinweis: Verwendung der ID der Technischen Ressource", art: "hinweis" },
  "567": { text: "Hinweis: Es darf nur eine Information im DE3148 übermittelt werden", art: "hinweis" },
  "568": { text: "Hinweis: Wenn die Einrichtung der Konfiguration mit einer Zählzeit übermittelt wird, ist hier die MP-ID des NB als Eigentümer der Liste der Zählzeit einzutragen.", art: "hinweis" },
  "569": { text: "Hinweis: MaBiS-Zählpunkt der LF-SZR", art: "hinweis" },
  "570": { text: "Hinweis: zur Angabe von Kontaktdaten des Kunden des Lieferanten um die Änderung an der Technik zu vereinfachen.", art: "hinweis" },
  "571": { text: "Hinweis: MSB der Marktlokation, an den die Werte der weiteren Energieflussrichtung der Messlokation zu übermitteln sind.", art: "hinweis" },
  "572": { text: "Hinweis: MSB der Marktlokation der Kundenanlage, in der die betroffene Lokation integriert wird.", art: "hinweis" },
  "573": { text: "Hinweis: Es ist eine URI IPv4 für die Bereitstellung der Werte anzugeben.", art: "hinweis" },
  "574": { text: "Hinweis: Es ist eine URI IPv6 für die Bereitstellung der Werte anzugeben.", art: "hinweis" },
  "575": { text: "Hinweis: Wenn der gewünschte Änderungszeitpunkt ein fixer Zeitpunkt ist.", art: "hinweis" },
  "576": { text: "Hinweis: Wenn der gewünschte Änderungszeitpunkt ein nächst möglicher Termin zum oder nach dem angegebenen Zeitpunkt ist.", art: "hinweis" },
  "577": { text: "Hinweis: Wert aus BGM+Z93 (Bestellung eines Angebots Änderung der Technik der Lokation) DE1004 der QUOTES mit der das Angebot erfolgt ist.", art: "hinweis" },
  "578": { text: "Hinweis: Wert aus BGM DE1004 der PRICAT mit der das Preisblatt B des MSB, auf die aus Sicht des NB das Angebot basiert, übermittelt wurde.", art: "hinweis" },
  "579": { text: "Hinweis: Angabe des Beginnzeitpunkts des gewünschten Umsetzungstermins aus Sicht des Bestellers.", art: "hinweis" },
  "580": { text: "Hinweis: Angabe des Endezeitpunkts des gewünschten Umsetzungstermins aus Sicht des Bestellers.", art: "hinweis" },
  "591": { text: "Hinweis: Wenn es sich um die Bestellung eines vorherigen Angebots im Rahmen der BDEW Anwendungshilfe \"Prozesse zur Änderung der Technik an Lokationen\" handelt.", art: "hinweis" },
  "592": { text: "Hinweis: wenn es sich um die Beauftragung einer Änderung gemäß WiM Teil1 UC \"Messlokationsänderung\" handelt.", art: "hinweis" },
  "903": { text: "Format: Möglicher Wert: 1", art: "format" },
  "906": { text: "Format: max. 3 Nachkommastellen", art: "format" },
  "911": { text: "Format: Mögliche Werte: 1 bis n, je Nachricht oder Segmentgruppe bei 1 beginnend und fortlaufend aufsteigend", art: "format" },
  "914": { text: "Format: Möglicher Wert: >0", art: "format" },
  "922": { text: "Format: TR-ID", art: "format" },
  "930": { text: "Format: max. 2 Nachkommastellen", art: "format" },
  "931": { text: "Format: ZZZ = +00", art: "format" },
  "939": { text: "Format: Die Zeichenkette muss die Zeichen @ und . enthalten", art: "format" },
  "940": { text: "Format: Die Zeichenkette muss mit dem Zeichen + beginnen und danach dürfen nur noch Ziffern folgen", art: "format" },
  "950": { text: "Format: Marktlokations-ID", art: "format" },
  "951": { text: "Format: Zählpunktbezeichnung", art: "format" },
  "955": { text: "Format: Möglicher Wert: <100", art: "format" },
  "960": { text: "Format: Netzlokations-ID", art: "format" },
  "961": { text: "Format: SR-ID", art: "format" },
  "962": { text: "Format: max. 6 Vorkommastellen", art: "format" },
  "967": { text: "Format: Zertifikatskörper gemäß X509.1, BSI TR-03109-4", art: "format" },
  "2001": { text: "Die SG29 ist so oft zu wiederholen, wie ab dem DTM+203 (Ausführungsdatum) Tranchen zu der in der SG2 genannten Marktlokation vorhanden sind.", art: "wiederholbarkeit" },
  "2002": { text: "Ist mindestens zwei Mal anzugeben", art: "wiederholbarkeit" },
  "2003": { text: "Die SG29 ist so oft zu wiederholen, wie ab dem DTM+203 (Ausführungsdatum) Messlokationen zu der in der SG2 genannten Marktlokation vorhanden sind und für jede dieser Messlokationen müssen alle Messprodukte genannt sein, die ab dem DTM+203 (Ausführungsdatum) in der SG2 genannten Marktlokation bzw. deren Tranchen vorhanden sind.", art: "wiederholbarkeit" },
  "2004": { text: "Die SG29 ist so oft zu wiederholen, dass alle Geräte der betroffenen Geräteart die im Rahmen des Gerätewechsels aufgrund MSB-Wechsel getauscht werden sollen genannt sind.", art: "wiederholbarkeit" },
  "2005": { text: "Pro SG29 LIN ist die SG34 RFF+Z09 (Gerätenummer) genau einmal anzugeben", art: "wiederholbarkeit" },
  "2006": { text: "Pro SG29 LIN ist die SG34 RFF+Z09 (Gerätenummer) bis zu dreimal anzugeben", art: "wiederholbarkeit" },
  "2007": { text: "Die SG29 ist so oft zu wiederholen, wie ab dem DTM+203 (Ausführungsdatum) Messlokationen zu der in der SG2 genannten Netzlokation vorhanden sind und für jede dieser Messlokationen müssen alle Messprodukte genannt sein, die ab dem DTM+203 (Ausführungsdatum) in der SG2 genannten Netzlokation vorhanden sind.", art: "wiederholbarkeit" },
  "2050": { text: "Pro Nachricht ist die SG29 genau einmal anzugeben", art: "wiederholbarkeit" },
  "2060": { text: "Pro Nachricht ist die SG29 LIN+Z64 (Erforderliches Produkt Schaltzeitdefinitionen) maximal einmal anzugeben", art: "wiederholbarkeit" },
  "2061": { text: "Pro Nachricht ist die SG29 LIN++Z65 (Erforderliches Produkt Leistungskurvendefinitionen) maximal einmal anzugeben", art: "wiederholbarkeit" },
  "2062": { text: "Pro Nachricht ist die SG29 LIN++Z66 (Erforderliches Produkt Ad-hoc-Steuerkanal) maximal einmal anzugeben", art: "wiederholbarkeit" },
  "2063": { text: "Pro Nachricht ist die SG29 LIN++Z67 (Erforderliches Messprodukt für Werte nach Typ 2 aus Backend) maximal einmal anzugeben", art: "wiederholbarkeit" },
  "2064": { text: "Pro Nachricht ist die SG29 LIN++Z68 (Erforderliches Produkt Konfigurationserlaubnis für Werte nach Typ 2 aus SMGW) maximal einmal anzugeben", art: "wiederholbarkeit" },
  "2065": { text: "Diese SG30 ist so oft zu wiederholen, wie zu den unterschiedlichen Messprodukt-Position-Codes zu dem innerhalb derselben SG29 LIN im PIA+5 DE7140 (Erforderliches Produkt Konfigurationserlaubnis für Werte nach Typ 2 aus SMGW) angegebenen Produkt ein Produkt angegeben ist, das in der Codeliste der Konfigurationen im Kapitel 4.4 „Messprodukte mit Konfigurationserlaubnis für Werte nach Typ 2 aus SMGW“ in der Spalte \"Auslöser\" mit dem Wert \"Bei Schwellwertunter- / -überschreitung\" gekennzeichnet ist.", art: "wiederholbarkeit" },
  "2066": { text: "Die SG3 RFF+Z37 Referenz auf ID der Technischen Ressource ist so oft zu wiederholen, bis alle IDs der Technischen Ressourcen angegeben sind, die der Steuerbaren Ressource in LOC+172 DE3225 (Meldepunkt) mit diesem Vorgang zugeordnet werden sollen genannt sind.", art: "wiederholbarkeit" },
  "2088": { text: "Die SG29 ist so oft zu wiederholen, dass alle Messprodukte ab dem DTM+203 (Ausführungsdatum) zu der in der SG2 genannten Netzlokation genannt sind.", art: "wiederholbarkeit" },
  "2089": { text: "Die SG29 ist so oft zu wiederholen, dass alle Messprodukte ab dem DTM+203 (Ausführungsdatum) zu der in der SG2 genannten Marktlokation genannt sind.", art: "wiederholbarkeit" },
  "2090": { text: "Für 33-stellige ID im SG2 LOC+172 (Meldepunkt) DE3225 mindestens einmal anzugeben", art: "wiederholbarkeit" },
  "2092": { text: "Pro Nachricht ist die SG29 maximal einmal anzugeben", art: "wiederholbarkeit" },
  "2094": { text: "Pro Nachricht ist die SG29 LIN (Positionsdaten) so oft anzugeben, wie Positionen aus dem Angebot, welches in SG1 RFF+AAG (Referenz Nachrichtennummer), DE1154 angegeben ist, bestellt werden sollen.", art: "wiederholbarkeit" },
  "2095": { text: "Diese SG29 ist so oft zu wiederholen, dass alle Produkte zur Lokation die ab dem DTM+203 (Ausführungsdatum) gewünscht sind und deren Kombination gemäß Codeliste der Konfigurationen Kapitel 7 \"Produkte zur Bestellung einer Änderung an einer Lokation\"möglich sind, genannt sind.", art: "wiederholbarkeit" },
  "2096": { text: "Die SG3 Referenz auf die ID der Tranche ist so oft zu wiederholen, wie ab dem DTM+203 (Ausführungsdatum) Tranchen zu der in der SG2 genannten Marktlokation vorhanden sind.", art: "wiederholbarkeit" },
  "2097": { text: "Die SG29 ist so oft zu wiederholen, dass für alle in SG3 Referenz auf ID der Tranche genannten Tranchen mindestens eine SG29 vorhanden ist.", art: "wiederholbarkeit" },
  "2098": { text: "Die SG2 Lieferant an der Lokation ist so oft zu wiederholen, dass für alle in SG3 Referenz auf ID der Tranche genannten Tranchen genau eine SG2 Lieferant der Lokation vorhanden ist.", art: "wiederholbarkeit" },
  "2099": { text: "Die SG2 Lieferant an der Lokation ist genau einmal anzugeben.", art: "wiederholbarkeit" },
};
if (typeof window!=='undefined') window.EdiBedingungen = Object.assign(window.EdiBedingungen||{}, ordersBedingungen);
if (typeof module!=='undefined') module.exports = ordersBedingungen;
