// _bedingungen.js (PRICAT) - AHB-Bedingungen via kohlrahbi-Parser (an unser docx-Layout adaptiert).
// parse_conditions_from_string (kohlrahbi/Hochfrequenz), Quelle AHB_PRICAT_2.0f_20251001_20260930_20251001_ooox_11608.docx.
var pricatBedingungen = {
  "1": { text: "Wenn Vorgängerversion vorhanden", art: "voraussetzung" },
  "2": { text: "Code Z08 Höchstspannung X Z09 Hochspannung X Z10 Mittelspannung X Z11 Niederspannung X", art: "voraussetzung" },
  "3": { text: "Wenn IMD+X vorhanden", art: "voraussetzung", check: {"tag": "IMD", "qual": "X", "neg": false} },
  "4": { text: "Marktlokation mit unterbrechbaren Verbrauchseinrichtung nach § 14a EnWG mit iMS Z20 POG bei verbrauchender X", art: "voraussetzung" },
  "5": { text: "Wenn SG36 IMD+X in diesem IMD vorhanden", art: "voraussetzung" },
  "6": { text: "Wenn in dieser SG36 LIN in DE7140 9990001000798 vorhanden", art: "voraussetzung" },
  "7": { text: "Wenn in dieser SG36 LIN in DE7140 9990001000798 nicht vorhanden", art: "voraussetzung" },
  "8": { text: "Wenn das in DE1001 angegebene Preisblatt vom NB nicht genutzt wird.", art: "voraussetzung" },
  "9": { text: "Wenn BGM DE1373 =11 nicht vorhanden", art: "voraussetzung" },
  "10": { text: "Wenn in dieser SG36 ein weiteres RNG (d. h. für diese Gruppenartikel-ID eine weitere Zone) vorhanden ist, in der der Wert des DE6162 (Wertebereichsgrenze, untere) größer ist als der Wert des DE6162 in diesem RNG", art: "voraussetzung" },
  "12": { text: "je UNB ist nur eine Nachricht mit BGM+Z04 in der Übertragungsdatei erlaubt (nur eine Nachricht je Übertragungsdatei)", art: "voraussetzung" },
  "14": { text: "je UNB ist maximal je Code aus DE1001 eine Nachricht in der Übertragungsdatei erlaubt", art: "voraussetzung" },
  "19": { text: "Nur MP-ID aus Sparte Strom", art: "voraussetzung" },
  "22": { text: "Wenn die Artikel-ID aus dieser SG36 LIN DE7140 in der EDI@Energy Codeliste der Artikelnummern und Artikel-ID in der Spalte \"PRICAT Preisangabe\" ein X hat", art: "voraussetzung" },
  "24": { text: "Wenn in dieser SG36 Wert von LIN DE7140 im Format n1- n2-n1-n8-n2-n1", art: "voraussetzung" },
  "26": { text: "Wenn BGM DE1001 = Z70 vorhanden", art: "voraussetzung" },
  "27": { text: "Wenn BGM DE1001 = Z70 nicht vorhanden", art: "voraussetzung" },
  "28": { text: "Wenn die zugehörige Artikel- ID in der letzten Stelle eine 1 ist", art: "voraussetzung" },
  "29": { text: "Wenn die zugehörige Artikel- ID in der letzten Stelle > 1 ist", art: "voraussetzung" },
  "30": { text: "wenn MP-ID in SG2 NAD+MR in der Rolle LF", art: "voraussetzung" },
  "31": { text: "wenn BGM DE1001 = Z32", art: "voraussetzung" },
  "32": { text: "wenn der Zeitpunkt im DTM+157 DE2380 < 01.01. 2024 00:00 Uhr gesetzlicher deutscher Zeit", art: "voraussetzung" },
  "33": { text: "wenn der Zeitpunkt im DTM+157 DE2380 ≥ 01.01. 2024 00:00 Uhr gesetzlicher deutscher Zeit", art: "voraussetzung" },
  "34": { text: "wenn BGM DE1001 = Z77", art: "voraussetzung" },
  "35": { text: "Wenn das in DE1001 angegebene Preisblatt vom MSB nicht genutzt wird.", art: "voraussetzung" },
  "36": { text: "Wenn MP-ID in SG2 NAD+MR in der Rolle NB", art: "voraussetzung" },
  "37": { text: "Wenn im DE3155 in demselben COM der Code EM vorhanden ist", art: "voraussetzung" },
  "38": { text: "Wenn im DE3155 in demselben COM der Code TE / FX / AJ / AL vorhanden ist", art: "voraussetzung" },
  "39": { text: "Es sind nur Werte aus der EDI@Energy Codeliste der Artikelnummern und Artikel-ID erlaubt, die in der Spalte MaBiS ein X haben", art: "voraussetzung" },
  "40": { text: "Es sind nur Werte aus der EDI@Energy Codeliste der Artikelnummern und Artikel-ID erlaubt, die in der Spalte H ein X haben", art: "voraussetzung" },
  "41": { text: "Es sind nur Werte aus der EDI@Energy Codeliste der Artikelnummern und Artikel-ID erlaubt, die in der Spalte \"PRICAT Codeverwendung\" ein X haben", art: "voraussetzung" },
  "42": { text: "Es sind nur Werte erlaubt, die die Bildungsvorschrift der EDI@Energy Codeliste der Artikelnummern und Artikel-ID erfüllen, und die in der Spalte \"PRICAT Codeverwendung\" ein X haben", art: "voraussetzung" },
  "43": { text: "Wenn BGM DE1001 = Z32 und LIN DE7140 im Format n1-n2-n1-n3, dann muss der hier genannte Zeitpunkt ≥ 01. 01.2024 00:00 Uhr gesetzlicher deutscher Zeit sein", art: "voraussetzung" },
  "44": { text: "Wenn BGM DE1001 = Z77, dann muss der hier genannte Zeitpunkt ≥ 01.10. 2023 00:00 Uhr gesetzlicher deutscher Zeit sein", art: "voraussetzung" },
  "45": { text: "Es sind nur Werte aus der EDI@Energy Codeliste der Artikelnummern und Artikel-ID erlaubt, die in dieser in Kapitel \"Abrechnung Messstellenbetrieb für die Sparte Strom\" genannt sind", art: "voraussetzung" },
  "46": { text: "Es sind nur Werte aus der EDI@Energy Codeliste der Artikelnummern und Artikel-ID erlaubt, die in dieser in Kapitel \"Artikel-ID für den Universalbestellprozess für die Sparte Strom\" genannt sind", art: "voraussetzung" },
  "47": { text: "Wenn BGM DE1001 = Z32 und LIN DE7140 im Format n13, dann muss der hier genannte Zeitpunkt < 01.01. 2024 00:00 Uhr gesetzlicher deutscher Zeit sein", art: "voraussetzung" },
  "48": { text: "Wenn in dieser SG36 LIN in DE7140 einer der Codes 1-01-6- 005 / 1-01-9-001 / 1-01-9-002 / 1-02-0-015 / 1-03-8-001 / 1-03- 8-002 / 1-03-8-003 / 1-03-8-004 / 1-03-9-001 / 1-03-9-002 / 1-03- 9-003 / 1-03-9-004 / 1-07-4-001 vorhanden", art: "voraussetzung" },
  "49": { text: "Wenn in dieser SG36 LIN in DE7140 keiner der Codes 1-01-6- 005 / 1-01-9-001 / 1-01-9-002 / 1-02-0-015 / 1-03-8-001 / 1-03- 8-002 / 1-03-8-003 / 1-03-8-004 / 1-03-9-001 / 1-03-9-002 / 1-03- 9-003 / 1-03-9-004 / 1-07-4-001 vorhanden", art: "voraussetzung" },
  "50": { text: "Wenn MP-ID aus RFF+Z56 mit MP-ID aus NAD+MS identisch ist", art: "voraussetzung" },
  "51": { text: "Wenn BGM+Z54 vorhanden", art: "voraussetzung", check: {"tag": "BGM", "qual": "Z54", "neg": false} },
  "52": { text: "Wenn BGM+Z54 nicht vorhanden", art: "voraussetzung", check: {"tag": "BGM", "qual": "Z54", "neg": true} },
  "53": { text: "Diese SG40 darf genau einmal in der SG36 angegeben werden", art: "voraussetzung" },
  "54": { text: "Falls der Preis des Artikels gezont ist", art: "voraussetzung" },
  "55": { text: "Wenn in dieser SG36 ein weiteres RNG (d. h. eine weitere Zone) vorhanden ist, in der der Wert des DE6162 (Wertebereichsgrenze, untere) größer ist als der Wert des DE6162 in diesem RNG", art: "voraussetzung" },
  "56": { text: "Wenn BGM DE1001 = Z94, dann muss der hier genannte Zeitpunkt ≥ 01.10. 2025 00:00 Uhr gesetzlicher deutscher Zeit sein", art: "voraussetzung" },
  "57": { text: "wenn BGM DE1001 = Z94", art: "voraussetzung" },
  "58": { text: "Der Teil des Codes vor dem \"-\" muss mit einem der Codes aus der EDI@Energy Codeliste", art: "voraussetzung" },
  "59": { text: "Der Teil des Codes vor dem \"-\" muss mit einem der Codes aus der EDI@Energy Codeliste der Konfigurationen übereinstimen, die im Kapitel Produkte zur Bestellung einer Änderung an einer Lokation in der Sparte Strom genannt sind", art: "voraussetzung" },
  "60": { text: "Wenn in dieser SG36 der Teil vor dem \"-\" aus LIN DE7140 aus der Tabelle des Kapitels \"Produkte zur Bestellung einer Änderung an einer Lokation in der Sparte Strom\" der EDI@Energy Codeliste der Konfigurationen", art: "voraussetzung" },
  "61": { text: "Wenn in dieser SG36 der Wert der Zahl nach dem - aus LIN DE7140 >01", art: "voraussetzung" },
  "62": { text: "Wenn IMD+F vorhanden", art: "voraussetzung", check: {"tag": "IMD", "qual": "F", "neg": false} },
  "63": { text: "Wenn vorheriges DE7008 zur Beschreibung der Leistung dieser Artikel-ID nicht ausreicht", art: "voraussetzung" },
  "65": { text: "Text im AHB nicht gefunden (bitte prüfen).", art: "voraussetzung" },
  "66": { text: "Text im AHB nicht gefunden (bitte prüfen).", art: "voraussetzung" },
  "67": { text: "Text im AHB nicht gefunden (bitte prüfen).", art: "voraussetzung" },
  "72": { text: "Text im AHB nicht gefunden (bitte prüfen).", art: "voraussetzung" },
  "492": { text: "ohne gemeindespezifische Konzessionsabgaben Z67 Preisblatt Blindarbeit X", art: "voraussetzung" },
  "494": { text: "Das hier genannte Datum muss der Zeitpunkt sein, zu dem das Dokument erstellt wurde, oder ein Zeitpunkt, der davor liegt", art: "voraussetzung" },
  "495": { text: "Der Zeitpunkt muss ≤ dem Wert im DE2380 des DTM+137 sein", art: "voraussetzung" },
  "502": { text: "Hinweis: Preis in Euro je MWh", art: "hinweis" },
  "503": { text: "Hinweis: Hier ist immer der Wert 1000 einzutragen, da in DE5118 der Preis in €/MWh angegeben wird.", art: "hinweis" },
  "504": { text: "Hinweis: Dokumentennummer der PRICAT", art: "hinweis" },
  "511": { text: "Hinweis: 1. Der genannte Wert gehört nicht zum Intervall. 2. Wenn in dieser SG36 die letzte Ziffer von LIN DE7140 >1, dann ist der Wert identisch mit dem Wert des DE6152 im RNG-Segment, in der SG36, in der die letzte Ziffer von LIN DE7140 um 1 kleiner ist, als die letzte Ziffer von LIN DE7140 in dieser SG36. 3. Die untere Wertegrenze zu der Artikel-ID, deren Zahl an der letzten Stelle den Wert n hat, muss kleiner sein, als die untere Wertegrenze zu der Artikel-ID, deren Zahl an der letzten Stelle den Wert n+1 hat.", art: "hinweis" },
  "512": { text: "Hinweis: Der genannte Wert gehört zum Intervall", art: "hinweis" },
  "513": { text: "Hinweis: Die zum Preis gehörende Einheit ist in der Codeliste definiert", art: "hinweis" },
  "519": { text: "Hinweis: Es darf nur eine Information im DE3148 übermittelt werden", art: "hinweis" },
  "520": { text: "Hinweis: Falls der Preis des Artikels gezont ist, ist diese SG40 so oft zu wiederholen, bis alle Preise zu diesem Artikel genannt sind", art: "hinweis" },
  "521": { text: "Hinweis: Je Artikel-ID muss in einem RNG der Wert dieses DE = 0 sein und in allen anderen RNG zu dieser Artikel-ID muss der Wert dieses DE mit dem Wert des DE6152 eines anderen RNG zu dieser Artikel-ID identisch sein", art: "hinweis" },
  "522": { text: "Hinweis: Hier ist die Leistung zu beschreiben, die mit dieser Artikel-ID in Rechnung gestellt wird, wobei darauf zu achten ist, dass zu erkennen ist, wie sich diese von den Leistungen unterscheiden, bei denen die ersten 13 Stellen der Artikel-ID mit den ersten 13 Stellen dieser Artikel-ID identisch sind", art: "hinweis" },
  "902": { text: "Format: Möglicher Wert: ≥ 0", art: "format" },
  "908": { text: "Format: Mögliche Werte: 1 bis n", art: "format" },
  "909": { text: "Format: Mögliche Werte: 0 bis n", art: "format" },
  "911": { text: "Format: Mögliche Werte: 1 bis n, je Nachricht oder Segmentgruppe bei 1 beginnend und fortlaufend aufsteigend", art: "format" },
  "912": { text: "Format: max. 6 Nachkommastellen", art: "format" },
  "926": { text: "Format: Möglicher Wert: 0", art: "format" },
  "929": { text: "Format: Möglicher Wert: 1000", art: "format" },
  "931": { text: "Format: ZZZ = +00", art: "format" },
  "937": { text: "Format: keine Nachkommastelle", art: "format" },
  "939": { text: "Format: Die Zeichenkette muss die Zeichen @ und . enthalten", art: "format" },
  "940": { text: "Format: Die Zeichenkette muss mit dem Zeichen + beginnen und danach dürfen nur noch Ziffern folgen", art: "format" },
  "941": { text: "Format: Artikelnummer", art: "format" },
  "942": { text: "Format: n1-n2-n1-n3", art: "format" },
  "946": { text: "Format: max. 11 Nachkommastellen", art: "format" },
  "948": { text: "Format: n1-n2-n1-n8-n2", art: "format" },
  "949": { text: "Format: n1-n2-n1-n8-n2-n1", art: "format" },
  "957": { text: "Format: n1-n2-n1-n8", art: "format" },
  "959": { text: "Format: n13-n2", art: "format" },
  "968": { text: "Format: Möglicher Wert: ≤ 0", art: "format" },
};
if (typeof window!=='undefined') window.EdiBedingungen = Object.assign(window.EdiBedingungen||{}, pricatBedingungen);
if (typeof module!=='undefined') module.exports = pricatBedingungen;

// --- Nachtrag 28.07.2026 -------------------------------------------------
// Diese Bedingungen werden in den Formularen referenziert, fehlten aber in der
// Bedingungsdatei; die Texte stammen aus der AHB-Extraktion desselben Stands.
if (typeof window !== 'undefined') {
    window.EdiBedingungen = window.EdiBedingungen || {};
    var _nachtrag = {
        "64": { text: "Wenn der Zeitpunkt im DTM+157 DE2380 ≥ 01.01.2026, 00:00 Uhr gesetzlicher deutscher Zeit", art: "voraussetzung" },
        "68": { text: "Der Teil des Codes vor dem \"-\" muss ein Messprodukt-Code sein", art: "voraussetzung" },
        "69": { text: "Der Teil des Codes vor dem \"-\" muss ein Konfigurationsprodukt-Code sein", art: "voraussetzung" },
        "70": { text: "Der Teil des Codes vor dem \"-\" muss ein Produkt-Code sein", art: "voraussetzung" },
        "71": { text: "Es muss der Code 9991000003030-01 sein", art: "voraussetzung" },
    };
    Object.keys(_nachtrag).forEach(function (nr) {
        if (!window.EdiBedingungen[nr]) window.EdiBedingungen[nr] = _nachtrag[nr];
    });
}
