// _bedingungen.js (UTILTS) - AHB-Bedingungen via kohlrahbi-Parser (an unser docx-Layout adaptiert).
// parse_conditions_from_string (kohlrahbi/Hochfrequenz), Quelle AHB_UTILTS_1.0_20250606_20260930_20250606_ooox_11112.docx.
var utiltsBedingungen = {
  "1": { text: "Nur MP-ID aus Sparte Strom", art: "voraussetzung" },
  "2": { text: "Wenn SG5 STS+Z23+Z34 (Berechnungsformel muss beim Absender angefragt werden) in einem SG5 IDE vorhanden", art: "voraussetzung" },
  "3": { text: "SEQ Energiemenge der Marktlokation Muss DE1229: Z36 Energiemenge der Marktlokation X", art: "voraussetzung" },
  "4": { text: "DE4451 ACB X DE4441Zeitraum-ID aus der Übermittlung der Berechnungsformel X DE4440 X", art: "voraussetzung" },
  "5": { text: "Wenn das SG8 RFF+Z19 (Referenz auf eine Messlokation) in derselben SG8 SEQ+Z37 nicht vorhanden", art: "voraussetzung" },
  "6": { text: "Wenn das SG8 RFF+Z23 (Referenz auf Rechenschritt) in derselben SG8 SEQ+Z37 und der selben Zeitraum-ID nicht vorhanden", art: "voraussetzung" },
  "7": { text: "Wenn in derselben SG8 SEQ+Z37 das SG8 RFF+Z19 (Referenz auf eine Messlokation) vorhanden", art: "voraussetzung" },
  "8": { text: "Rechenschrittidentifikator aus einem SG8 SEQ+Z37 (Bestandteil des Rechenschritts) DE1050 desselben SG5 IDE+24 und derselben Zeitraum-ID wie bei diesem SG8", art: "voraussetzung" },
  "9": { text: "Der hier angegebene Rechenschrittidentifikator darf nicht identisch mit dem Rechenschrittidentifikator aus diesem SG8 SEQ+Z37 DE1050 sein", art: "voraussetzung" },
  "10": { text: "wenn vorhanden", art: "voraussetzung" },
  "11": { text: "Wenn in SG8 SEQ+Z37 SG9 CCI+++Z86 CAV+Z69/Z70 (Addition / Subtraktion) vorhanden, darf es in dem Vorgang beliebig viele weitere SG8 SEQ+Z37 mit identischem Rechenschrittidentifikator mit derselben Zeitraum-ID geben, die jedoch ausschließlich die Operatoren Z69/Z70 enthalten dürfen", art: "voraussetzung" },
  "12": { text: "Wenn in SG8 SEQ+Z37 SG9 CCI+++Z86 CAV+Z83 (Positivwert) vorhanden, darf es in dem Vorgang keine weitere SG8 SEQ+Z37 mit identischem Rechenschrittidentifikator und derselben Zeitraum-ID geben", art: "voraussetzung" },
  "13": { text: "Wenn in SG8 SEQ+Z37 SG9 CCI+++Z86 CAV+Z80/Z81 (Divisor / Dividend) vorhanden, muss in diesem Vorgang genau eine zweite SG8 SEQ+Z37 mit identischen Rechenschrittidentifikator und derselben Zeitraum-ID vorhanden sein, sodass das eine SG8 SEQ+Z37 den Operator Z80 (Divisor) und das andere SG8 SEQ+Z37 den Operator Z81 (Dividend) enthält", art: "voraussetzung" },
  "14": { text: "Wenn in SG8 SEQ+Z37 SG9 CCI+++Z86 CAV+Z82 (Faktor) vorhanden, darf es in dem Vorgang beliebig viele weitere SG8 SEQ+Z37 mit identischem Rechenschrittidentifikator und derselben Zeitraum-ID geben, die jedoch ausschließlich CAV+Z82 enthalten", art: "voraussetzung" },
  "15": { text: "Wenn in einem SG5 IDE+24 nur eine SEQ+Z37 mit einer SG8 RFF+Z19 (Messlokation) und der selben Zeitraum-ID vorhanden ist", art: "voraussetzung" },
  "18": { text: "Wenn MP-ID in SG2 NAD+MR (Nachrichtenempfänger) in der Rolle LF", art: "voraussetzung" },
  "21": { text: "Wenn in dieser CAV+ZD3 der Wert im DE7110 mit Z32 (sonstiger Zählzeitdefinitionstyp) vorhanden ist", art: "voraussetzung" },
  "22": { text: "Wenn MP-ID in SG2 NAD+MS (Nachrichtenabsender) in der Rolle NB", art: "voraussetzung" },
  "24": { text: "Wenn SG5 STS+Z36+Z45 (Definitionen werden verwendet) vorhanden", art: "voraussetzung" },
  "25": { text: "Wenn MP-ID in SG2 NAD+MR (Nachrichtenempfänger) in der Rolle LF", art: "voraussetzung" },
  "26": { text: "sofern per ORDERS reklamiert", art: "voraussetzung" },
  "27": { text: "Wenn in SG9 CAV+ZD4+Z26 (keine Verwendung des Hochlastzeitfensters) vorhanden", art: "voraussetzung" },
  "29": { text: "Wenn in SG8 SEQ+Z43 DTM+Z33 (Zählzeitänderungszeitpu nkt) im DE2379 der Code 303 vorhanden", art: "voraussetzung" },
  "30": { text: "Der Wert von CCYY", art: "voraussetzung" },
  "31": { text: "Wenn im DE2379 dieses Segments der Code 303 vorhanden", art: "voraussetzung" },
  "32": { text: "Der Zeitpunkt in diesem DE muss ≥ dem Zeitpunkt aus dem DE2380 des Gültigkeitsbeginn der ausgerollten Definition (SG5 DTM+Z34) sein", art: "voraussetzung" },
  "33": { text: "Der Zeitpunkt in diesem DE muss ≤ dem Zeitpunkt aus dem DE2380 des Gültigkeitsende der ausgerollten Definition (SG5 DTM+Z35) sein", art: "voraussetzung" },
  "34": { text: "Wenn im DE2379 dieses Segments der Code 401 vorhanden", art: "voraussetzung" },
  "36": { text: "Wenn in SG8 SEQ+Z43 DTM+Z33 (Zählzeitänderungszeitpu nkt) im DE2379 der Code 401 vorhanden", art: "voraussetzung" },
  "37": { text: "\" für SG5 DTM Gültigkeitsende der ausgerollten Definition und wurde entfernt. Zusätzlich wurde die Präzisierung eingeführt, dass alle Codes in diesem DTM-Segment innerhalb eines Vorgangs (IDE+24) den gleichen Code im DE2379 besitzen müssen.", art: "voraussetzung" },
  "38": { text: "Wenn SG5 DTM+Z35 (Gültigkeitsende der ausgerollten Definition) vorhanden", art: "voraussetzung" },
  "39": { text: "Wenn SG5 DTM+Z35 (Gültigkeitsende der ausgerollten Definition) nicht vorhanden", art: "voraussetzung" },
  "41": { text: "Wenn SG8 SEQ+Z42 (Zählzeitdefinition) vorhanden", art: "voraussetzung" },
  "42": { text: "Der in diesem Datenlement angegebene Code der Schaltzeitdefinition muss innerhalb eines Vorgangs (IDE) eindeutig sein.", art: "voraussetzung" },
  "43": { text: "Der in diesem Datenlement angegebene Code der Leistungskurvendefinitio n muss innerhalb eines Vorgangs (IDE) eindeutig sein.", art: "voraussetzung" },
  "44": { text: "Der in diesem Datenlement angegebene Code der Zählzeitdefinition muss innerhalb eines Vorgangs (IDE) eindeutig sein.", art: "voraussetzung" },
  "46": { text: "Wenn in SG8 SEQ+Z73 DTM+Z44 (Schaltzeitänderungszeit punkt) im DE2379 der Code 303 vorhanden", art: "voraussetzung" },
  "47": { text: "war der Name des DTM+Z44 Segments als Zählzeitänderungszeitpunkt angegeben, korrekterweise lautet der Name Schaltzeitänderungszeitpunkt. Dieser Fehler wurde behoben.", art: "voraussetzung" },
  "48": { text: "Wenn in SG8 SEQ+Z74 DTM+Z45 (Leistungskurvenänderun gszeitpunkt) im DE2379 der Code 303 vorhanden", art: "voraussetzung" },
  "49": { text: "Wenn in SG8 SEQ+Z74 DTM+Z45 (Leistungskurvenänderun gszeitpunkt) im DE2379 der Code 401 vorhanden", art: "voraussetzung" },
  "50": { text: "In jedem DE2379 dieses DTM-Segments innerhalb eines IDE+24 (Vorgangs) muss der gleiche Code angegeben werden", art: "voraussetzung" },
  "51": { text: "CCI Muss DE7059 Z30 X DE7037 Z06 X", art: "voraussetzung" },
  "53": { text: "Wenn im DE3155 in demselben COM der Code EM vorhanden ist", art: "voraussetzung" },
  "54": { text: "Wenn im DE3155 in demselben COM der Code TE / FX / AJ / AL vorhanden ist", art: "voraussetzung" },
  "55": { text: "Es ist der Wert", art: "voraussetzung" },
  "56": { text: "Wenn dieses DTM+Z25 (Verwendung der Daten ab) im SG6 RFF (Verwendungszeitraum der Daten) mit der Zeitraum ID \"1\" im DE1156 ist, muss das Datum der darauffolgende oder ein älterer Tag 0:00 Uhr deutscher Zeit vom DTM+137 DE2380 (Nachrichtendatum) entsprechen", art: "voraussetzung" },
  "57": { text: "Wenn dieses DTM+Z25 (Verwendung der Daten ab) nicht im SG6 RFF+Z49/ Z53 (Verwendungszeitraum der Daten: Gültige Daten/ Keine Daten) mit der Zeitraum ID \"1\" im DE1156 ist, muss das Datum dem DTM+Z26 (Verwendung der Daten bis) des SG6 RFF+Z49/ Z53 (Verwendungszeitraum der Daten: Gültige Daten/ Keine Daten) mit der nächst niedrigeren Zeitraum ID im DE1156 entsprechen", art: "voraussetzung" },
  "58": { text: "Wenn im selben SG6 RFF+Z49/ Z53 (Verwendungszeitraum der Daten: Gültige Daten/ Keine Daten) im DE1156 (Zeitraum-", art: "voraussetzung" },
  "59": { text: "Es ist die Zeitraum-ID vom DE1156 aus einem passenden SG6 RFF+Z49 (Verwendungszeitraum der Daten) einzutragen", art: "voraussetzung" },
  "61": { text: "Wenn in einem STS+E01 im DE9013 (Status der Antwort) ein Antwortcode aus dem Cluster Ablehnung", art: "voraussetzung" },
  "62": { text: "Wenn MP-ID in SG2 NAD+MR (Nachrichtenempfänger) in der Rolle MSB", art: "voraussetzung" },
  "494": { text: "Das hier genannte Datum muss der Zeitpunkt sein, zu dem das Dokument erstellt wurde, oder ein Zeitpunkt, der davor liegt.", art: "voraussetzung" },
  "501": { text: "Hinweis: Verwendung der ID der Marktlokation", art: "hinweis" },
  "502": { text: "Hinweis: Verwendung der ID der Messlokation", art: "hinweis" },
  "504": { text: "Hinweis: Wert aus BGM+Z55 DE1004 der ORDERS mit der die Reklamation einer Definition erfolgt ist", art: "hinweis" },
  "505": { text: "Hinweis: Jede ausgerollte Zählzeitdefinition ist in einem eigenen IDE anzugeben", art: "hinweis" },
  "506": { text: "Hinweis: Zeitpunkt, ab dem die Übersicht der Zählzeitdefinitionen gültig ist", art: "hinweis" },
  "507": { text: "Hinweis: Es ist die Zeit nach der deutschen gesetzlichen Zeit anzugeben", art: "hinweis" },
  "508": { text: "Hinweis: Zeitpunkt, ab dem die Übersicht der Schaltzeitdefinitionen gültig ist", art: "hinweis" },
  "509": { text: "Hinweis: Zeitpunkt, ab dem die Übersicht der Leistungskurvendefinitio n gültig ist", art: "hinweis" },
  "510": { text: "Hinweis: Für jeden Zählzeitänderungszeitpu nkt (SG8 DTM+Z33) ist diese Sementgruppe einmal anzugeben", art: "hinweis" },
  "511": { text: "Hinweis: Der Zählzeitänderungszeitpu nkt (SG8DTM+Z33) dieser SG8 darf in keiner anderen SG8 „Zählzeitdefinition“ wiederholt werden", art: "hinweis" },
  "512": { text: "Hinweis: Wenn der Code 303 im DE2379 des Zählzeitänderungszeitpu nkt (SG8 DTM+Z33) genutzt wird, muss genau ein Wert im DE2380 des Zählzeitänderungszeitpu nkt (SG8 DTM+Z33) identisch mit dem Wert aus DE2380 des Gültigkeitsbeginn der ausgerollten Definition (SG5 DTM+Z34) sein", art: "hinweis" },
  "513": { text: "Hinweis: Wenn der Code 401 im DE2379 des Zählzeitänderungszeitpu nkt (SG8 DTM+Z33) genutzt wird, muss genau ein Wert = 0000 im DE2380 des Zählzeitänderungszeitpu nkt (SG8 DTM+Z33) sein", art: "hinweis" },
  "514": { text: "Hinweis: Für jeden Schaltzeitänderungszeitp unkt (SG8 DTM+Z44) ist diese Sementgruppe einmal anzugeben", art: "hinweis" },
  "515": { text: "Hinweis: Kein Schaltzeitänderungszeitp unkt (SG8 DTM+Z44) darf mehrfach vorkommen", art: "hinweis" },
  "516": { text: "Hinweis: Wenn der Code 303 im DE2379 des Schaltzeitänderungszeitp unkt (SG8 DTM+Z44) genutzt wird, muss genau ein Wert im DE2380 des Schaltzeitänderungszeitp unkt (SG8 DTM+Z44) identisch mit dem Wert aus DE2380 des Gültigkeitsbeginn der ausgerollten Definition (SG5 DTM+Z34) sein", art: "hinweis" },
  "517": { text: "Hinweis: Wenn der Code 401 im DE2379 des Schaltzeitänderungszeitp unkt (SG8 DTM+Z44) genutzt wird, muss genau ein Wert = 0000 im DE2380 des Schaltzeitänderungszeitp unkt (SG8 DTM+Z44) sein", art: "hinweis" },
  "518": { text: "Hinweis: Für jeden Leistungskurvenänderun gszeitpunkt (SG8 DTM+Z45) ist diese Sementgruppe einmal anzugeben", art: "hinweis" },
  "519": { text: "Hinweis: Kein Leistungskurvenänderun gszeitpunkt (SG8 DTM+Z45) darf mehrfach vorkommen", art: "hinweis" },
  "520": { text: "Hinweis: Wenn der Code 303 im DE2379 des Leistungskurvenänderun gszeitpunkt (SG8 DTM+Z45) genutzt wird, muss genau ein Wert im DE2380 des Leistungskurvenänderun gszeitpunkt (SG8 DTM+Z45) identisch mit dem Wert aus DE2380 des Gültigkeitsbeginn der ausgerollten Definition (SG5 DTM+Z34) sein", art: "hinweis" },
  "521": { text: "Hinweis: Wenn der Code 401 im DE2379 des Leistungskurvenänderun gszeitpunkt (SG8 DTM+Z45)", art: "hinweis" },
  "522": { text: "Hinweis: Jede ausgerollte Schaltzeitdefinition ist in einem eigenen IDE anzugeben", art: "hinweis" },
  "523": { text: "Hinweis: Jede ausgerollte Leistungskurvendefinitio n ist in einem eigenen IDE anzugeben", art: "hinweis" },
  "524": { text: "Hinweis: Es ist der Code einer Zählzeitdefinition anzugeben", art: "hinweis" },
  "525": { text: "Hinweis: Es ist der Code einer Schaltzeitdefinition anzugeben", art: "hinweis" },
  "526": { text: "Hinweis: Es ist der Code einer Leistungskurvendefinitio n anzugeben", art: "hinweis" },
  "527": { text: "Hinweis: Dieser Code ist anzugeben, wenn es sich um eine einmalig zu übermittelnde Definition handelt", art: "hinweis" },
  "528": { text: "Hinweis: Dieser Code ist anzugeben, wenn es sich um eine jährlich zu übermittelnde Definition handelt", art: "hinweis" },
  "529": { text: "Hinweis: Verwendung der ID der Netzlokation", art: "hinweis" },
  "530": { text: "Hinweis: Es darf nur eine Information im DE3148 übermittelt werden", art: "hinweis" },
  "531": { text: "Hinweis: für weitere Details siehe Kapitel 4.1 \"Übermittlung einer Vielzahl von Berechnungsformeln in einem Vorgang\"", art: "hinweis" },
  "532": { text: "Hinweis: Es ist die Zeitraum-ID vom DE1156 aus einem passenden SG6 RFF+Z49/Z53 (Verwendungszeitraum der Daten: \"Gültige Daten\", \"Keine Daten\") aus der Übermittlung der Berechnungsformel aus SG6 RFF+TN DE1154 (Referenz Vorgangsnummer (aus Berechnungsformel)) einzutragen", art: "hinweis" },
  "533": { text: "Hinweis: Für jeden übermittelten Zeitraum aus der Übermittlung der Berechnungsformel ist genau einmal das Segement anzugeben", art: "hinweis" },
  "534": { text: "Hinweis: Wert aus SG5 IDE+24 DE7402 mit der die Übermitt-lung der Berechnungsformel erfolgt ist.", art: "hinweis" },
  "912": { text: "Format: Wert kann mit maximal 6 Nachkommastellen angegeben werden", art: "format" },
  "913": { text: "Format: Mögliche Werte: 1 bis 99999", art: "format" },
  "914": { text: "Format: Möglicher Wert: > 0", art: "format" },
  "915": { text: "Format: Möglicher Wert: ≠ 1", art: "format" },
  "930": { text: "Format: max. 2 Nachkommastellen", art: "format" },
  "931": { text: "Format: ZZZ = +00", art: "format" },
  "937": { text: "Format: keine Nachkommastelle", art: "format" },
  "939": { text: "Format: Die Zeichenkette muss die Zeichen @ und . enthalten", art: "format" },
  "940": { text: "Format: Die Zeichenkette muss mit dem Zeichen + beginnen und danach dürfen nur noch Ziffern folgen", art: "format" },
  "947": { text: "Format: MMDDHHMM = 12312300", art: "format" },
  "950": { text: "Format: Marktlokations-ID", art: "format" },
  "951": { text: "Format: Zählpunktbezeichnung", art: "format" },
  "960": { text: "Format: Netzlokations- ID", art: "format" },
  "963": { text: "Format: Möglicher Wert: ≤ 100", art: "format" },
  "964": { text: "Format: HHMM ≥ 0000", art: "format" },
  "965": { text: "Format: HHMM ≤ 2359", art: "format" },
  "969": { text: "Format: Möglicher Wer: ≤ 1", art: "format" },
  "2001": { text: "Segment bzw. Segmentgruppe ist genau einmal anzugeben", art: "wiederholbarkeit" },
  "2002": { text: "Für jeden Code der Zählzeit aus SG8 SEQ+Z42 (Zählzeitdefinition) SG9 CCI+Z39 (Code der Zählzeitdefinition) sind mindestens zwei Register anzugeben, bei denen in dieser SG8 das SG8 RFF+Z27 mit diesem Code gefüllt ist", art: "wiederholbarkeit" },
  "2003": { text: "Segmentgruppe ist genau einmal für jede Zeitraum-ID aus dem DE1156 der SG6 RFF+Z49 (Verwendungszeitraum der Daten: \"Gültige Daten\") anzugeben", art: "wiederholbarkeit" },
  "2004": { text: "Segment ist genau einmal für jede Zeitraum-ID aus dem DE1156 der SG6 RFF+Z49 (Verwendungszeitraum der Daten: \"Gültige Daten\") anzugeben", art: "wiederholbarkeit" },
  "2005": { text: "Segment ist genau einmal für jede Zeitraum-ID aus dem DE9012 der SG5 STS+E01 (\"Status der Antwort\") anzugeben, wenn im selben SG5 STS+E01 im DE9013 der Code A99 (\"Sontiges\") enthalten ist", art: "wiederholbarkeit" },
  "2006": { text: "Segmentgruppe ist mindestens einmal für jede Zeitraum-ID aus dem DE9013 der SG5 STS+Z23+Z33 (Berechnungsformel angefügt) anzugeben", art: "wiederholbarkeit" },
};
if (typeof window!=='undefined') window.EdiBedingungen = Object.assign(window.EdiBedingungen||{}, utiltsBedingungen);
if (typeof module!=='undefined') module.exports = utiltsBedingungen;

// --- Nachtrag 28.07.2026 -------------------------------------------------
// Diese Bedingungen werden in den Formularen referenziert, fehlten aber in der
// Bedingungsdatei; die Texte stammen aus der AHB-Extraktion desselben Stands.
if (typeof window !== 'undefined') {
    window.EdiBedingungen = window.EdiBedingungen || {};
    var _nachtrag = {
        "2007": { text: "Segmentgruppe ist genau einmal für jede Zeitraum-ID aus dem DE9013 der SG5 STS+Z23+Z33 (Berechnungsformel angefügt) anzugeben", art: "wiederholbarkeit" },
    };
    Object.keys(_nachtrag).forEach(function (nr) {
        if (!window.EdiBedingungen[nr]) window.EdiBedingungen[nr] = _nachtrag[nr];
    });
}
