// _bedingungen.js (INVOIC) - AHB-Bedingungen, extrahiert mit kohlrahbi (Hochfrequenz).
// Offizieller conditions-Scraper, Quelle FV2604.
var invoicBedingungen = {
  "1": { text: "Wenn in zu stornierender Rechnung gefüllt", art: "voraussetzung" },
  "2": { text: "Wenn es sich um eine Nutzungsüberlassung (Pacht) eines Gerätes handelt", art: "voraussetzung" },
  "3": { text: "Wenn es sich um einen Kauf eines Gerätes handelt", art: "voraussetzung" },
  "4": { text: "Wenn Steuerschuldnerschaft des Leistungsempfängers vorliegt", art: "voraussetzung" },
  "5": { text: "Wenn NAD+MR DE3207 <> „DE“", art: "voraussetzung" },
  "6": { text: "Wenn NAD+MR DE3207 = „DE“", art: "voraussetzung" },
  "7": { text: "Sofern keine Großkundenpostleitza hl verwendet wird", art: "voraussetzung" },
  "8": { text: "Bei zeitabhängigen Preisen", art: "voraussetzung" },
  "9": { text: "Wenn SG26 DTM+203 nicht vorhanden", art: "voraussetzung", check: {"tag": "DTM", "qual": "203", "neg": true} },
  "10": { text: "Wenn SG26 DTM+155/156 nicht vorhanden", art: "voraussetzung" },
  "11": { text: "Wenn Abschlag anfällt", art: "voraussetzung" },
  "12": { text: "Wenn SG26 QTY+136 vorhanden", art: "voraussetzung", check: {"tag": "QTY", "qual": "136", "neg": false} },
  "13": { text: "Wenn vorausbezahlter Betrag vorliegt", art: "voraussetzung" },
  "14": { text: "Wenn in selben SG26 LIN DE7140 =\"9990001000748\" (Mehrmenge)", art: "voraussetzung" },
  "15": { text: "Wenn eine Bilanzierung erfolgt ist", art: "voraussetzung" },
  "16": { text: "Wenn eine Netznutzung erfolgt ist", art: "voraussetzung" },
  "17": { text: "Wenn DTM+Z11 vorhanden", art: "voraussetzung", check: {"tag": "DTM", "qual": "Z11", "neg": false} },
  "18": { text: "Wenn IMD++WIM nicht vorhanden", art: "voraussetzung", check: {"tag": "IMD", "qual": "WIM", "neg": true} },
  "19": { text: "Wenn IMD++WIM vorhanden", art: "voraussetzung", check: {"tag": "IMD", "qual": "WIM", "neg": false} },
  "20": { text: "Wenn fälliger Betrag (SG50 MOA+9) ≥ 0", art: "voraussetzung" },
  "21": { text: "Wenn fälliger Betrag (SG50 MOA+9) < 0", art: "voraussetzung" },
  "22": { text: "Wenn vorhanden", art: "voraussetzung" },
  "23": { text: "Wenn im selben NAD DE3124 nicht vorhanden", art: "voraussetzung" },
  "24": { text: "Wert muss mindestens 10 WT nach Wert aus DTM+137 DE2380 liegen", art: "voraussetzung" },
  "25": { text: "Wert darf maximal 10 WT nach Wert aus DTM+137 DE2380 liegen", art: "voraussetzung" },
  "26": { text: "Wenn SG39 ALC+A+:Z04 vorhanden", art: "voraussetzung" },
  "27": { text: "Wenn SG39 ALC+C vorhanden", art: "voraussetzung", check: {"tag": "ALC", "qual": "C", "neg": false} },
  "28": { text: "Wenn Zuschlag anfällt", art: "voraussetzung" },
  "29": { text: "[Wenn DTM+155 (Abrechnungszeitraum Beginn) nicht größer 31.12.2015", art: "voraussetzung" },
  "30": { text: "Wenn MP-ID in NAD+MR nicht in der Rolle MGV oder KN", art: "voraussetzung" },
  "31": { text: "Wenn MP-ID in NAD+MR in der Rolle MGV", art: "voraussetzung" },
  "32": { text: "Wenn SG39 ALC+A+:Z01 (Gemeinderabatt) vorhanden", art: "voraussetzung" },
  "34": { text: "Wenn in Ursprungsrechnung vorhanden", art: "voraussetzung" },
  "36": { text: "Wenn DTM+156 (Abrechnungszeitraum Ende) ≥ 01.12.2019", art: "voraussetzung" },
  "37": { text: "Wenn Lieferschein zuvor ausgetauscht wurde", art: "voraussetzung" },
  "40": { text: "Es sind nur die Artikelnummern erlaubt, die in der Codeliste der Artikelnummern und Artikel-ID mit dem entsprechenden Prüfidentifikator versehen sind oder Artikel-ID aus der Codeliste der Artikelnummern und Artikel-ID.", art: "voraussetzung" },
  "41": { text: "Wenn IMD++SOR vorhanden", art: "voraussetzung", check: {"tag": "IMD", "qual": "SOR", "neg": false} },
  "42": { text: "Wenn DTM+155 (Abrechnungszeitraum Beginn) ≥ 1.1.2023 0: 00 gesetzlicher deutscher Zeit", art: "voraussetzung" },
  "44": { text: "Wenn IMD++ABS nicht vorhanden", art: "voraussetzung", check: {"tag": "IMD", "qual": "ABS", "neg": true} },
  "45": { text: "Nur MP-ID aus Sparte Strom", art: "voraussetzung" },
  "47": { text: "Wenn IMD++Z43 vorhanden", art: "voraussetzung", check: {"tag": "IMD", "qual": "Z43", "neg": false} },
  "48": { text: "Wenn IMD++Z44 vorhanden", art: "voraussetzung", check: {"tag": "IMD", "qual": "Z44", "neg": false} },
  "49": { text: "Wenn IMD++Z43 und IMD+Z44 nicht vorhanden", art: "voraussetzung" },
  "50": { text: "Wenn IMD++SOR nicht vorhanden", art: "voraussetzung", check: {"tag": "IMD", "qual": "SOR", "neg": true} },
  "51": { text: "Wenn SG26 DTM+156 (Positionsbezogener Abrechnungszeitraum Ende) ≤ 1.1.2023 0:00 gesetzlicher deutscher Zeit", art: "voraussetzung" },
  "53": { text: "Wenn IMD++Z45 vorhanden", art: "voraussetzung", check: {"tag": "IMD", "qual": "Z45", "neg": false} },
  "54": { text: "Wenn IMD++ABR/JVR/ZVR vorhanden", art: "voraussetzung" },
  "55": { text: "Wenn IMD++ABS vorhanden", art: "voraussetzung", check: {"tag": "IMD", "qual": "ABS", "neg": false} },
  "56": { text: "Wenn DTM+137 (Nachrichtendatum ≥ 1.1.2023 0: 00 gesetzlicher deutscher Zeit", art: "voraussetzung" },
  "57": { text: "Wenn DTM+156 (Abrechnungszeitraum Ende) ≤ 1. 1.2023 0:00 gesetzlicher deutscher Zeit", art: "voraussetzung" },
  "58": { text: "Wenn in dieser SG52 MOA+113 vorhanden", art: "voraussetzung" },
  "59": { text: "Wenn SG26 DTM+155 (Positionsbezogener Abrechnungszeitraum Beginn) ≥ 1.1.2023 0: 00 gesetzlicher deutscher Zeit", art: "voraussetzung" },
  "60": { text: "Wenn DTM+203 DE2379 in demselben Segment mit Wert 303 vorhanden", art: "voraussetzung" },
  "61": { text: "Wenn DTM+203 DE2379 in demselben Segment mit Wert 102 vorhanden", art: "voraussetzung" },
  "64": { text: "Wenn DTM+156 (Abrechnungszeitraum Ende) ≤ 1. 1.2024 0:00 gesetzlicher deutscher Zeit", art: "voraussetzung" },
  "65": { text: "Wenn SG26 DTM+155 (Positionsbezogener Abrechnungszeitraum Beginn) ≥ 1.1.2024 0: 00 gesetzlicher deutscher Zeit", art: "voraussetzung" },
  "66": { text: "Wenn IMD++KON vorhanden", art: "voraussetzung", check: {"tag": "IMD", "qual": "KON", "neg": false} },
  "67": { text: "Es sind nur die Artikelnummern erlaubt, die im Kapitel 2 „Codeliste der Artikelnummer“ in derCodeliste der Artikelnummern und Artikel-ID ein „X“ für den entsprechenden Prüfidentifikator haben.", art: "voraussetzung" },
  "68": { text: "Es sind nur die Artikel-ID erlaubt, die im Kapitel 3 „Codeliste der Gruppenartikel-ID und Artikel-ID“ in der Codeliste der Artikelnummern und Artikel-ID ein „X“ in der Spalte „INVOIC Codeverwendung“ haben.", art: "voraussetzung" },
  "69": { text: "Es sind nur die Artikel-ID erlaubt, die im Kapitel 3 „Codeliste der Gruppenartikel-ID und Artikel-ID“ in der Codeliste der Artikelnummern und Artikel-ID ein „SOR“ in der Spalte „INVOIC Codeverwendung“ haben.", art: "voraussetzung" },
  "70": { text: "Wenn IMD++Z45 nicht vorhanden", art: "voraussetzung", check: {"tag": "IMD", "qual": "Z45", "neg": true} },
  "71": { text: "Wenn DTM+155 (Abrechnungszeitraum Beginn) ≥ 1.1.2024 0:00 gesetzlicher deutscher Zeit", art: "voraussetzung" },
  "72": { text: "Wenn MP-ID in NAD+MR in der Rolle LF", art: "voraussetzung" },
  "73": { text: "Wenn IMD++MSB vorhanden", art: "voraussetzung", check: {"tag": "IMD", "qual": "MSB", "neg": false} },
  "74": { text: "wenn im DE3155 in demselben COM der Code EM vorhanden ist", art: "voraussetzung" },
  "75": { text: "wenn im DE3155 in demselben COM der Code TE / FX / AJ / AL vorhanden ist", art: "voraussetzung" },
  "76": { text: "Wenn MP-ID in NAD+MR in der Rolle NB", art: "voraussetzung" },
  "77": { text: "Wenn SG26 DTM+156 (Positionsbezogener Abrechnungszeitraum Ende) ≤ 1.1.2024 0:00 gesetzlicher deutscher Zeit", art: "voraussetzung" },
  "78": { text: "Wenn GEI+Z08 nicht vorhanden", art: "voraussetzung", check: {"tag": "GEI", "qual": "Z08", "neg": true} },
  "79": { text: "Wenn GEI+Z09 nicht vorhanden", art: "voraussetzung", check: {"tag": "GEI", "qual": "Z09", "neg": true} },
  "80": { text: "Wenn GEI+Z01 nicht vorhanden", art: "voraussetzung", check: {"tag": "GEI", "qual": "Z01", "neg": true} },
  "81": { text: "Wenn GEI+Z04 nicht vorhanden", art: "voraussetzung", check: {"tag": "GEI", "qual": "Z04", "neg": true} },
  "82": { text: "Wenn GEI+Z05 nicht vorhanden", art: "voraussetzung", check: {"tag": "GEI", "qual": "Z05", "neg": true} },
  "83": { text: "Wenn GEI+Z10 nicht vorhanden", art: "voraussetzung", check: {"tag": "GEI", "qual": "Z10", "neg": true} },
  "84": { text: "Wenn in dieser SG39 ALC+C+:Z02 / Z03 / Z04 vorhanden", art: "voraussetzung" },
  "85": { text: "Wenn in diesem Segment DE6411 = DAY", art: "voraussetzung" },
  "86": { text: "Wenn in diesem Segment DE6411 = MON/ANN", art: "voraussetzung" },
  "87": { text: "Wenn IMD++TEC vorhanden", art: "voraussetzung", check: {"tag": "IMD", "qual": "TEC", "neg": false} },
  "88": { text: "Wenn DTM+155 (Abrechnungszeitraum Beginn) ≥ 1.1.2026 0: 00 gesetzlicher deutscher Zeit", art: "voraussetzung" },
  "90": { text: "Text im AHB nicht gefunden (bitte prüfen).", art: "voraussetzung" },
  "490": { text: "wenn Wert in diesem DE, an der Stelle CCYYMMDDHHMM ein Zeitpunkt aus dem angegeben Zeitraum der Tabelle Kapitel 3.5 „Übersicht gesetzliche deutsche Sommerzeit (MESZ)“ der Spalten:\n›\t„Sommerzeit (MESZ) von“ Darstellung in UTC und\n›\t„Sommerzeit (MESZ) bis“ Darstellung in UTC ist.", art: "voraussetzung" },
  "491": { text: "wenn Wert in diesem DE, an der Stelle CCYYMMDDHHMM ein Zeitpunkt aus dem angegeben Zeitraum der Tabelle Kapitel 3.6 „Übersicht gesetzliche deutsche Zeit (MEZ)“ der Spalten: \n›\t„Winterzeit (MEZ) von“ Darstellung in UTC und\n›\t„Winterzeit (MEZ) bis“ Darstellung in UTC ist.", art: "voraussetzung" },
  "492": { text: "Wenn MP-ID in NAD+MR (Nachrichtenempfäng er) aus Sparte Strom", art: "voraussetzung" },
  "493": { text: "Wenn MP-ID in NAD+MR (Nachrichtenempfäng er) aus Sparte Gas", art: "voraussetzung" },
  "501": { text: "Hinweis: Dokumentennummer der ORDERS", art: "hinweis" },
  "502": { text: "Hinweis: Dokumentennummer der Bilanzierungs- MSCONS", art: "hinweis" },
  "503": { text: "Hinweis: Ein positiver Betrag ist eine Forderung des Rechnungsstellers.", art: "hinweis" },
  "504": { text: "Hinweis: Ein positiver Betrag ist eine Forderung des Rechnungsempfängers .", art: "hinweis" },
  "507": { text: "Hinweis: Dokumentennummer der SSQNOT", art: "hinweis" },
  "508": { text: "Hinweis: Dokumentennummer der QUOTES", art: "hinweis" },
  "509": { text: "Hinweis: Verwendung der ID der Marktlokation", art: "hinweis" },
  "510": { text: "Hinweis: Verwendung der ID der Messlokation", art: "hinweis" },
  "512": { text: "Hinweis: Hier ist entweder der Betrag aus MOA+203 oder der um den gültigen Steuerbetrag erhöhte Betrag aus MOA+203 anzugeben.", art: "hinweis" },
  "513": { text: "Hinweis: Hier ist das Ergebnis der Multiplikation von MOA+25 mit PCD+3 anzugeben.", art: "hinweis" },
  "514": { text: "Hinweis: Dokumentennummer der Lieferschein- MSCONS", art: "hinweis" },
  "515": { text: "Hinweis: BGM DE1004 aus INVOIC-Nachricht, die storniert werden soll", art: "hinweis" },
  "516": { text: "Hinweis: Ein Lieferschein zu einerRechnung ist für alle Abrechnungszeiträum e, die erstmals nach dem 1.12.2019 abgerechnet werden und für alle Abrechnungszeiträum e, für die sich nach dem 1.12.2019 geänderte Mengen oder Leistungswerte ergeben, nötig.", art: "hinweis" },
  "517": { text: "Hinweis: Dokumentennummer der PDF- Kapazitätsrechnung", art: "hinweis" },
  "518": { text: "Hinweis: Im Fall der Stornierung des Auftrags der Unterbrechung: Der Tag an dem der NB die Stornierung empfangen hat Bei erfolgreicher Sperrung: Tag der durchgeführten Sperrung Bei erfolgloser Sperrung: Letzter Sperrversuchstag", art: "hinweis" },
  "519": { text: "Hinweis: Stornierte Abschlagsrechnungen sind nicht aufzuführen", art: "hinweis" },
  "520": { text: "Hinweis: Es sind nur dieArtikel-IDs aus dem Preisblatt erlaubt", art: "hinweis" },
  "521": { text: "Hinweis: BGM DE1004 aus der INVOIC-Nachricht, für die Verzugskosten erhoben werden", art: "hinweis" },
  "522": { text: "Hinweis: Verwendung der ID der Netzlokation", art: "hinweis" },
  "523": { text: "Hinweis: Verwendung der ID der Steuerbaren Ressource", art: "hinweis" },
  "524": { text: "Hinweis: Es darf nur eine Information im DE3148 übermittelt werden", art: "hinweis" },
  "525": { text: "Hinweis: Verwendung, sofern Netzentgelte geringer als die Pauschale Netzentgeltreduzierun g", art: "hinweis" },
  "526": { text: "Hinweis: Der hier angegebene Geldbetrag muss mit dem identisch sein, der in SG50 MOA+77 im DE5004 der Abschlagsrechnung steht, die die Rechnungsnummer hat, die in dieser SG50 in SG51-RFF+AFL in DE1154 genannt ist.", art: "hinweis" },
  "527": { text: "Text im AHB nicht gefunden (bitte prüfen).", art: "hinweis" },
  "902": { text: "Format: Möglicher Wert: ≥ 0", art: "format" },
  "903": { text: "Text im AHB nicht gefunden (bitte prüfen).", art: "format" },
  "906": { text: "Format: max. 3 Nachkommastellen", art: "format" },
  "908": { text: "Format: Mögliche Werte: 1 bis n", art: "format" },
  "910": { text: "Format: Möglicher Wert: < 0 oder ≥ 0", art: "format" },
  "911": { text: "Format: Mögliche Werte: 1 bis n, je Nachricht oder Segmentgruppe bei 1 beginnend und fortlaufend aufsteigend", art: "format" },
  "912": { text: "Format: max. 6 Nachkommastellen", art: "format" },
  "914": { text: "Format: Möglicher Wert: > 0", art: "format" },
  "927": { text: "Format: Möglicher Wert: -1", art: "format" },
  "930": { text: "Format: max. 2 Nachkommastellen", art: "format" },
  "931": { text: "Format: ZZZ = +00", art: "format" },
  "932": { text: "Format: HHMM = 2200", art: "format" },
  "933": { text: "Format: HHMM = 2300", art: "format" },
  "934": { text: "Format: HHMM = 0400", art: "format" },
  "935": { text: "Format: HHMM = 0500", art: "format" },
  "937": { text: "Format: keine Nachkommastelle", art: "format" },
  "939": { text: "Format: Die Zeichenkette muss die Zeichen @ und . enthalten", art: "format" },
  "940": { text: "Format: Die Zeichenkette muss mit dem Zeichen + beginnen und danach dürfen nur noch Ziffern folgen", art: "format" },
  "946": { text: "Format: max. 11 Nachkommastellen", art: "format" },
  "950": { text: "Format: Marktlokations-ID", art: "format" },
  "951": { text: "Format: Zählpunktbezeichnung", art: "format" },
  "960": { text: "Format: Netzlokations-ID", art: "format" },
  "961": { text: "Format: SR-ID", art: "format" },
};
if (typeof window!=='undefined') window.EdiBedingungen = Object.assign(window.EdiBedingungen||{}, invoicBedingungen);
if (typeof module!=='undefined') module.exports = invoicBedingungen;

// --- Nachtrag 28.07.2026 -------------------------------------------------
// Diese Bedingungen werden in den Formularen referenziert, fehlten aber in der
// Bedingungsdatei; die Texte stammen aus der AHB-Extraktion desselben Stands.
if (typeof window !== 'undefined') {
    window.EdiBedingungen = window.EdiBedingungen || {};
    var _nachtrag = {
        "2000": { text: "Segmentgruppe ist genau einmal anzugeben.", art: "wiederholbarkeit" },
    };
    Object.keys(_nachtrag).forEach(function (nr) {
        if (!window.EdiBedingungen[nr]) window.EdiBedingungen[nr] = _nachtrag[nr];
    });
}
