// _bedingungen.js (MSCONS) - AHB-Bedingungen via kohlrahbi-Parser (an unser docx-Layout adaptiert).
// parse_conditions_from_string (kohlrahbi/Hochfrequenz), Quelle AHB_MSCONS_3.1g_20260401_20260930_20260401_ooox_11931.docx.
var msconsBedingungen = {
  "1": { text: "Sofern per ORDERS angefordert", art: "voraussetzung" },
  "2": { text: "Wenn das Zeitintervall zwischen ersten SG10 DTM+163 und letzten SG10 DTM+164 mindestens einen Monat umfasst", art: "voraussetzung" },
  "11": { text: "Wenn SG9 PIA+5+7-0?:52.0.22/7-0?:54.0.16/7-0?:54.0.20/7-0?:54.0.22", art: "voraussetzung" },
  "12": { text: "Wenn nicht SG9 PIA+5+7-0?:52.0.22/7-0?:54.0.16/7-0?:54.0.20/7-0?:54.0.22", art: "voraussetzung" },
  "17": { text: "Wenn nicht SG9 PIA+5+1-b?:9.99.0 (b= Kanal: Wert gemäß Codeliste der OBIS-Kennzahlen und Medien)", art: "voraussetzung" },
  "18": { text: "Wenn SG9 PIA+5+1-b?:9.99.0 (b= Kanal: Wert gemäß Codeliste der OBIS-Kennzahlen und Medien)", art: "voraussetzung" },
  "22": { text: "Wenn Aufteilung vorhanden", art: "voraussetzung" },
  "23": { text: "Wenn UNH DE0070 mit 1 vorhanden", art: "voraussetzung" },
  "24": { text: "Bei Aufteilung, in der Nachricht mit der höchsten Übermittlungsnummer", art: "voraussetzung" },
  "27": { text: "Wenn SG9 PIA+5+1-1?:1.9.0 vorhanden", art: "voraussetzung" },
  "28": { text: "Wenn SG9 PIA+5+1-1?:1.9.0 nicht vorhanden", art: "voraussetzung" },
  "32": { text: "wenn MP-ID in SG2 NAD+MS in der Rolle NB", art: "voraussetzung" },
  "33": { text: "wenn MP-ID in SG2 NAD+MR in der Rolle LF", art: "voraussetzung" },
  "35": { text: "wenn MP-ID in SG2 NAD+MS in der Rolle MSB", art: "voraussetzung" },
  "36": { text: "wenn MP-ID in SG2 NAD+MR in der Rolle NB", art: "voraussetzung" },
  "38": { text: "wenn in SG6 LOC+172 DE3225 die ID der Messlokation angegeben ist", art: "voraussetzung" },
  "42": { text: "Wenn MP-ID in SG2 NAD+MR in der Rolle MSB", art: "voraussetzung" },
  "45": { text: "Wenn SG9 PIA+5+7-b:99.41.16 (b=Kanal: Wert gemäß Codeliste der OBIS-Kennzahlen und Medien) vorhanden", art: "voraussetzung" },
  "46": { text: "Wenn Wert in SG6 LOC+172 DE3225 genau 11 Stellen", art: "voraussetzung" },
  "48": { text: "Wenn SG9 PIA+5+7-0?:52.0.22", art: "voraussetzung" },
  "49": { text: "Wenn SG9 PIA+5+7-b?:70.16.16/7-b?:70.16.20/7-b?:70.16.22 (b=Kanal: Wert gemäß Codeliste der OBIS-Kennzahlen und Medien) vorhanden", art: "voraussetzung" },
  "50": { text: "Wenn SG9 PIA+5+7-b?:70.18.16/7-b?:70.18.20/7-b?:70.18.22 (b=Kanal: Wert gemäß Codeliste der OBIS-Kennzahlen und Medien) vorhanden", art: "voraussetzung" },
  "51": { text: "Wenn SG9 PIA+5+7-0?:33.86.0 vorhanden ist, darf mittels Wiederholung SG9 LIN in derselben Nachricht das SG9 PIA+5+7-0?:52.0.22/7-0?:54.0.16/7-0?:54.0.20/7-0?:54.0.22 nicht mehr angegeben werden", art: "voraussetzung" },
  "62": { text: "Wenn Wert in SG6 LOC+172 DE3225 genau 33 Stellen", art: "voraussetzung" },
  "67": { text: "Wenn es sich um die Referenz auf eine ORDERS handelt", art: "voraussetzung" },
  "68": { text: "Wenn BGM+7 vorhanden", art: "voraussetzung", check: {"tag": "BGM", "qual": "7", "neg": false} },
  "69": { text: "Wenn BGM+Z28 vorhanden", art: "voraussetzung", check: {"tag": "BGM", "qual": "Z28", "neg": false} },
  "70": { text: "Wenn BGM+BK vorhanden", art: "voraussetzung", check: {"tag": "BGM", "qual": "BK", "neg": false} },
  "71": { text: "Wenn BGM+Z39 vorhanden", art: "voraussetzung", check: {"tag": "BGM", "qual": "Z39", "neg": false} },
  "72": { text: "Wenn SG9 PIA+5+1-b?:1.6.0/1-b?:3.6.0/1-b?:4.6.0/1-66?:13.6.0/1-66?:14.6.0 (b=Kanal: Wert gemäß Codeliste der OBIS-Kennzahlen und Medien) vorhanden", art: "voraussetzung" },
  "73": { text: "Wenn SG9 PIA+5+1-b?:1.9.e/1-b?:3.9.0/1-b?:4.9.0/1-66?:13.9.0/1-66?:14.9.0 (b=Kanal: Wert gemäß Codeliste der OBIS-Kennzahlen und Medien, e=Tarif: Wert gemäß Codeliste der OBIS-Kennzahlen und Medien) vorhanden", art: "voraussetzung" },
  "77": { text: "Wenn MP-ID in SG2 NAD+MR der RB HKN-R", art: "voraussetzung" },
  "78": { text: "Wenn SG9 PIA+5+1-66?:13.6.0/1-66?:14.6.0/1-66?:13.9.0/1-66?:14.9.0 vorhanden", art: "voraussetzung" },
  "79": { text: "Wenn SG9 PIA+5+1-66?:13.6.0/1-66?:14.6.0/1-66?:13.9.0/1-66?:14.9.0 nicht vorhanden", art: "voraussetzung" },
  "80": { text: "Wenn MP-ID in SG2 NAD+MR in der Rolle ÜNB", art: "voraussetzung" },
  "81": { text: "Wenn MP-ID in SG2 NAD+MS in der Rolle ÜNB", art: "voraussetzung" },
  "83": { text: "Wenn in derselben SG9 LIN die Angabe STS+10+Z38 nicht vorhanden", art: "voraussetzung" },
  "84": { text: "Wenn in derselben SG9 LIN die Angabe STS+10+Z39 nicht vorhanden", art: "voraussetzung" },
  "85": { text: "Wenn in derselben SG9 LIN die Angabe STS+10+Z36 nicht vorhanden", art: "voraussetzung" },
  "86": { text: "Wenn in derselben SG9 LIN die Angabe STS+10+Z37 nicht vorhanden", art: "voraussetzung" },
  "87": { text: "Wenn der Wert in DTM+163 DE2380 derselben SG6 LOC+172 mit demselben Wert in SG9 PIA+5 DE7140 der früheste angegebene Zeitpunkt ist", art: "voraussetzung" },
  "88": { text: "Wenn der Wert in DTM+164 DE2380 derselben SG6 LOC+172 mit demselben Wert in SG9 PIA+5 DE7140 der späteste angegebene Zeitpunkt ist", art: "voraussetzung" },
  "90": { text: "Wenn BGM+Z41 vorhanden", art: "voraussetzung", check: {"tag": "BGM", "qual": "Z41", "neg": false} },
  "91": { text: "Wenn BGM+Z42 vorhanden", art: "voraussetzung", check: {"tag": "BGM", "qual": "Z42", "neg": false} },
  "92": { text: "Wenn SG10 QTY DE6063 mit Wert 67 vorhanden", art: "voraussetzung" },
  "93": { text: "Wenn SG10 QTY DE6063 mit Wert 220 vorhanden", art: "voraussetzung" },
  "94": { text: "Wenn SG10 QTY DE6063 mit Wert 201 vorhanden", art: "voraussetzung" },
  "95": { text: "Wenn SG10 QTY DE6063 mit Wert 20 vorhanden", art: "voraussetzung" },
  "96": { text: "Wenn SG10 QTY DE6063 mit Wert Z18 vorhanden", art: "voraussetzung" },
  "97": { text: "Wenn es sich um die Übermittlung eines Wertes aufgrund der Umstellung der Gasqualität handelt", art: "voraussetzung" },
  "98": { text: "Wenn SG9 PIA+5+SOL:Z08 vorhanden", art: "voraussetzung" },
  "99": { text: "Wenn SG9 PIA+5+WID:Z08 vorhanden", art: "voraussetzung" },
  "100": { text: "Wenn in derselben SG9 LIN das PIA+5+AUA:Z08 vorhanden", art: "voraussetzung" },
  "101": { text: "Wenn in derselben SG9 LIN das PIA+5+FPA:Z08 vorhanden", art: "voraussetzung" },
  "108": { text: "wenn SG9 PIA+5+7-b?:99.41.16/7-b?:99.42.16 (b=Kanal: Wert gemäß Codeliste der OBIS-Kennzahlen und Medien) vorhanden", art: "voraussetzung" },
  "111": { text: "Wenn SG10 DTM+9 DE2379 in demselben Segment mit Wert 303 vorhanden", art: "voraussetzung" },
  "113": { text: "wenn SG7 RFF+AGK (Konfigurations-ID) vorhanden", art: "voraussetzung" },
  "117": { text: "Nur MP-ID aus Sparte Strom", art: "voraussetzung" },
  "118": { text: "Nur MP-ID aus Sparte Gas", art: "voraussetzung" },
  "119": { text: "wenn in SG6 LOC+172 DE3225 die ID der Marktlokation angegeben ist", art: "voraussetzung" },
  "121": { text: "wenn BGM+Z43 (Redispatch Ausfallarbeitüberführungszeitreihe) vorhanden", art: "voraussetzung" },
  "125": { text: "wenn SG9 PIA+5+7-0?:52.0.22/7-b?:53.0.16/7-b?:55.0.16/7-b?:55.0.20/7-b?:55.0.22 (b=Kanal: Wert gemäß Codeliste der OBIS-Kennzahlen und Medien) vorhanden", art: "voraussetzung" },
  "126": { text: "wenn Plausibilisierungshinweise vorliegen", art: "voraussetzung" },
  "127": { text: "wenn ein Korrekturgrund anzugeben ist", art: "voraussetzung" },
  "128": { text: "Wenn es sich um eine Ablesung handelt, welche keine Ablesung aufgrund der Änderung an der Messtechnik oder deren Konfiguration ist (z.B. Kundenablesung).", art: "voraussetzung" },
  "129": { text: "Wenn es sich um eine Ablesung aufgrund der Änderung an der Messtechnik oder deren Konfiguration handelt (z.B. Gerätewechsel).", art: "voraussetzung" },
  "130": { text: "Wenn innerhalb desselben LIN-Segments neben diesem Segment (SG10 DTM+7 Nutzungszeitpunkt) noch das SG10 DTM+60 (Ausführungs- / Änderungszeitpunkt) oder das SG10 DTM+9 (Ablesedatum) vorhanden, darf der Wert der Differenz zwischen dem größeren und dem kleineren Zeitpunkt der DTM-Segmente ausschließlich < 24 Stunden sein. Findet zwischen den beiden Zeitpunkten die Sommer/Winter-Zeitumschaltung statt, darf der Wert der Differenz ausschließlich < 25 Stunden sein. Findet zwischen den beiden Zeitpunkten die Winter/Sommer-Zeitumschaltung statt, darf der Wert der Differenz ausschließlich < 23 Stunden sein.", art: "voraussetzung" },
  "131": { text: "wenn RFF+AGK (Konfigurations-ID) nicht vorhanden", art: "voraussetzung" },
  "132": { text: "wenn LOC+172 (Identifikationsangabe) DE3225 nicht vorhanden", art: "voraussetzung" },
  "133": { text: "Wenn innerhalb desselben LIN-Segments neben diesem Segment (SG10 DTM+7 Nutzungszeitpunkt) noch das SG10 DTM+9 (Ablesedatum) mit dem Code 102 im DE2379 vorhanden ist, darf der Wert der Differenz zwischen dem Wert an der Stelle CCYYMMDD des größeren und dem kleineren Zeitpunkt der DTM-Segmente an der Stelle CCYYMMDD ausschließlich 0 oder 1 Tag sein.", art: "voraussetzung" },
  "134": { text: "Wenn SG10 DTM+9 DE2379 in demselben Segment mit Wert 102 vorhanden", art: "voraussetzung" },
  "135": { text: "Der Wert an der Stelle CCYYMMDD muss ≤ dem Wert an der Stelle CCYYMMDD im DE2380 des DTM+137 sein", art: "voraussetzung" },
  "138": { text: "Wenn es sich um eine Korrekturenergiemenge auf einen Wert aus einem iMS handelt", art: "voraussetzung" },
  "141": { text: "Wenn MP-ID in SG2 NAD+MR in der Rolle MGV", art: "voraussetzung" },
  "142": { text: "wenn im DE3155 in demselben COM der Code EM vorhanden ist", art: "voraussetzung" },
  "143": { text: "wenn im DE3155 in demselben COM der Code TE / FX / AJ / AL vorhanden ist", art: "voraussetzung" },
  "144": { text: "Wenn Wert in SG7 RFF+AGK DE1154 (Konfigurations-ID) vorhanden", art: "voraussetzung" },
  "145": { text: "Wenn in derselben S9 LIN das SG10 DTM+163 (Beginn Messperiode) nicht vorhanden ist.", art: "voraussetzung" },
  "146": { text: "Wenn es bei dem zu übermittelnden Wert um einen Wert zu einem Zeitpunkt handelt.", art: "voraussetzung" },
  "147": { text: "Wenn in derselben S9 LIN das SG10 DTM+7 (Nutzungszeitpunkt) nicht vorhanden ist.", art: "voraussetzung" },
  "148": { text: "Wenn es bei dem zu übermittelnden Wert um einen Wert in einem Zeitintervall handelt.", art: "voraussetzung" },
  "149": { text: "Wenn in derselben S9 LIN das SG10 DTM+163 (Beginn Messperiode) vorhanden ist.", art: "voraussetzung" },
  "150": { text: "Wenn BGM+Z69 (Redispatch tägliche Ausfallarbeitsüberführungszeitreihe) vorhanden.", art: "voraussetzung" },
  "151": { text: "Wenn BGM+Z27 (Bewegungsdaten im Kalenderjahr vor Lieferbeginn) vorhanden.", art: "voraussetzung" },
  "152": { text: "Wenn BGM+7 (Prozessdatenbericht) vorhanden.", art: "voraussetzung" },
  "153": { text: "Wenn SG9 PIA+5+7-0?:33.86.0 vorhanden", art: "voraussetzung" },
  "154": { text: "Wenn SG9 PIA+5+7-0?:33.47.0 vorhanden", art: "voraussetzung" },
  "492": { text: "Wenn MP-ID in NAD+MR (Nachrichtenempfänger) aus Sparte Strom", art: "voraussetzung" },
  "493": { text: "Wenn MP-ID in NAD+MR (Nachrichtenempfänger) aus Sparte Gas", art: "voraussetzung" },
  "494": { text: "Das hier genannte Datum muss der Zeitpunkt sein, zu dem das Dokument erstellt wurde, oder ein Zeitpunkt, der davor liegt.", art: "voraussetzung" },
  "495": { text: "Der Zeitpunkt muss ≤ dem Wert im DE2380 des DTM+137 sein", art: "voraussetzung" },
  "501": { text: "Hinweis: Es sind nur die Werte erlaubt, die in der EDI@Energy Codeliste der OBIS-Kennzahlen und Medien mit dem entsprechenden Prüfidentifikator versehen sind.", art: "hinweis" },
  "502": { text: "Hinweis: Einmal für die Energiemenge von Beginn des Kalenderjahres bis zum Lieferbeginn und bis zu zweimal für die zwei höchsten Monatsleistungswerte (wegen KAV) von Beginn des Kalenderjahres bis zum Lieferbeginn", art: "hinweis" },
  "506": { text: "Hinweis: Nur bei Einspeisemengen und bei Gas zur stündlichen Energiedatenübermittlung", art: "hinweis" },
  "509": { text: "Hinweis: Falls es sich um eine Korrekturenergiemenge handelt, ist hier die Referenz auf die MSCONS anzugeben, in der der Zählerstand vorab übermittelt wurde.", art: "hinweis" },
  "510": { text: "Hinweis: Verwendung der ID der Messlokation", art: "hinweis" },
  "511": { text: "Hinweis: Verwendung der ID des MaBiS-ZP", art: "hinweis" },
  "512": { text: "Hinweis: Verwendung der Bilanzkreisbezeichnung", art: "hinweis" },
  "513": { text: "Hinweis: Verwendung der Bezeichnung des Bilanzierungsgebietes", art: "hinweis" },
  "514": { text: "Hinweis: Verwendung der ID der Marktlokation", art: "hinweis" },
  "515": { text: "Hinweis: Verwendung der Profilbezeichnung", art: "hinweis" },
  "516": { text: "Hinweis: Verwendung der Bezeichnung der Profilschar", art: "hinweis" },
  "518": { text: "Hinweis: Verwendung der ID der Tranche", art: "hinweis" },
  "519": { text: "Hinweis: Nur wenn der gemessene Lastgang der Messlokation nicht dem Lastgang der Marktlokation 1:1 entspricht.", art: "hinweis" },
  "520": { text: "Hinweis: Wenn es sich um eine 1:1 Beziehung zwischen Messlokation und Marktlokation handelt und der gemessene Lastgang der Messlokation dem Lastgang der Marktlokation 1:1 entspricht, oder wenn der gemessene Lastgang nicht dem Lastgang der Marktlokation entspricht.", art: "hinweis" },
  "522": { text: "Hinweis: Nur für die Übermittlung der Korrekturenergiemengen im Zeitintervall zwischen zwei Messwerten.", art: "hinweis" },
  "523": { text: "Hinweis: Nur für die Übermittlung der Energiemenge im Zeitintervall zwischen zwei Messwerten vor der Netznutzungsabrechnung.", art: "hinweis" },
  "524": { text: "Hinweis: Nur, wenn es sich um die Übermittlung von Abrechnungsbrennwert und Z-Zahl für den vom Lieferanten über eine Geschäftsdatenanfrage angeforderten Zeitraum handelt.", art: "hinweis" },
  "525": { text: "Hinweis: Nur für die Übermittlung der Energiemenge im Zeitintervall für eine Marktlokation ohne Messlokation (Pauschalanlage) wenn eines der Ereignisse aus Kapitel 4.2 eingetreten ist.", art: "hinweis" },
  "526": { text: "Hinweis: Wert aus BGM+Z24 DE1004 der ORDERS mit der die Allokationsliste bestellt wurde.", art: "hinweis" },
  "528": { text: "Hinweis: Wert aus BGM+Z28 DE1004 der ORDERS mit der die Anforderung von Messwerten erfolgt ist.", art: "hinweis" },
  "529": { text: "Hinweis: Wert aus BGM+7 DE1004 der ORDERS mit der die Anforderung von Messwerten erfolgt ist.", art: "hinweis" },
  "530": { text: "Hinweis: Wert aus SG4 IDE+24 DE7402 der UTILMD mit dem der Sender der MSCONS die vorherigen Stammdaten mittels UTILMD übermittelt hat.", art: "hinweis" },
  "531": { text: "Hinweis: Wert aus BGM+7 DE1004 der MSCONS mit der der Zählerstand übermittelt wurde.", art: "hinweis" },
  "532": { text: "Hinweis: Wert aus BGM+7/Z27/Z28/270/Z41/Z42/Z85 DE1004 der MSCONS Nachricht, die storniert wird", art: "hinweis" },
  "535": { text: "Hinweis: Verwendung der ID des Netzkoppelpunktes Strom/Gas", art: "hinweis" },
  "538": { text: "Hinweis: Die Referenz auf die ORDERS ist nur dann anzugeben, wenn diese Werte vom Empfänger auch ursprünglich mittels ORDERS angefragt wurden.", art: "hinweis" },
  "541": { text: "Hinweis: Ein Korrekturgrund ist anzugeben, wenn: 1. ein bereits an den MP übermittelter vorläufiger Wert nach Stornierung durch einen Ersatzwert ersetzt wird, oder 2. ein bereits an den MP übermittelter Ersatzwert nach Stornierung durch einen Ersatzwert ersetzt wird, oder 3. ein bereits an den MP übermittelter wahrer Wert nach Stornierung durch einen Ersatzwert ersetzt wird, oder 4. ein bereits an den MP übermittelter wahrer Wert nach Stornierung durch einen wahren Wert ersetzt wird.", art: "hinweis" },
  "543": { text: "Hinweis: Wert aus BGM+Z23 DE1004 der ORDERS mit der die bilanzierte Menge bestellt wurde.", art: "hinweis" },
  "544": { text: "Hinweis: Bei einer Mengenaufteilung (z. B. Aufgrund einer Abgrenzung) für SG6 LOC+172 muss für den frühesten angegebenen Zeitpunkt zum Beginn des Zeitintervalls (über alle Wiederholungen der LIN-Segmente derselben SG6 LOC+172 hinweg) zu jeder OBIS-Kennziffer ein Zählerstand vorhanden und kommuniziert sein.", art: "hinweis" },
  "545": { text: "Hinweis: Bei einer Mengenaufteilung (z. B. Aufgrund einer Abgrenzung) für SG6 LOC+172 muss für den spätesten angegebenen Zeitpunkt zum Ende des Zeitintervalls (über alle Wiederholungen der LIN-Segmente derselben SG6 LOC+172 hinweg) zu jeder OBIS-Kennziffer ein Zählerstand vorhanden und kommuniziert sein.", art: "hinweis" },
  "546": { text: "Hinweis: Eine Referenz auf die Stammdatenänderung des Gerätewechsels ist immer anzugeben, wenn diese dem Sender vorliegt.", art: "hinweis" },
  "547": { text: "Hinweis: Der Code 270 ist nur zu nutzen, wenn ein Lieferschein, der vor dem 1.4.2021 erstellt wurde, storniert wird.", art: "hinweis" },
  "551": { text: "Hinweis: Ein Korrekturgrund ist anzugeben, wenn: 1. ein bereits an den MP übermittelter vorläufiger Wert durch einen Ersatzwert ersetzt wird, oder 2. ein bereits an den MP übermittelter Ersatzwert durch einen Ersatzwert ersetzt wird, oder 3. ein bereits an den MP übermittelter wahrer Wert durch einen Ersatzwert ersetzt wird, oder 4. ein bereits an den MP übermittelter wahrer Wert durch einen wahren Wert ersetzt wird.", art: "hinweis" },
  "553": { text: "Hinweis: Wert aus BGM+Z34 DE1004 der ORDERS mit der die Reklamation von Werten erfolgt ist", art: "hinweis" },
  "554": { text: "Hinweis: Verwendung der ID der Technischen Ressource", art: "hinweis" },
  "556": { text: "Hinweis: Wert aus BGM+Z45 DE1004 der ORDERS mit der die Anforderung der Ausfallarbeit durch den anfNB erfolgt ist.", art: "hinweis" },
  "557": { text: "Hinweis: Die Referenz auf die ursprüngliche MSCONS ist anzugeben, wenn es sich um die Übermittlung eines Gegenvorschlags durch den BTR handelt.", art: "hinweis" },
  "558": { text: "Hinweis: Wert aus BGM+Z45 DE1004 der MSCONS auf die sich die Übermittlung des Gegenvorschlags durch den BTR bezieht.", art: "hinweis" },
  "559": { text: "Hinweis: Ein Korrekturgrund ist anzugeben, wenn: 1. ein bereits an den MP übermittelter vorläufiger Wert nach Stornierung durch einen Ersatzwert ersetzt wird, oder 2. ein bereits an den MP übermittelter Ersatzwert nach Stornierung durch einen Ersatzwert ersetzt wird, oder 3. ein bereits an den MP übermittelter wahrer Wert nach Stornierung durch einen Ersatzwert ersetzt wird, oder 4. ein bereits an den MP übermittelter wahrer Wert nach Stornierung durch einen wahren Wert ersetzt wird.", art: "hinweis" },
  "560": { text: "Hinweis: Ein Korrekturgrund ist anzugeben, wenn: 1. ein bereits an den MP übermittelter vorläufiger Wert durch einen Ersatzwert ersetzt wird, oder 2. ein bereits an den MP übermittelter Ersatzwert durch einen Ersatzwert ersetzt wird, oder 3. ein bereits an den MP übermittelter wahrer Wert durch einen Ersatzwert ersetzt wird, oder 4. ein bereits an den MP übermittelter wahrer Wert durch einen wahren Wert ersetzt wird.", art: "hinweis" },
  "566": { text: "Hinweis: Es sind nur die Werte erlaubt, die im vorherigen Stammdatenaustausch zu diesem Meldepunkt vom MSB zum Zeitpunkt übermittelt wurden.", art: "hinweis" },
  "567": { text: "Hinweis: Es ist die Konfigurations-ID anzugeben, die im vorherigen Stammdatenaustausch kommuniziert wurde.", art: "hinweis" },
  "568": { text: "Hinweis: Verwendung ist nur zulässig, wenn es sich um 1:n Beziehung zwischen Markt- und Messlokation handelt und auf Ebene der Messlokation unterschiedliche Ersatzwertbildungsverfahren verwendet und kommuniziert wurden.", art: "hinweis" },
  "569": { text: "Hinweis: Bei mehreren Zählerständen einer Messlokation (z. B. HT/NT) ist diese Zeitangabe zu nutzen und eine Wiederholung das SG9 LIN durchzuführen.", art: "hinweis" },
  "570": { text: "Hinweis: Verwendung ist nur zulässig, wenn es sich um 1:n Beziehung zwischen Markt- und Messlokation handelt und auf Ebene der Messlokation unterschiedliche Gründe für die Ersatzwertbildung vorliegen und kommuniziert wurden.", art: "hinweis" },
  "571": { text: "Hinweis: Verwendung ist nur zulässig, wenn es sich um 1:n Beziehung handelt und auf Ebene der Netzkopplungspunkte unterschiedliche Gründe für die Ersatzwertbildung vorliegen und kommuniziert wurden.", art: "hinweis" },
  "572": { text: "Hinweis: Verwendung ist nur zulässig, wenn es sich um 1:n Beziehung handelt und auf Ebene der Netzkopplungspunkte unterschiedliche Ersatzwertbildungsverfahren vorliegen und kommuniziert wurden.", art: "hinweis" },
  "573": { text: "Hinweis: Eine Energiemenge in der Sparte Gas ist gemäß DVGW G685 Arbeitsblatt 4 Kapitel 5.3 auf ganze Kilowattstunden zu runden.", art: "hinweis" },
  "574": { text: "Hinweis: Wert aus BGM DE1004 der ORDERS mit der die Bestellung der Werte nach Typ 2 erfolg ist", art: "hinweis" },
  "575": { text: "Hinweis: Verwendung der ID der Netzlokation", art: "hinweis" },
  "576": { text: "Hinweis: Es darf nur eine Information im DE3148 übermittelt werden", art: "hinweis" },
  "577": { text: "Hinweis: Dieser Code ist auch zu verwenden, wenn aufgrund der Beendigung einer Messlokation (Stilllegung) die Beendigung der Marktlokation (Stilllegung) zu unterschiedlichen Zeitpunkten erfolgt, das heißt die Beendigung der Messlokation vor der Beendigung der Marktlokation erfolgt. Die Energiemenge ist bis zum Endezeitpunkt der Marklokation zu übermitteln, wenngleich der letzte Zählerstand der Messlokation zu einem früheren Zeitpunkt liegt.", art: "hinweis" },
  "578": { text: "Hinweis: Wenn es sich um die Übermittlung des Leistungswertes für die Netzentgelte mit Jahresleistungspreissystem handelt.", art: "hinweis" },
  "579": { text: "Hinweis: Wenn es sich um die Übermittlung des Leistungswertes für die Netzentgelte mit Monatsleistungspreissystem handelt.", art: "hinweis" },
  "580": { text: "Hinweis: Wenn es sich um die Übermittlung des Leistungswertes für die Netzentgelte mit Tagesleistungspreissystem handelt.", art: "hinweis" },
  "581": { text: ": Hinweis: Wenn es sich um die Übermittlung des Monatsmaximums gemäß WiM handelt.", art: "hinweis" },
  "902": { text: "Format: Möglicher Wert: ≥ 0", art: "format" },
  "904": { text: "Format: genau 16 Stellen", art: "format" },
  "905": { text: "Format: max. 3 Stellen", art: "format" },
  "906": { text: "Format: max. 3 Nachkommastellen", art: "format" },
  "907": { text: "Format: max. 4 Nachkommastellen", art: "format" },
  "908": { text: "Format: Mögliche Werte: 1 bis n", art: "format" },
  "909": { text: "Format: Mögliche Werte: 0 bis n", art: "format" },
  "910": { text: "Format: Möglicher Wert: < 0 oder ≥ 0", art: "format" },
  "917": { text: "Format: max. 4 Vorkommastellen", art: "format" },
  "918": { text: "Format: Zeichen aus dem über UNOC definierten Zeichensatz, wobei von den Buchstaben nur Großbuchstaben erlaubt sind.", art: "format" },
  "922": { text: "Format: TR-ID", art: "format" },
  "925": { text: "Format: max. 5 Nachkommastellen", art: "format" },
  "931": { text: "Format: ZZZ = +00", art: "format" },
  "937": { text: "Format: keine Nachkommastelle", art: "format" },
  "939": { text: "Format: Die Zeichenkette muss die Zeichen @ und . enthalten", art: "format" },
  "940": { text: "Format: Die Zeichenkette muss mit dem Zeichen + beginnen und danach dürfen nur noch Ziffern folgen", art: "format" },
  "950": { text: "Format: Marktlokations-ID", art: "format" },
  "951": { text: "Format: Zählpunktbezeichnung", art: "format" },
  "960": { text: "Format: Netzlokations-ID", art: "format" },
  "2001": { text: "Segmentgruppe ist nur einmal je UNH anzugeben", art: "wiederholbarkeit" },
  "2002": { text: "Segmentgruppe ist bis zu drei Mal je SG5 NAD+DP anzugeben", art: "wiederholbarkeit" },
  "2003": { text: "Segmentgruppe ist genau zwei Mal je SG9 LIN anzugeben", art: "wiederholbarkeit" },
};
if (typeof window!=='undefined') window.EdiBedingungen = Object.assign(window.EdiBedingungen||{}, msconsBedingungen);
if (typeof module!=='undefined') module.exports = msconsBedingungen;
