// _bedingungen.js
// Zentrale, DATENGETRIEBENE Datenbank aller AHB-Bedingungen (die "[NNN]"-Verweise).
//
// Enthält alle 614 im UTILMD-Strom-AHB (V2.2) definierten Bedingungen als Text, plus
// - je Bedingung die aus dem Nummernkreis abgeleitete Art (Voraussetzung/Hinweis/
//   Format/Wiederholbarkeit), und
// - für maschinell prüfbare Bedingungen ein Prüflogik-Overlay (STS-Abhängigkeit,
//   Gegensegment bei Entweder-Oder, Kardinalität).
//
// Die Texte wurden mit scripts/extract_bedingungen.py aus dem AHB-Klartext extrahiert
// (spaltentreue, gutter-basierte Rekonstruktion der rechten Bedingungsspalte, Konsens
// über alle Fundstellen, datengetriebene Wortnaht-Reparatur). 23 schwer aus dem
// PDF rekonstruierbare Stellen sind handverifizierte Overrides (in extract_bedingungen.py
// dokumentiert). Diese Datei wird von scripts/generate_bedingungen_js.py erzeugt -
// NICHT von Hand editieren; stattdessen Extraktor/Generator anpassen und neu erzeugen.
//
// NUMMERNKREISE (Allgemeine Festlegungen, Kap. 6.4):
//   [1]   - [499]  Voraussetzungen    -> harte Prüfung
//   [500] - [899]  Hinweise           -> nur informativ
//   [901] - [999]  Formatbedingungen  -> Formatprüfung des Datenelements
//   [2000]- [2499] Wiederholbarkeiten -> Kardinalität
//
// OPERATOREN zwischen Bedingungen (Kap. 6.4.6): ∧ (UND), ∨ (ODER), ⊻ (XODER); runde
// Klammern gewichten. Ein Hinweis innerhalb einer Verknüpfung ist NIE Teil der
// einzuhaltenden Voraussetzung.
//
// Quelle: UTILMD-Strom-AHB (V2.2) + Allgemeine Festlegungen.

// Leitet die Bedingungsart aus dem Nummernkreis ab.
function bedingungsart(nr) {
    const n = parseInt(String(nr).replace(/\D/g, ""), 10);
    if (/^UB\d/.test(String(nr))) return "zeitpunkt";
    if (n >= 1 && n <= 499)     return "voraussetzung";   // harte Prüfung
    if (n >= 500 && n <= 899)   return "hinweis";         // nur informativ
    if (n >= 901 && n <= 999)   return "format";          // Formatprüfung
    if (n >= 2000 && n <= 2499) return "wiederholbarkeit"; // Kardinalität
    return "unbekannt";
}

// Prüflogik-Overlay: maschinell auswertbare Metadaten je Bedingung.
//   gegensegment  : Entweder-Oder - das Segment, dessen Fehlen die Bedingung auslöst.
//   wennStsErgaenzung : Bedingung greift nur bei dieser STS+7-Transaktionsgrundergänzung.
//   maxProVorgang : Wiederholbarkeit - erlaubte Höchstzahl je SG4 IDE.
// var statt const (alle Deklarationen dieser Datei): der Validator lädt mehrere
// Bedingungsdateien nacheinander in
// denselben Kontext; mit const bricht die zweite Datei mit "already been declared" ab.
var bedingungLogik = {
    "348": {
        "gegensegment": {
            "tag": "LOC",
            "qual": "Z21"
        }
    },
    "349": {
        "gegensegment": {
            "tag": "LOC",
            "qual": "Z17"
        }
    },
    "479": {
        "wennStsErgaenzung": "ZW3"
    },
    "480": {
        "wennStsErgaenzung": "ZW4"
    },
    "481": {
        "wennStsErgaenzung": "ZW5"
    },
    "96":  { "wennStsErgaenzung": "ZAP" },
    "192": { "wennStsErgaenzung": "ZW4" },
    "279": { "wennStsErgaenzung": "ZW4" },
    "476": { "wennStsErgaenzung": "ZW0" },
    "477": { "wennStsErgaenzung": "ZW1" },
    "478": { "wennStsErgaenzung": "ZW2" },
    "483": { "wennStsErgaenzung": "ZW7" },
    "484": { "wennStsErgaenzung": "ZW8" },
    "487": { "wennStsErgaenzung": "ZX1" },
    "572": { "wennStsErgaenzung": "ZW4" },
    "2001": { "wennStsErgaenzung": "ZW5" },
    "301": { "wennBgm": { "codes": ["E03"], "vorhanden": true } },
    "315": { "wennBgm": { "codes": ["Z88"], "vorhanden": true } },
    "2061": {
        "maxProVorgang": 1
    }
};

// Alle 614-AHB-Bedingungstexte (extrahiert; Schlüssel = Bedingungsnummer als String).
var bedingungTexte = {
    "1": "Wenn Aufteilung vorhanden",
    "2": "Wenn UNH DE0070 (Übermittlungsfolgenummer) mit 1 vorhanden",
    "3": "(Übermittlungsfolgenummer) mit 1 vorhanden",
    "4": "Wenn MP-ID in SG2 NAD+MR (Nachrichtenempfänger) in der Rolle LF",
    "5": "Wenn MP-ID in SG2 NAD+MS (Nachrichtenabsender) in der Rolle LF",
    "6": "Wenn MP-ID in SG2",
    "7": "Wenn SG4 STS+7++ZG9/ZH1/ZH2 (Transaktionsgrund: Aufhebung einer zukünftigen Zuordnung wegen Auszug des Kunden / -wegen Stilllegung / -wegen aufgehobenem Vertragsverhältnis) vorhanden",
    "8": "Wenn für Datenclearing erforderlich",
    "9": "Wenn MP-ID in SG2 NAD+MS (Nachrichtenabsender) in der Rolle MSB",
    "10": "Wenn SG4 STS+7++xxx+xxx+E01/E03 (Transaktionsgrund befristete Anmeldung) vorhanden",
    "11": "Wenn SG4 STS+7++ZG9/ZH1/ZH2 (Transaktionsgrund: Aufhebung einer zukünftigen Zuordnung wegen Auszug des Kunden / -wegen Stilllegung / -wegen aufgehobenem Vertragsverhältnis) nicht vorhanden",
    "12": "Wenn SG4 DTM+471 (Ende zum nächstmöglichem Termin) nicht vorhanden",
    "13": "(Ende zum nächstmöglichem Termin) nicht vorhanden",
    "14": "Wenn Datum bekannt",
    "15": "Wenn in derselben SG8 das SEQ+Z98 (Informative Daten der Marktlokation) vorhanden",
    "16": "Wenn SG4 STS+E01++Z12 (Status der Antwort: Ablehnung Vertragsbindung) vorhanden",
    "17": "Wenn in derselben SG8 das SEQ+Z01/Z80/Z81 (Daten der Marktlokation) vorhanden",
    "18": "Wenn SG4 DTM+93 (Ende zum) nicht vorhanden",
    "19": "Wenn SG8 SEQ+Z01/ Z98 (Daten der Marktlokation) SG10 CCI+++ZC0 (Prognose auf Basis von Werten) vorhanden",
    "21": "Wenn SG10 CCI+++ZA6 (Prognose auf Basis von Profilen) in dieser SG8 vorhanden",
    "22": "Es ist die Zeitraum-ID vom DE1156 aus einem passenden SG6 RFF+Z47/ Z48/ Z49 (Verwendungszeitraum der Daten) einzutragen",
    "23": "Wenn in dieser SG4 das STS+E01++A05 (Status der Antwort) vorhanden",
    "24": "Wenn in dieser SG4 das STS+E01++A25 (Status der Antwort) vorhanden",
    "25": "Wenn die Veräußerungsform der erzeugenden Marktlokation der Marktprämie zugeordnet ist",
    "27": "Wenn das DE2380 von SG4 DTM+Z01 (Kündigungsfrist des Vertrags) an vierter Stelle ein T oder R enthält",
    "28": "Wenn in dieser SG4 IDE+24 das STS+E01++A04: E_0017 bzw. A03: E_0052 (Zusätzlicher Datensatz / ergänzte Marktlokation) nicht vorhanden",
    "29": "Wenn in dieser SG4 IDE+24 das STS+E01++A06: E_0017 bzw. A05: E_0052 (Zu viele Marktlokationen enthalten / entfallene Marktlokation) nicht vorhanden",
    "30": "Wenn Antwort auf Aktivierung übermittelt wird",
    "31": "Wenn eine Korrektur erfolgt",
    "32": "Wenn mehr als ein SG8 (Referenz auf die Lokationsbündelstruktur) vorhanden",
    "33": "Wenn in einer SG8 SEQ+Z79 im PIA+5 (Erforderliches Produkt) DE7140 ein Produkt-Code genannt ist, der in der Codeliste der Konfigurationen im Kapitel 6 \"Produkte zur Bestellung / Änderung von Daten\" in der Spalte \"Code der Produkteigenschaft 9991000002272 („Lieferant“ (Empfänger der Vergütung zur Einspeisung)) befüllt ist.",
    "34": "Wenn Antwort auf Deaktivierung übermittelt wird",
    "35": "Wenn das DE2380 von SG4 DTM+Z01 (Kündigungsfrist des Vertrags) an vierter Stelle T (Termin) enthält",
    "36": "Wenn in derselben SG8 SEQ+Z79 im PIA+5 (Erforderliches Produkt) DE7140 ein Produkt-Code genannt ist, der in der Codeliste der Konfigurationen im Kapitel 6.1 \"Anmeldung einer Zuordnung des LFN (UTILMD)\" in der Spalte \"Code der Produkteigenschaft (Wertebereich)\" mit einem Code befüllt ist.",
    "37": "Wenn Anmeldung/ Änderung befristet",
    "38": "Es sind nur die Code der Produkteigenschaft zu dem in derselben SG8 SEQ+Z79 im PIA+5 (Erforderliches Produkt) DE7140 erlaubt, die in der Codeliste der Konfigurationen im Kapitel 6.1 \"Anmeldung einer Zuordnung des LFN (UTILMD)\" in derselben Zeile wie der Produkt-Code stehen und in der Spalte \"Code der Produkteigenschaft (Wertebereich)\" genannt sind.",
    "39": "Wenn in derselben SG8 SEQ+Z79 m PIA+5 (Erforderliches Produkt) DE7140 ein Produkt-Code genannt ist, der in der Codeliste der Konfigurationen im Kapitel 6.1 \"Anmeldung einer Zuordnung des LFN (UTILMD)\" in der Spalte \"Wertedetails für Position\" die ggf. enthaltene Bedingung erfüllt ist",
    "40": "Es ist nur der Wertebereich erlaubt, der zu dem in derselben SG8 SEQ+Z79 im PIA+5 (Erforderliches Produkt) DE7140 genannten Produkt, das in der Codeliste der Konfigurationen im Kapitel 6.1 \"Anmeldung einer Zuordnung des LFN (UTILMD)\" in derselben Zeile wie der Produkt-Code in der Spalte \"Wertedetails für Position\" genannt ist",
    "41": "Es ist eine Produktpaket-ID aus dem DE1050 von einem SG8 SEQ+Z79 (Bestandteil eines Produktpakets) zu nennen",
    "42": "Wenn mehr als ein SG8 SEQ+ZH0 (Priorisierung erforderliches Produktpaket) vorhanden",
    "43": "Wenn in dieser SG4 das STS+E01++A12 / A13 (Status der Antwort) vorhanden",
    "44": "Es ist die Zeitraum-ID vom DE1156 aus einem passenden SG6 RFF+Z49/ Z53 (Verwendungszeitraum der Daten: \"Gültige Daten\", \"Keine Daten\") aus der Anfragennachricht aus SG6 RFF+TN DE1154 ((Referenz Vorgangsnummer (aus Anfragenachricht)) einzutragen",
    "45": "Wenn in derselben SG8 das SG10 CCI+Z01++Z82 (Verwendungsumfang: ID der prozessual behandelten Messlokation) vorhanden",
    "46": "Wenn ID für Objekt vergeben wurde",
    "47": "Wenn SG10 CCI+15++Z21 (Summenzeitreihentyp) CAV+DBA/ VZR/ EGS/ LGS/ SLS/ SES/ TLS/ TES/ BIL/ BIP/ BIT/ GAL/ GAP/ GAT/ GEL/ GEP/ GET/ SOL/ SOP/ SOT/ WFL/ WFP/ WFT/ WNL/ WNP/ WNT vorhanden",
    "48": "Wenn in dieser SG4 das STS+E01++A99 (Status der Antwort: Sonstiges) vorhanden",
    "49": "Wenn in dieser SG4 das STS+E01++E14 (Status der Antwort: Ablehnung Sonstiges) vorhanden",
    "50": "Wenn kein SG8 SEQ+ZE7 (Informative Daten der Tranche) mit derselben Zeitraum-ID im DE1050 auf die gleiche Marktlokation-ID mit dem RFF+Z18 (Marktlokation) referenziert wie dieses SG8 SEQ+Z98 (Informative Daten der Marktlokation)",
    "51": "Wenn die Marktlokations-ID im SG8 RFF+Z18 derselben SG8 SEQ+Z98 (Informative Daten der Marktlokation) mit derselben Zeitraum-ID im DE1050 nicht auf ein SG8 SEQ+Z78 (Referenz auf die Lokationsbündelstruktur) verweist, welches im SG8 RFF+Z31 (Referenz auf die Lokationsbündelstruktur) den Code der Lokationsbündelstruktur mit der ID 9992 00000 001 8 (Verbrauch ohne Messlokation (Pauschal)) vorhanden ist X X X",
    "52": "Wenn SG10 CCI+Z07++Z55/ Z56 (Profiltyp: sonstige verbrauchende Marktlokation / sonstige erzeugende Marktlokation) vorhanden",
    "53": "(Profiltyp: sonstige verbrauchende Marktlokation / sonstige erzeugende Marktlokation) vorhanden",
    "54": "Wenn SG8 SEQ+Z01 (Daten der Marktlokation) SG10 CCI+Z30++Z06 (Lieferrichtung: Erzeugung) vorhanden",
    "56": "Wenn im STS+E01 im DE9013 (Status der Antwort) ein Antwortcode aus dem Cluster Zustimmung vorhanden ist",
    "57": "Wenn in derselben SG8 das CCI+Z45++ZD9 (Abrechnung findet statt) vorhanden ist",
    "58": "Wenn in diesem CCI das DE3055 mit dem Code 293 vorhanden",
    "60": "Wenn BGM+Z90 (Beendigung der Zuordnung zur Lokation) vorhanden",
    "61": "Wenn BGM+Z89 (Zuordnung zur Lokation) vorhanden",
    "62": "Wenn mehr als eine SG8 SEQ+Z45 (Netznutzungsabrechnungsdaten der Marktlokation), mit derselben Zeitraum-ID im DE1050, mit einer Gruppen/Artikel-ID im SG8 PIA+Z02 (Gruppenartikel-ID / Artikel-ID), welche mit 1-08-1/2/3/4/5 beginnt, vorhanden",
    "63": "Wenn in dieser SG4 das STS+E01++A15 (Status der Antwort) vorhanden",
    "64": "Wenn mehr als eine SG8 SEQ+ZE1 (Informative Netznutzungsabrechnungsdaten der Marktlokation) mit einer Gruppen-/ Artikel-ID im SG8 PIA+Z02 (Gruppenartikel-ID / Artikel-ID), welche mit 1-08-1/2/3/4/5 beginnt, vorhanden",
    "65": "Wenn in derselben SG8 SEQ+ZE1 (Informative Netznutzungsabrechnungsdaten der Marktlokation) eine Gruppen-/Artikel-ID im PIA+Z02 (Gruppenartikel-ID / Artikel-ID), welche mit 1-08-1/2/3/4/5 beginnt, vorhanden",
    "66": "Wenn SG8 SEQ+ZH0 (Priorisierung erforderliches Produktpaket) mehr als einmal vorhanden",
    "67": "Wenn in keinem SG8 SEQ+Z79 (Bestandteil eine Produktpakets) CCI+Z66/CAV+ZH9 (Produkteigenschaft/ Code der Produkteigenschaft) der Code 9991000002933 (Ruhende Marktlokation ausprägen) vorhanden ist.",
    "68": "Wenn SG8 SEQ+ ZH0 (Priorisierung erforderliches Produktpaket) mehr als zweimal vorhanden",
    "69": "Wenn SG8 SEQ+ ZH0 (Priorisierung erforderliches Produktpaket) mehr als dreimal vorhanden",
    "70": "Wenn SG8 SEQ+ ZH0 (Priorisierung erforderliches Produktpaket) fünfmal vorhanden",
    "71": "Wenn Antwort auf Zuordnung übermittelt wird",
    "72": "Wenn Antwort auf Beendigung der Zuordnung übermittelt wird",
    "73": "Wenn in derselben SG8 im PIA DE7140 ein Code aus der Codeliste der Gruppenartikel- und Artikel-ID vorhanden ist, der in der Spalte UTILMD/Preisangabe mit X gekennzeichnet ist",
    "76": "Wenn Summenzeitreihe auf Ebene des Bilanzierungsgebiet",
    "77": "Wenn SG8 SEQ+Z03 ∧ [2061] (Zähleinrichtungsdaten) CAV+Z30 (Identifikation/Nummer des Gerätes) nicht vorhanden",
    "78": "Wenn SG4 STS+7++E02 (Transaktionsgrund: benötigt, wenn an dieser selbst eine kME/mME vorliegt, nicht an allen Marklokationen eines Lokationsbündels, wenn an einer Marklokation des Lokationsbündels eine kME/ mME vorliegt. (Marktlokation) aus einer SG8 SEQ+Z01 (Daten der Marktlokation), in der SG10 CCI+++Z83",
    "79": "Wenn SG4 STS+7++Z33 (Auszug wegen Stilllegung) vorhanden",
    "80": "Wenn in derselben SG8 SEQ+Z61 (Produkt-Daten der Steuerbaren Ressource) das PIA+5 (Produkt-Daten der Steuerbaren Ressource) nicht vorhanden",
    "81": "Wenn in derselben SG8 SEQ+Z61/ ZB3/ ZB4 (Produkt-Daten der Steuerbaren Ressource) das SG10 CCI+11 (Details zum Produkt der Steuerbaren Ressource) nicht vorhanden",
    "82": "Wenn in der selben SG8 (Daten der technischen Einrichtungen) das SG10 CCI+Z63 (Information zu technischen Einrichtungen) CAV+ZH7 (Technische Einrichtungen vorhanden) vorhanden",
    "83": "Wenn in dieser SG4 das STS+E01++A08/ A16/ A99 (Status der Antwort) vorhanden",
    "84": "Wenn SG4 STS+E01++A57 (Status der Antwort) vorhanden",
    "85": "Wenn das DE2380 von SG4 DTM+Z01 (Kündigungsfrist des Vertrags) an vierter Stelle M, Q, H oder J enthält",
    "87": "Es ist ein Monatserster 0 Uhr (gem. deutscher Zeit) anzugeben",
    "88": "Wert muss identisch mit DE2380 aus dem SG4 DTM+157 (Änderung zum) sein",
    "89": "Wenn im SG8 SEQ+Z01 (Daten der Marktlokation) mit identischer Zeitraum-ID im DE1050 wie in diesem SG8, das SG10 CCI+++ZA6 (Prognosegrundlage der Marktlokation: Prognose auf Basis von Profilen) CAV+E14 (TLP/TEP) vorhanden",
    "90": "Wenn SG10 CCI+++ZA6 (Prognosegrundlage der Marktlokation: Prognose auf Basis von Profilen) einmal mit CAV+E14 (TLP/TEP) und einmal mit CAV+E02 (SLP/SEP) in dieser SG8 vorhanden",
    "91": "Wenn nicht SG10 CCI+++ZA6 (Prognosegrundlage der Marktlokation: Prognose auf Basis von Profilen) einmal mit CAV+E14 (TLP/ TEP) und einmal mit CAV+E02 (SLP/SEP) in dieser SG8 vorhanden",
    "92": "Wenn Wert innerhalb SG bzw. Segment geändert wird",
    "93": "Erlaubte Codes aus der PRICAT BGM+Z32 (Preisblatt Messstellenbetrieb) des verantwortlichen MSB",
    "94": "Wenn ein Segment innerhalb der SG vorhanden",
    "95": "Wenn in derselben SG10 das CCI+Z17 (Stromverbrauchsart) CAV+ZE5 (E-Mobilität) vorhanden",
    "96": "Wenn SG4 STS+7++xxx+ZAP (Transaktionsgrundergänzung ruhende Marktlokation) vorhanden",
    "97": "Wenn in einem SG10 CAV+ZH9 DE7110 der Code der Produkteigenschaft (Wertebereich) 9991000002420 (Marktprämie) vorhanden ist",
    "98": "Wenn MP-ID in SG2 NAD+MS (Nachrichtenabsender) in der Rolle NB",
    "99": "Wenn MP-ID in SG2 NAD+MS (Nachrichtenabsender) in der Rolle ÜNB",
    "100": "Wenn SG10 CAV+TLS/ TES/ BIT/ GET/ GAT/ SOT/ WNT/ WFT/ WAT vorhanden",
    "101": "Wenn SG10 CCI+++ZA6 (Prognosegrundlage der Marktlokation: Prognose auf Basis von Profilen) CAV+E14/ Z36 (TLP/ TEP/ TEP mit Ref.messung) in dieser SG8 vorhanden",
    "102": "Wenn SG10 CCI+++ZA6 (Prognosegrundlage der Marktlokation: Prognose auf Basis von Profilen) CAV+Z36 (TEP mit Ref.messung) in dieser SG8 vorhanden",
    "103": "Wenn SG9 QTY+265 (Arbeit / Leistung für tagesparameterabhängige Marktlokation: Veranschlagte Jahresmenge Gesamt) in dieser SG8 vorhanden",
    "104": "Wenn SG9 QTY+Z08 (Arbeit / Leistung für tagesparameterabhängige Marktlokation: angepasste elektrische Arbeit nach Anhang D) in dieser SG8 vorhanden",
    "105": "Wenn SG9 QTY+Z10 (Arbeit / Leistung für tagesparameterabhängige Marktlokation: Leistung der Marktlokation) in dieser SG8 vorhanden",
    "106": "Wenn in dieser SG8 SEQ+Z01 SG10 CCI+++ZA6 (Prognosegrundlage der Marktlokation: Prognose auf Basis von Profilen) CAV+E02 (SLP/SEP) vorhanden",
    "107": "Wenn in derselben SG8 das SG10 CAV+SLS/ SES/ BIP/ GEP/ GAP/ SOP/ WNP/ WFP/ WAP vorhanden",
    "108": "Wenn in derselben SG8 (Netznutzungsabrechnungsdaten der Marktlokation) eine Gruppen-/Artikel-ID im PIA+Z02 (Gruppenartikel-ID / Artikel-ID), welche mit 1-08- 1/2/3/4/5 beginnt, vorhanden",
    "110": "Wenn SG10 CAV+LGS/ EGS/ BIL/ GEL/ GAL/ SOL/ WNL/ WFL / WAL vorhanden",
    "113": "Wenn es sich um eine Antwort auf die Bestellung einer Zählzeit handelt",
    "114": "Wenn das SG10 CCI+E03 (Spannungsebene der Marktlokation) CAV E06 (Niederspannung) in dieser SG vorhanden",
    "115": "(Spannungsebene der Marktlokation) CAV E06 (Niederspannung) in dieser SG vorhanden",
    "116": "Wenn das SG10 CCI+E03 (Spannungsebene der Marktlokation) CAV E04 (Hochspannung) in dieser SG vorhanden",
    "117": "Wenn das RFF+Z18 (Marktlokation) aus dieser SG8 auf das gleiche SG5 LOC+Z16 (Marktlokation), wie ein RFF+Z18 (Marktlokation) aus einer SG8 SEQ+Z01 (Daten der Marktlokation), in dem SG10 CCI+++ZA6 (Prognosegrundlage der Marktlokation: Prognose auf Basis von Profilen) CAV+E14 (TLP/TEP) vorhanden",
    "118": "Wenn in dieser SG8 SEQ+Z98 SG10 CCI+++ZA6 (Prognosegrundlage der Marktlokation: Prognose auf Basis von Profilen) CAV+E02 (SLP/ SEP) vorhanden",
    "119": "Wenn in der SG8 SEQ+Z01/ Z98 SG10 CCI+++ZA6 (Prognosegrundlage der Marktlokation: Prognose auf Basis von Profilen) CAV+E02 (SLP/SEP) vorhanden",
    "120": "SEQ+Z79 im PIA+5 (Erforderliches Produkt) DE7140 ein Produkt-Code genannt ist, der in der Codeliste der Konfigurationen im Kapitel 6 \"Produkte zur Bestellung / Änderung von Daten\" in der Spalte \"Code der Produkteigenschaft 9991000002272 („Lieferant“ (Empfänger der Vergütung zur Einspeisung)) befüllt ist.",
    "121": "Wenn in dem SEQ+Z03/ ZF5 (Zähleinrichtungsdaten ) das SG8 RFF+Z14 (Referenz auf das Smartmeter-Gateway) nicht vorhanden",
    "122": "Wenn in dieser SG8 SEQ+Z98 SG10 CCI+++E03 (Spannungsebene der Marktlokation) CAV+E06 (Niederspannung) vorhanden",
    "123": "Wenn noch mindestens eine weitere SG8 SEQ+Z20 (OBIS-Daten der Zähleinrichtung Smartmeter-Gateway) mit dem SG8 RFF+MG (Gerätenummer des Zählers) auf die gleiche Identifikation/Nummer des Gerätes referenziert",
    "124": "Wenn noch mindestens eine weitere SG8 SEQ+Z20 (OBIS-Daten der Zähleinrichtung Smartmeter-Gateway) mit derselben Zeitraum-ID aus dem DE1050 dieser SG8 mit dem SG8 RFF+MG (Gerätenummer des Zählers) auf die gleiche Identifikation/Nummer des Gerätes referenziert",
    "125": "Wenn in derselben SG8 SEQ+Z76/ ZC5/ ZC6 (Messstellenbetriebsabrechnungsdaten der Marktlokation) im DE4347 des PIA Z02 (Gruppenartikel-ID / Artikel-ID) vorhanden",
    "126": "Es ist der Wert einzutragen, der sich aus der Wiederholungshäufigkeit des SG6 RFF+Z49/ Z53 (Verwendungszeitraum der Daten: Gültige Daten/ Keine Daten) ergibt. Bedeutet: Das erste SG6 RFF+Z49/ Z53 hat somit die „1“, das zweite die „2“, das dritte die „3“ usw.",
    "127": "Es ist der Wert einzutragen, der sich aus der Wiederholungshäufigkeit des SG6 RFF+Z48/ Z55 (Verwendungszeitraum der Daten: Erwartete Daten/ Keine Daten erwartet) ergibt. Bedeutet: Das erste SG6 RFF+Z48/ Z55 hat somit die „1“, das zweite die „2“, das dritte die „3“ usw.",
    "128": "Es ist der Wert einzutragen, der sich aus der Wiederholungshäufigkeit des SG6 RFF+Z47/ Z54 (Verwendungszeitraum der Daten: Im System vorhandene Daten/ Im System keine Daten vorhanden) ergibt. Bedeutet: Das erste SG6 RFF+Z47/ Z54 hat somit die „1“, das zweite die „2“, das dritte die „3“ usw.",
    "129": "Innerhalb eines SG4 IDE müssen alle DE3225 der SG5 LOC+Z16 (Marktlokation) den identischen Wert enthalten",
    "130": "Wenn an Messlokation vorhanden",
    "131": "Wenn dieses DTM+Z25 (Verwendung der Daten ab) im SG6 RFF (Verwendungszeitraum der Daten) mit der Zeitraum ID \"1\" im DE1156 gekennzeichnet ist, muss das Datum in diesem DE2380 der direkt auf DTM+137 DE2380 (Nachrichtendatum) folgende Tag 0:00 Uhr oder ein älterer Tag als dieser 0:00 Uhr deutscher Zeit sein",
    "132": "Wenn dieses DTM+Z25 (Verwendung der Daten ab) im SG6 RFF (Verwendungszeitraum der Daten) mit der Zeitraum ID \"1\" im DE1156 gekennzeichnet ist, muss das Datum in diesem DE2380 der direkt auf DTM+137 DE2380 (Nachrichtendatum) folgende Tag 0:00 Uhr deutscher Zeit sein",
    "133": "Wenn an der übermittelten Marktlokation / Messlokation vorhanden",
    "134": "Wenn dieses DTM+Z25 (Verwendung der Daten ab) nicht im SG6 RFF+Z48/ Z55 (Verwendungszeitraum der Daten: Erwartete Daten/ Keine Daten erwartet) mit der Zeitraum ID \"1\" im DE1156 ist, muss das Datum dem DTM+Z26 (Verwendung der Daten bis) des SG6 RFF+Z48/ Z55 (Verwendungszeitraum der Daten: Erwartete Daten/ Keine Daten erwartet) mit der nächst niedrigeren Zeitraum ID im DE1156 entsprechen",
    "135": "Wenn dieses DTM+Z25 (Verwendung der Daten ab) nicht im SG6 RFF+Z47/ Z54 (Verwendungszeitraum der Daten: Im System vorhandene Daten/ Im System keine Daten vorhanden) mit der Zeitraum ID \"1\" im DE1156 ist, muss das Datum dem DTM+Z26 (Verwendung der Daten bis) des SG6 RFF+Z47/ Z54 (Verwendungszeitraum der Daten: Im System vorhandene Daten/ Im System keine Daten vorhanden) mit der nächst niedrigeren Zeitraum ID im DE1156 entsprechen",
    "136": "Wenn SG10 CCI+++E13 (Zählertyp) CAV+EHZ (elektronischer Haushaltszähler) in dieser SG8 vorhanden",
    "137": "Nicht bei Neuanlage",
    "138": "Wenn im selben QTY im",
    "139": "Wenn SG10 CAV+IVA (Individuelle Abstimmung) in dieser SG8 nicht vorhanden",
    "140": "Wenn im selben QTY im DE6063 Z34/Z35 (Zuschlag/Abschlag) vorhanden",
    "141": "Wenn SG10 CAV+MIW/ MPW/ MBW vorhanden",
    "142": "Wenn SG8 PIA+Z01+:Z04/ Z05 (Berechnung Tagesmitteltemperatur: vom Anbieter zur Verfügung gestellte - / Äquivalente Tagesmitteltemperatur) vorhanden",
    "143": "Wenn STS+7++ZX3 (Transaktionsgrund: Abrechnungsdaten BK-Abrechnung verbrauchender MaLo) vorhanden",
    "144": "Wenn STS+7++ZAN (Transaktionsgrund: Korrektur Abrechnungsdaten BK-Abrechnung verbrauchender MaLo) vorhanden",
    "145": "Wenn STS+7++ZX2 (Transaktionsgrund: Abrechnungsdaten BK-Abrechnung erzeugender MaLo) vorhanden",
    "146": "Wenn STS+7++ZA0 (Transaktionsgrund: Korrektur Abrechnungsdaten BK-Abrechnung erzeugender MaLo) vorhanden",
    "147": "Wenn in Anfrage vorhanden",
    "148": "Wenn in dieser SG8 im SG8 PIA+Z02 (Gruppenartikel-ID / Artikel-ID), die Artikel-ID 1-02-0-017/ 1-02-0-018 vorhanden",
    "149": "Wenn zwei SG8 SEQ+Z45 (Netznutzungsabrechnungsdaten der Marktlokation), mit derselben Zeitraum-ID im DE1050, mit Artikel-ID im SG8 PIA+Z02 (Gruppenartikel-ID / Artikel-ID), eine SG8 mit 1-02- 0-017 und eine mit 1-02-0-018 vorhanden",
    "150": "Wenn in dieser SG8 im SG8 PIA+Z02 (Gruppenartikel-ID / Artikel-ID), die Artikel-ID 1-02-0-002 vorhanden",
    "151": "Wenn bei der Bestellung ein Messprodukt der Codeliste der Konfigurationen aus dem Kapitel 4.4 mit dem Übertragungsweg \"aus dem SMGW\" bestellt wurde. Der Empfänger der Werte kann dadurch seine Firewall genau Konfigurieren",
    "152": "NAD+MR (Nachrichtenempfänger) in der Rolle LF",
    "153": "NAD+MR (Nachrichtenempfänger) in der Rolle LF",
    "156": "Wenn SG4 FTX+Z17 (Zieladresse URI) vorhanden",
    "157": "STS+7++ZG9/ZH1/ZH2 (Transaktionsgrund: Aufhebung einer zukünftigen Zuordnung wegen Auszug des Kunden / -wegen Stilllegung / -wegen aufgehobenem Vertragsverhältnis) nicht vorhanden",
    "158": "Wenn in derselben SG8 SEQ+Z57/ ZD9 (OBIS-Daten der Netzlokation) das PIA+5 (OBIS-Daten der Netzlokation) nicht vorhanden",
    "159": "Wenn in derselben SG8 SEQ+Z57/ ZD9 (OBIS-Daten der Netzlokation) das SG10 CCI+11 (OBIS-Daten der Netzlokation) nicht vorhanden",
    "160": "Wenn der Objektcode im RFF+Z33 (Referenz auf den Objektcode in der Lokationsbündelstruktur) im DE1154 derselben SG8 SEQ+Z58/ ZC9 / ZD0/ ZD6 (Zuordnung Lokation zum Objektcode des Lokationsbündels) in einem weiteren SG8 SEQ+Z58/ ZC9 / ZD0/ ZD6 (Zuordnung Lokation zum Objektcode des Lokationsbündels) mit der selben Zeitraum-ID sowie mit identischem Code im DE1229 vorhanden ist",
    "161": "Wenn SG4 STS+7++E03+ZW8 (Transaktionsgrundergänzung Fall 1) vorhanden",
    "162": "STS+7++E03+ZW8 (Transaktionsgrundergänzung Fall 1) vorhanden",
    "163": "(Transaktionsgrundergänzung Fall 1) vorhanden",
    "164": "Wenn SG4 STS+7++E03+ZX1 (Transaktionsgrundergänzung Fall 4) vorhanden",
    "165": "Wenn bekannt",
    "166": "Wenn vorhanden",
    "167": "Wenn SG5 LOC+Z21 (Tranche) vorhanden",
    "168": "Wenn in dieser SG8 im SG8 PIA+Z02 (Gruppenartikel-ID / Artikel-ID), die Artikel-ID 1-02-0-002/ 003/ 004 vorhanden",
    "169": "Wenn zwei SG8 SEQ+Z45 (Netznutzungsabrechnungsdaten der Marktlokation), mit derselben Zeitraum-ID im DE1050, mit Artikel-ID im SG8 PIA+Z02 (Gruppenartikel-ID / Artikel-ID), eine SG8 mit 1-02- 0-002 und eine mit 1-02-0- 003/004 vorhanden",
    "170": "Wenn Anschrift der Marktlokation vorhanden",
    "172": "Wenn im selben QTY im DE6063 Z37 (Kein Zu- und Abschlag) vorhanden",
    "173": "Wenn im RFF+Z33 (Referenz auf den Objektcode in der Lokationsbündelstruktur) das DE1156 (Fortlaufende Nummer eines Lokationsbündels im Geschäftsvorfall) in derselben SG8 SEQ+Z58/ ZC9/ ZD0/ ZD6 (Zuordnung Lokation zum Objektcode des Lokationsbündels) nicht vorhanden ist",
    "174": "Wenn im RFF+Z33 (Referenz auf den Objektcode in der Lokationsbündelstruktur) das DE1156 Fortlaufende Nummer eines Lokationsbündels im Geschäftsvorfall) in derselben SG8 SEQ+Z58/ ZC9/ ZD0/ ZD6 (Zuordnung Lokation zum Objektcode des Lokationsbündels) vorhanden ist",
    "175": "Wenn der Objektcode im RFF+Z33 (Referenz auf den Objektcode in der Lokationsbündelstruktur) im DE1154 derselben SG8 SEQ+Z58 (Zuordnung Lokation zum Objektcode des Lokationsbündels) in einem weiteren SG8 SEQ+Z58 mit derselben fortlaufenden Nummer vorhanden ist",
    "176": "Wenn in demselben Segment das DE1153 mit dem Code Z34 vorgelagerte Messlokation vorhanden ist",
    "177": "Wenn in demselben Segment das DE1153 mit dem Code Z35 vorgelagerte Netzlokation vorhanden ist",
    "178": "Wenn das LOC+Z18 (Netzlokation) vorhanden ist",
    "179": "Wenn der Objektcode im RFF+Z33 (Referenz auf den Objektcode in der Lokationsbündelstruktur) im DE1154 derselben SG8 SEQ+Z58/ ZC9 / ZD0/ ZD6 (Zuordnung Lokation zum Objektcode des Lokationsbündels) in einem weiteren SG8 SEQ+Z58/ ZC9 / ZD0/ ZD6 (Zuordnung Lokation zum Objektcode des Lokationsbündels) mit identischem Code im DE1229 vorhanden ist",
    "180": "Wenn im selben QTY im DE6063 Z46 (Kein Abschlag) vorhanden",
    "181": "Wenn der Versender datenschutzrechtliche Voraussetzungen geschaffen hat, um die Daten bereitstellen zu dürfen",
    "182": "Wenn SG10 CCI+++ZA6 (Prognosegrundlage der Marktlokation: Prognose auf Basis von Profilen) CAV+E14 (TLP/TEP) in dieser SG8 vorhanden",
    "183": "Wenn SG10 CCI+Z30++Z07 (Lieferrichtung: Verbrauch) in dieser SG8 vorhanden",
    "184": "Wenn in derselben SG8 SEQ+Z18 (Daten der Messlokation) ein CCI+Z01++Z82 (Verwendungsumfang: ID der prozessual behandelten Messlokation) vorhanden",
    "185": "Zulässig sind ausschließlich Codes aus der Spalte „Code“ der Codeliste der Verwendungszwecke (Kapitel 2), sofern in derselben Zeile sowohl in der Spalte „Lokation/MaLo“ als auch in der Spalte „Verwendbar für Marktrolle/NB“ jeweils ein „X“ gesetzt ist und die Aussagen der Spalte „Erläuterung“ zu dem im DE7140 genannten Produkt-Code desselben PIA passen",
    "186": "Zulässig sind ausschließlich Codes aus der Spalte „Code“ der Codeliste der Verwendungszwecke (Kapitel 2), sofern in derselben Zeile sowohl in der Spalte „Lokation/MaLo“ als auch in der Spalte „Verwendbar für Marktrolle/LF“ jeweils ein „X“ gesetzt ist und die Aussagen der Spalte „Erläuterung“ zur im DE7140 genannten Produkt-Code desselben PIA passen",
    "187": "Zulässig sind ausschließlich Codes aus der Spalte „Code“ der Codeliste der Verwendungszwecke (Kapitel 2), sofern in derselben Zeile sowohl in der Spalte „Lokation/MaLo“ als auch in der Spalte „Verwendbar für Marktrolle/ÜNB“ jeweils ein „X“ gesetzt ist und die Aussagen der Spalte „Erläuterung“ zur im DE7140 genannten Produkt-Code desselben PIA passen",
    "190": "Wenn in derselben SG8 SEQ+Z60/ ZG8/ ZG9/ ZE0 (Produkt-Daten der Netzlokation) PIA+5+9991000000721:Z 12 vorhanden",
    "191": "Wenn im SG4 IDE+Z01",
    "192": "Wenn SG4 STS+7++XXX+ZW4/ZAP (Transaktionsgrund / Ergänzung: Verbrauchende Marktlokation / ruhende Marktlokation) vorhanden",
    "193": "Wenn das SG10 CCI ZB5 (Spannungsebene der Summenzeitreihe) CAV E06 (Niederspannung) in dieser SG vorhanden",
    "194": "ZB5 (Spannungsebene der Summenzeitreihe) CAV E06 (Niederspannung) in dieser SG vorhanden",
    "195": "Wenn das SG10 CCI ZB5 (Spannungsebene der Summenzeitreihe) CAV E04 (Hochspannung) in dieser SG vorhanden",
    "196": "Wenn der Objektcode im RFF+Z33 (Referenz auf den Objektcode in der Lokationsbündelstruktur) im DE1154 derselben SG8 SEQ+Z58/ZC9/ZD0 (Zuordnung Lokation zum Objektcode des Lokationsbündels) in einem weiteren SG8 SEQ+Z58/ZC9/ZD0 mit derselben fortlaufenden Nummer im DE1156 des SG8 RFF, der selben Zeitraum-ID im DE1050 sowie identischen Codes im DE1229 des SG8 SEQ vorhanden ist",
    "197": "Wenn das RFF+Z18 (Marktlokation) aus dieser SG8 auf das gleiche SG5 LOC+Z16 (Marktlokation), wie ein RFF+Z18 (Marktlokation) aus einer SG8 SEQ+Z01 (Daten der Marktlokation), in dem SG10 CCI+++ZA6 (Prognosegrundlage der Marktlokation: Prognose auf Basis von Profilen) CAV+E02 (SLP/SEP) vorhanden",
    "198": "Wenn SG4 ∧ [570] STS+7++E03(Transaktionsgrund: Wechsel) vorhanden",
    "199": "Wenn in der SG8 SEQ+Z01/ SG10 CCI+++ZA6 (Prognosegrundlage der Marktlokation: Prognose auf Basis von Profilen) mit identischer Zeitraum-ID im DE1050 CAV+E02 (SLP/SEP) vorhanden",
    "201": "Wenn die Marktlokation / Tranche nicht den ganzen Bilanzierungsmonat dem gleichen Tupel aus Bilanzkreis, Zeitreihentyp, Spannungsebene und Lieferant zugeordnet ist",
    "202": "Wenn SG8 SEQ+Z78 RFF+Z39 (Keine standardisierte Lokationsbündelstruktur vorhanden), mit identischer Zeitraum-ID im DE1050 wie im DE3224 dieses Segments",
    "203": "Wenn STS+7++E06 / Z39 / ZC6 / ZC7/ ZT6/ ZT7 / Z02 / ZZD vorhanden",
    "204": "Wenn im SG8+SEQ+Z03/ ZA3/ ZA4 (Zähleinrichtungsdaten) mit der selben Zeitraum-ID im SG8 SEQ DE1050, sowie identischer Qualität im DE1229 der SG8 SEQ für die in diesem RFF DE1154 genannte Gerätenummer eines Zählers das RFF+Z14 (Referenz auf das Smartmeter-Gateway) nicht vorhanden ist",
    "205": "Wenn SG5 LOC+Z19 (Steuerbare Ressource) vorhanden",
    "206": "Wenn SG4 STS+7++ZG5 (Transaktionsgrund: Aufhebung der zukünftigen Zuordnung aufgrund § 38 EEG 2014 bzw. § 21b Abs. 1 Nr. 2 EEG 2017) nicht vorhanden",
    "209": "Wenn im selben Segment im DE2379 der für die Bedingung \"Wenn im selben Segment im DE2379 der Code 106 vorhanden ist\" anstatt der [158] jedoch die",
    "210": "Wenn SG10 CCI+++ZA6 (Prognose auf Basis von Profilen) in dieser SG8 vorhanden",
    "212": "Wenn im selben SG12 NAD DE3124 nicht vorhanden",
    "213": "Wenn SG12 NAD+Z09 (Kunde des Lieferanten) vorhanden",
    "215": "Wenn in derselben SG8 (Zähleinrichtungsdaten ) SG10 CCI+++E13 CAV+MME (Zählertyp: mME) vorhanden",
    "216": "Wenn CCI+++Z88 (Netznutzung) CAV+Z74:::Z08 (Netznutzungsvertrag: Direkter Vertrag zwischen Kunden und NB) vorhanden",
    "217": "Wenn SG6 RFF+Z49 (Verwendungszeitraum der Daten: \"Gültige Daten\") vorhanden",
    "219": "Wenn SG12 NAD+Z65 (Informativer Kunde des Lieferanten) vorhanden",
    "220": "Wenn SG8 SEQ+Z01/ Z98 (Daten der Marktlokation) SG10 CCI+Z30++Z06 (Lieferrichtung: Erzeugung) in dieser SG8 vorhanden",
    "221": "STS+7++E02 (Transaktionsgrund: Einzug in Neuanlage) nicht vorhanden",
    "223": "Wenn das RFF+Z18 (Marktlokation) aus dieser SG8 auf das gleiche SG5 LOC+Z16 (Marktlokation), wie ein RFF+Z18 (Marktlokation) aus einer SG8 SEQ+Z01 (Daten der Marktlokation) verweist, und dort das SG10 CCI+Z30++Z06 (Lieferrichtung: Erzeugung) vorhanden ist",
    "224": "Wenn kein SG8 SEQ+ZE7 (Informative Daten der Tranche) auf die gleiche Marktlokation-ID mit dem RFF+Z18 (Marktlokation) referenziert wie dieses SG8 SEQ+Z98 (Informative Daten der Marktlokation)",
    "227": "Wenn im SG8 SEQ+Z98 (Daten der Marktlokation) das SG10 CCI+++ZA6 (Prognosegrundlage der Marktlokation: Prognose auf Basis von Profilen) CAV+E14 (TLP/TEP) vorhanden",
    "229": "Wenn der Objektcode im RFF+Z33 (Referenz auf den Objektcode in der Lokationsbündelstruktur) im DE1154 derselben SG8 SEQ+Z58/ ZC9/ ZD0/ ZD6 (Zuordnung Lokation zum Objektcode des Lokationsbündels) in einem weiteren SG8 SEQ+Z58/ ZC9/ ZD0/ ZD6 (Zuordnung Lokation zum Objektcode des Lokationsbündels) und identischer Zeitraum-ID im DE1050 sowie identischen Codes im DE1229 des SG8 SEQ vorhanden ist",
    "232": "Wenn SG10 CCI+++Z83 (Messtechnische Einordnung der Marktlokation) CAV+Z52 (iMS) vorhanden",
    "233": "Wenn MP-ID in SG2 NAD+MR (Nachrichtenempfänger) in der Rolle NB",
    "234": "Wenn SG10 CCI+++Z83 (Messtechnische Einordnung der Marktlokation) CAV+Z53 (kME/ mME) vorhanden",
    "237": "Wenn in derselben SG8 im DE7140 des PIA+Z02 (Gruppenartikel-ID / Artikel-ID) eine Gruppenartikel-ID / Artikel-ID mit 1-06 (entspricht Entgelte des Messstellenbetriebs bei kME) beginnt",
    "238": "Wenn SG4 IDE+24 (Vorgang) nicht vorhanden",
    "239": "Wenn in derselben SG10 das CCI+Z17 (Stromverbrauchsart) im CAV+Z65 (Wärme/Kälte) vorhanden",
    "240": "Wenn SG8 SEQ+Z01 (Daten der Marktlokation) CCI+Z22++Z91 (Veräußerungsform der erzeugenden Marktlokation:: Marktprämie) vorhanden",
    "241": "Wenn MP-ID in SG2 NAD+MR (Nachrichtenempfänger) in der Rolle MSB",
    "242": "Wenn mehr als ein SG8 (Referenz auf die Lokationsbündelstruktur) mit der selben Zeitraum-ID im DE1050 vorhanden",
    "243": "Wenn SG10 CCI+6++ZA8 (Aggreg.verantw. NB) in dieser SG8 vorhanden",
    "244": "Wenn SG10 CCI+6++ZA9 (Aggreg.verantw. ÜNB) in dieser SG8 vorhanden",
    "248": "Wenn die Inbetriebnahme der verbrauchenden Marktlokation innerhalb der letzten drei Jahre war und die Energie der Marktlokation mit iMS ausgestatteten Messlokationen erfolgt",
    "249": "Innerhalb eines SG4 IDE müssen alle DE1131 der SG4 STS+E01 (Status der Antwort) den identischen Wert enthalten",
    "251": "Wenn MP-ID in SG2 NAD+MS (Nachrichtensender) in der Rolle BIKO",
    "252": "Wenn DE0068 vorhanden",
    "253": "Wenn SG4 STS+E01++ZC9 (Ablehnung (keine Zuordnung möglich)) nicht vorhanden",
    "254": "Es ist der Code \"AUA\" einzutragen",
    "255": "Wenn Marktlokation am Redispatch 2.0 teilnimmt",
    "256": "Wenn in derselben SG8 SEQ (OBIS-Daten der Zähleinrichtung / Smartmeter-Gateway) das PIA+5+1-b?:1.8.e / 1- b?:2.8.e vorhanden",
    "257": "Wenn in derselben SG8 SEQ (OBIS-Daten der Marktlokation) das PIA+5+1- b?:1.9.e vorhanden",
    "258": "Wenn in dieser SG8 SEQ+Z01 (Daten der Marktlokation) SG10 CCI+Z30++Z07 (Verbrauch) vorhanden",
    "259": "Wenn in diesem PIA der Code im DE7140 mit 1-01, 1-03, 1-05 enthalten ist",
    "261": "Wenn in diesem PIA der Code im DE7140 mit 1-07-1/2, 1-10-1/2/4/5/6/7/8/9, 1-11-1 beginnt",
    "262": "Wenn Produkt an der Marktlokation vorhanden ist",
    "263": "Wenn SG8 SEQ+Z01 (Daten der Marktlokation) SG10 CCI+Z30++Z07 (Verbrauch) vorhanden",
    "265": "Wenn im SG8 SEQ+Z01/ Z98 (Daten der Marktlokation) das SG10 CCI+++ZA6 (Prognosegrundlage der Marktlokation: Prognose auf Basis von Profilen) CAV+Z36 (TEP m. Referenzmessung) vorhanden",
    "266": "Wenn im SG8 SEQ+Z01 (Daten der Marktlokation) mit identischer Zeitraum-ID im SG8 SEQ+Z01 DE1050 wie in dieser SG8 SEQ, das SG10 CCI+++ZA6 (Prognosegrundlage der Marktlokation: Prognose auf Basis von Profilen) CAV+Z36 (TEP m. Referenzmessung) vorhanden",
    "267": "Wenn SG8 SEQ+Z38 (Referenzprofildaten) nicht vorhanden",
    "268": "Wenn der Code im DE3207 in der \"EDI@Energy Codeliste der europäischen Ländercodes\" in der Spalte \"PLZ vorhanden\" ein \"X\" aufgeführt ist",
    "269": "Es sind alle OBIS-Kennzahlen gem. EDI@Energy Codeliste der OBIS-Kennzahlen und Medien für den deutschen Energiemarkt Kap.3 anzugeben welche an der Tranche erforderlich sind",
    "270": "Wenn in diesem PIA der Code im DE7140 mit 1-02, 1- 04, 1-06, 1-09 beginnt",
    "271": "Wenn das RFF+Z50 (Termine der Marktlokation) aus dieser SG6 (Termine der Marktlokation) auf das gleiche SG5 LOC+Z16 (Marktlokation), wie ein RFF+Z18 (Marktlokation) aus einer SG8 SEQ+Z01 (Daten der Marktlokation), in der SG10 CCI+++Z83 (Messtechnische Einordnung der Marktlokation) CAV+Z53 (kME/ mME) vorhanden ist, referenziert",
    "272": "Wenn im selben Segment im DE2379 der genannten Änderungshistorieneintrag war für die Bedingung \"Wenn im selben Segment im DE2379 der Code 106 vorhanden ist\" anstatt der [158] jedoch die",
    "273": "Wenn in derselben SG8 SEQ+Z20 (OBIS-Daten der Zähleinrichtung / Smartmeter-Gateway) das PIA+5+1-b?:1.8.e / 1- b?:2.8.e / 1-b?:3.8.e / 1- b?:4.8.e / 1-b?:5.8.e / 1- b?:6.8.e / 1-b?:7.8.e / 1- b?:8.8.e / 1-b?:1.8.63 vorhanden",
    "274": "Zulässig sind ausschließlich Codes aus der Spalte „Code“ der Codeliste der Verwendungszwecke (Kapitel 2), sofern in derselben Zeile sowohl in der Spalte „Lokation/ Tranche“ als auch in der Spalte „Verwendbar für Marktrolle/NB“ jeweils ein „X“ gesetzt ist und die Aussagen der Spalte „Erläuterung“ zur im DE7140 genannten Produkt-Code desselben PIA passen",
    "275": "Zulässig sind ausschließlich Codes aus der Spalte „Code“ der Codeliste der Verwendungszwecke (Kapitel 2), sofern in derselben Zeile sowohl in der Spalte „Lokation/Tranche“ als auch in der Spalte „Verwendbar für Marktrolle/LF“ jeweils ein „X“ gesetzt ist und die Aussagen der Spalte „Erläuterung“ zur im DE7140 genannten Produkt-Code desselben PIA passen",
    "276": "Zulässig sind ausschließlich Codes aus der Spalte „Code“ der Codeliste der Verwendungszwecke (Kapitel 2), sofern in derselben Zeile sowohl in der Spalte „Lokation/ Tranche“ als auch in der Spalte „Verwendbar für Marktrolle/ÜNB“ jeweils ein „X“ gesetzt ist und die Aussagen der Spalte „Erläuterung“ zur im DE7140 genannten Produkt-Code desselben PIA passen Löschen wurde im Rahmen des Fehler (29.06.2026) Umbaus in der Version UTILMD MIG S2.2 der Verwendungszwecke von den einzelnen SG10 direkt in das PIA vergessen und nun nachgeholt nicht vorhanden",
    "279": "Wenn STS+7++xxx+ZW4 / ZAP (Transaktionsgrundergänzung verbrauchende Marktlokation / ruhende Marktlokation) vorhanden",
    "280": "Nur MP-ID aus Sparte Strom",
    "282": "Wenn in diesem PIA der Code im DE7140 1-01-6-005, 1- 01-9-001/002, 1-07-3- 001, 1- 08-1-001, 1-08- 3-001, 1-08-4- 001/002/003/004, 1- 10-3-001 enthalten ist",
    "284": "Erlaubte Codes aus der Codeliste der Gruppenartikel- und Artikel-ID sind in der Spalte UTILMD/Codeverwendung mit X gekennzeichnet",
    "285": "Wenn in diesem PIA der Code im DE7140 mit 1-08-3- AGS angegeben ist",
    "286": "Wenn in diesem PIA der Code im DE7140 mit 1-08- 1/2/4/5-AGS-KG",
    "287": "Erlaubte Codes aus der PRICAT BGM+ Z70 (Preisblatt Netznutzung) des verantwortlichen NB",
    "288": "Wenn in derselben SG8 (OBIS-Daten der Marktlokation) das PIA+5+1- b?:2.9.e vorhanden",
    "291": "Wenn in derselben SG8 (Zuordnung Lokation zum Objektcode des Lokationsbündels) das RFF+Z37 vorhanden",
    "292": "Es sind nur die Produkt-Codes erlaubt, die in der Codeliste der Konfigurationen im Kapitel 6.1 \"Anmeldung einer Zuordnung des LFN (UTILMD)\" in der Spalte \"Anmeldung einer Zuordnung des LFN (UTILMD) \" mit dem entsprechenden Prüfidentifikator des Anwendungsfalls gekennzeichnet ist.",
    "293": "Wenn SG5 LOC+Z22 (ruhende Marktlokation) vorhanden",
    "294": "Wenn SG5 LOC+Z18 (Netzlokation) vorhanden",
    "295": "Wenn SG5 LOC+Z15 (MaBiS-Zählpunkt) nicht vorhanden",
    "296": "Wenn SG5 LOC+Z20 (Technische Ressource) vorhanden",
    "297": "Wenn mehr als eine SG8 SEQ+Z02/ ZE3 (OBIS-Daten der Marktlokation) mit einer OBIS-Kennzahl für Energiemenge im PIA+5, mit gleicher Zeitraum-ID und identischem Code im DE1229 des SG8 SEQ+Z02/ZA1/ZA2 (OBIS-Daten der Marktlokation) vorhanden",
    "300": "Wenn SG8 SEQ+Z15/ ZE7 (Daten der Tranche) nicht vorhanden",
    "301": "Wenn BGM+E03 (Änderungsmeldung) vorhanden",
    "302": "Wenn SG8 SEQ+Z08 (Profilschardaten) nicht vorhanden",
    "303": "Wenn SG8 SEQ+Z21 (Profildaten) nicht vorhanden",
    "304": "Wenn SG8 SEQ+Z22 (Daten der Summenzeitreihe) vorhanden",
    "305": "Wenn SG8 SEQ+Z24 (Daten der Überführungszeitreihe) vorhanden",
    "306": "Wenn SG5 LOC+Z22 (ruhende Marktlokation) mit derselben Zeitraum-ID im DE3224 vorhanden wie in dieser SG8 im DE1050 (Referenz auf Zeitraum-ID) des SEQ+Z58",
    "307": "Wenn SG5 LOC+Z22 (ruhende Marktlokation) mit derselben Zeitraum-ID im DE3224 nicht vorhanden wie in dieser SG8 im DE1050 (Referenz auf Zeitraum-ID) des SEQ+Z58",
    "309": "Wenn SG5 LOC+Z22 (ruhende Marktlokation) nicht vorhanden",
    "314": "Es sind alle OBIS-Kennzahlen gem. Codeliste der OBIS-Kennzahlen und Medien Kapitel 3 anzugeben welche an der Marktlokation erforderlich sind. Der Mindestumfang der OBIS-Kennzahlen ergibt sich aus den genannten Messprodukt-Codes dem Kapitel 5.1 des Dokumentes Codeliste der Konfigurationen",
    "315": "Wenn BGM+Z88 (Datenclearing) vorhanden",
    "316": "Wenn in derselben SG8 das RFF+Z14 (Smartmeter-Gateway) nicht vorhanden",
    "317": "Es ist derselbe Wert wie im DE2380 von DTM+92 (Datum Vertragsbeginn) einzutragen",
    "318": "Es ist derselbe Wert wie im DE2380 von DTM+93 (Datum Vertragende) einzutragen",
    "323": "Es sind alle OBIS-Kennzahlen gem. EDI@Energy Codeliste der OBIS-Kennzahlen und Medien für den deutschen Energiemarkt Kap. 3. anzugeben, welche an der Zähleinrichtung genutzt werden. Der Mindestumfang der OBIS-Kennzahlen ergibt sich aus den genannten Messprodukt-Codes dem Kap. 5.1 des Dokumentes \"Codeliste der Konfigurationen\"",
    "327": "Wenn die Zeitraum-ID im DE1050 dieser SG8 SEQ, welche mit der Zeitraum-ID einer SG6 RFF+Z47/Z48/Z49 (Verwendungszeitraum der Daten) identisch ist und in deren SG das SG6 DTM+Z25 (Verwendung der Daten ab) im DE2380 ≥ 202212312300?+00 ist",
    "328": "Wenn die Marktlokation stillgelegt wird X",
    "329": "Wenn in dieser SG4 IDE+24 das STS+E01++A03: E_0096 bzw. A04:E_0097 (Status der Antwort) nicht vorhanden",
    "332": "Wenn im SG8 SEQ+Z01 (Daten der Marktlokation) mit identischer Zeitraum-ID im DE1050 wie in dieser SG8, das SG10 CCI+6++ZA9 (Aggreg. verantw. ÜNB) nicht vorhanden",
    "333": "Wenn in diesem RFF \"Referenz auf die Lokationsbündelstruktur\" im DE1153 der Code Z31 \"Lokationsbündelstruktur \" vorhanden ist",
    "334": "Nur MP-ID aus Sparte Gas",
    "335": "Wenn in dieser SG8 im SEQ+Z58 (Zuordnung Lokation zum Objektcode des Lokationsbündels) im DE1050 eine Zeitraum-ID angegeben wird, wie in einer SG8 SEQ+Z78 RFF+Z31 (Referenz auf die Lokationsbündelstruktur) im DE1154",
    "336": "Wenn in Änderungsmeldung gefüllt",
    "337": "Wenn SG10 CCI+++ZB4 (Bezeichnung der Summenzeitreihe) CAV+Z95/ Z96 vorhanden",
    "338": "Wenn CCI+++ZB4 (Bezeichnung der Summenzeitreihe) CAV+Z95/ Z96/ Z97/ Z99/ ZA1/ ZA3/ ZA4/ZG7 vorhanden",
    "339": "Wenn CCI+++ZB4 (Bezeichnung der Summenzeitreihe) CAV+Z97/ Z98/ Z99/ ZA0/ ZA1/ ZA2/ ZA3/ ZA6/ ZG7 vorhanden",
    "340": "Wenn CCI+++ZB4 (Bezeichnung der Summenzeitreihe) CAV+Z95/ Z97/ Z98/ Z99/ ZA1/ ZA2/ ZA3/ ZA4/ ZA5/ ZA6 vorhanden",
    "341": "(Bezeichnung der Summenzeitreihe) CAV+Z95/ Z97/ Z98/ Z99/ ZA1/ ZA2/ ZA3/ ZA4/ ZA5/ ZA6 vorhanden",
    "342": "Wenn aktiver MaBiS-ZP für den Betrachtungszeitraum vorhanden",
    "344": "Wenn in dieser SG8 das SG10 CCI+++ZB4 (Bezeichnung der Summenzeitreihe) CAV+ZF1 (Netzgangzeitreihe (NGZ)) vorhanden",
    "345": "Wenn SG5 LOC+Z17 (Messlokation) vorhanden",
    "346": "Wenn SG10 CCI+++E13 (Zählertyp) CAV+MME (mME) in dieser SG8 vorhanden",
    "347": "Wenn SG5 LOC+Z16 (Marktlokation) nicht vorhanden",
    "348": "Wenn SG5 LOC+Z21 (Tranche) nicht vorhanden",
    "349": "Wenn SG5 LOC+Z17 (Messlokation) nicht vorhanden",
    "350": "Wenn SG8 SEQ+Z78/ZD5 RFF+Z31 (Referenz auf die Lokationsbündelstruktur) vorhanden",
    "351": "Wenn SG4 STS+E01++A04/ A05 /A13 /A14 (Status der Antwort) vorhanden",
    "352": "Wenn SG4 STS++A05/ A06/ A14 /A15 (Status der Antwort) vorhanden",
    "353": "Zulässig sind ausschließlich Codes aus der Spalte „Code“ der Codeliste der Verwendungszwecke (Kapitel 2), sofern in derselben Zeile sowohl in der Spalte „Lokation/NeLo“ als auch in der Spalte „Verwendbar für Marktrolle/NB“ jeweils ein „X“ gesetzt ist und die Aussagen der Spalte „Erläuterung“ zur im DE7140 genannten OBIS-Kennzahl desselben PIA passen",
    "354": "Zulässig sind ausschließlich Codes aus der Spalte „Code“ der Codeliste der Verwendungszwecke (Kapitel 2), sofern in derselben Zeile sowohl in der Spalte „Lokation/NeLo“ als auch in der Spalte „Verwendbar für Marktrolle/LF“ jeweils ein „X“ gesetzt ist und die Aussagen der Spalte „Erläuterung“ zur im DE7140 genannten OBIS-Kennzahl desselben PIA passen",
    "355": "Wenn SG4 STS+E01++A45 (Status der Antwort) vorhanden",
    "356": "Wenn SG4 ∧ [2061] STS+E01++A50 (Status der Antwort) vorhanden",
    "357": "Wenn SG4 STS+E01++A03/ A09/ A12/ A17 (Status der Antwort) vorhanden",
    "358": "Wenn SG4 STS+E01++A06 (Status der Antwort) vorhanden",
    "359": "Es sind nur Antwortcodes aus dem Cluster Ablehnung erlaubt",
    "360": "Es sind nur Antwortcodes aus dem Cluster Zustimmung erlaubt",
    "363": "Wenn SG4 ∧ [566] STS+E01++A50 (Status der Antwort) vorhanden",
    "365": "Wenn in dieser SG4 IDE+24 das STS+E01++A04:E_0047/E_001 4 bzw. A03:E_0049/E_0004 (Status der Antwort) nicht vorhanden",
    "366": "Bis auf den Code A30 sind alle Codes aus EBD E_0624 im Cluster Ablehnung erlaubt",
    "367": "Wenn SG4 ∧ [643] STS+E01++A05/ A14 (Status der Antwort) vorhanden",
    "368": "Bis auf den Code A41 sind alle Codes aus EBD E_0624 im Cluster Ablehnung erlaubt",
    "370": "Wenn SG10 CAV+TLS/TES/BIT/GET/GAT/SO T/WNT/WFT/WAT",
    "371": "Wenn SG8 SEQ+Z38 (Referenzprofildaten) nicht vorhanden",
    "372": "Wenn SG10 CAV+TES/BIT/GET/GAT/SOT/ WNT/WFT/WAT vorhanden",
    "373": "Wenn ein Referenzprofil an der Marktlokation vorhanden ist",
    "375": "Für die ID im SG5 LOC+Z15 (MaBiS-Zählpunkt) DE3225, wenn SG8+Z24 (Daten der Überführungszeitreihe) nicht vorhanden",
    "376": "(MaBiS-Zählpunkt) nicht vorhanden",
    "377": "Wenn SG10 CCI+15++Z21 (Überführungszeitreihentyp) CAV+AUS vorhanden",
    "378": "Wenn SG10 CCI+15++Z21 (Überführungszeitreihentyp) CAV+AUS nicht vorhanden",
    "379": "Wenn SG10 CCI+15++Z21 (Überführungszeitreihentyp) CAV+ Code für EEG-Überführungszeitreihen (ausgenommen AU1) vorhanden",
    "380": "Wenn SG10 CCI+15++Z21 (Überführungszeitreihentyp) CAV+AUS/AU1 vorhanden",
    "381": "Zulässig sind ausschließlich Codes aus der Spalte „Code“ der Codeliste der Verwendungszwecke (Kapitel 2), sofern in derselben Zeile sowohl in der Spalte „Lokation/MaLo“ als auch in der Spalte „Verwendbar für Marktrolle/NB“ jeweils ein „X“ gesetzt ist und die Aussagen der Spalte „Erläuterung“ zur im DE7140 genannten OBIS-Kennzahl desselben PIA passen",
    "382": "Zulässig sind ausschließlich Codes aus der Spalte „Code“ der Codeliste der Verwendungszwecke (Kapitel 2), sofern in derselben Zeile sowohl in der Spalte „Lokation/MaLo“ als auch in der Spalte „Verwendbar für Marktrolle/LF“ jeweils ein „X“ gesetzt ist und die Aussagen der Spalte „Erläuterung“ zur im DE7140 genannten OBIS-Kennzahl desselben PIA passen",
    "383": "Zulässig sind ausschließlich Codes aus der Spalte „Code“ der Codeliste der Verwendungszwecke (Kapitel 2), sofern in derselben Zeile sowohl in der Spalte „Lokation/MaLo“ als auch in der Spalte „Verwendbar für Marktrolle/ÜNB“ jeweils ein „X“ gesetzt ist und die Aussagen der Spalte „Erläuterung“ zur im DE7140 genannten OBIS-Kennzahl desselben PIA passen",
    "384": "Wenn in derselben SG8 SG10 CCI+Z37++ZD1 (Basis zur Bildung der Tranchengröße) (Prozentual) vorhanden",
    "386": "Wenn mehr als eine SG8 SEQ+Z02/ ZE3 (OBIS-Daten der Marktlokation) mit einer OBIS-Kennzahl für Energiemenge im PIA+5 vorhanden",
    "387": "Wenn in derselben SG8 (OBIS-Daten der Marktlokation) eine OBIS-Kennzahl für Energiemenge im PIA+5 vorhanden und es sich lt. Codeliste OBIS um eine OBIS mit zugeordneter Zählzeit handelt (Tarif: e = 1 .. 62)",
    "388": "Segmentgruppe ist mindesten einmal für jede Zeitraum-ID aus dem DE1156 der SG6 RFF+Z49 (Verwendungszeitraum der Daten: \"Gültige Daten\") anzugeben, wenn in diesem Zeitraum Blindarbeit bzw. - leistung an der Netzlokation zu erfassen ist.",
    "391": "Wenn in derselben SG8 SEQ+Z20 (OBIS Daten der Zähleinrichtung / Smartmeter-Gateway) eine OBIS-Kennzahl für Zählerstand im PIA+5 vorhanden und es sich lt. Codeliste OBIS um eine OBIS mit zugeordneter Zählzeit handelt (Tarif: e = 1 .. 62)",
    "392": "Wenn in diesem PIA der Code im",
    "393": "Wenn in diesem PIA der Code im Format n1-n2-n1-n3 angegeben ist",
    "394": "Wenn in diesem PIA der Code im Format n1-n2-n1-n8- n2 angegeben ist",
    "395": "Wenn in diesem PIA der Code im Format n1-n2-n1-n8 angegeben ist",
    "397": "Wenn in diesem PIA der Code im DE7140 mit 1-08-1/1- 08-4 beginnt",
    "398": "Wenn in diesem PIA der Code im DE7140 mit 1-08-2/1- 08-5 beginnt",
    "399": "Wenn im SG8 SEQ+Z78 mit identischer Zeitraum-ID im DE1050 wie im DE3224 dieses Segments, das RFF+Z31 (Lokationsbündelstruktur) im DE1153 der Code Z31 (Lokationsbündelstruktur) vorhanden, und im DE1154 (ID der Lokationsbündelstruktur) ein Code vorhanden ist welcher nicht der Code 9992 00000 001 8 ist.",
    "401": "Wenn dieses DTM+Z25 (Verwendung der Daten ab) nicht im SG6 RFF+Z49/ Z53 (Verwendungszeitraum der Daten: Gültige Daten/ Keine Daten) mit der Zeitraum ID \"1\" im DE1156 ist, muss das Datum dem DTM+Z26 (Verwendung der Daten bis) des SG6 RFF+Z49/ Z53 (Verwendungszeitraum der Daten: Gültige Daten/ Keine Daten) mit der nächst niedrigeren Zeitraum ID im DE1156 entsprechen",
    "402": "Wenn in derselben ∧ [420] SG8 (OBIS-Daten der Zähleinrichtung / Smartmeter-Gateway) eine OBIS-Kennzahl der Werteart \"Zählerstand\" im PIA+5 vorhanden",
    "403": "Wenn nicht dieselbe MP-ID in SG2 NAD+MS (Nachrichtensender) und im SG8 SEQ+Z01 (Daten der Marktlokation) SG10 CCI+++ZB3 (Zugeordnete Marktpartner) CAV+Z91 (Messtellenbetreiber) vorhanden",
    "404": "Wenn nicht dieselbe MP-ID in SG2 NAD+MR (Nachrichtenempfänger) und im SG8 SEQ+Z01/ Z98 (Daten der Marktlokation) SG10 CCI+++ZB3 (Zugeordnete Marktpartner) CAV+Z91 (Messtellenbetreiber) vorhanden",
    "412": "Es sind ausschließlich Konfigurationsprodukt -Codes der \"EDI@Energy Codeliste der Konfigurationen\" aus Kapitel 4.2 Konfigurationsprodukte Leistungskurvendefinition erlaubt",
    "417": "Wenn für den erforderlichen Wert keine Zählzeit benötigt wird",
    "420": "Wenn in dieser SG8 das RFF+Z14 (Smartmeter-Gateway) vorhanden ist",
    "421": "Wenn in dieser SG8 das SG10 CCI+Z39 (Zugeordnete Zählzeitdefinition) vorhanden ist",
    "422": "Zulässig sind ausschließlich Codes aus der Spalte „Code“ der Codeliste der Verwendungszwecke (Kapitel 2), sofern in derselben Zeile sowohl in der Spalte „Lokation/Tranche“ als auch in der Spalte „Verwendbar für Marktrolle/NB“ jeweils ein „X“ gesetzt ist und die Aussagen der Spalte „Erläuterung“ zur im DE7140 genannten OBIS-Kennzahl desselben PIA passen",
    "423": "Zulässig sind ausschließlich Codes aus der Spalte „Code“ der Codeliste der Verwendungszwecke (Kapitel 2), sofern in derselben Zeile sowohl in der Spalte „Lokation/Tranche“ als auch in der Spalte „Verwendbar für Marktrolle/LF“ jeweils ein „X“ gesetzt ist und die Aussagen der Spalte „Erläuterung“ zur im DE7140 genannten OBIS-Kennzahl desselben PIA passen",
    "424": "Zulässig sind ausschließlich Codes aus der Spalte „Code“ der Codeliste der Verwendungszwecke (Kapitel 2), sofern in derselben Zeile sowohl in der Spalte „Lokation/Tranche“ als auch in der Spalte „Verwendbar für Marktrolle/ÜNB“ jeweils ein „X“ gesetzt ist und die Aussagen der Spalte „Erläuterung“ zur im DE7140 genannten OBIS-Kennzahl desselben PIA passen",
    "425": "Messprodukt-Code aus den Kapitel 2.1 \"Standard-Messprodukte der Marktlokation\" der Codeliste der Konfigurationen",
    "426": "Messprodukt-Code aus den Kapitel 2.2 \"Standard-Messprodukte der Tranche\" der Codeliste der Konfigurationen",
    "427": "Messprodukt-Code aus den Kapitel 2.3 \"Standard-Messprodukte der Messlokation\" der Codeliste der Konfigurationen",
    "428": "Wenn in derselben SG8 SEQ+Z27/ ZE2 (Erforderliches Messprodukt der Marktlokation) das PIA+5 DE7140 mit einem Messprodukt aus Codeliste der Konfigurationen Kapitel 2.1.1 Standard-Messprodukt der Marktlokation mit der Wahlmöglichkeit der Zuordnung einer Zählzeit vorhanden ist",
    "429": "Wenn in derselben SG8 SEQ+Z19/ ZF4 (Erforderliches Messprodukt der Messlokation) das PIA+5 DE7140 mit einem Messprodukt aus Codeliste der Konfigurationen Kapitel 2.3.1 Standard-Messprodukt der Messlokation mit der Wahlmöglichkeit der Zuordnung einer Zählzeit vorhanden ist",
    "437": "Wenn in dieser SG4 das STS+E01++A04 / A23 (Status der Antwort) vorhanden",
    "438": "Wenn im selben CCI im DE7059 der Code Z39 (Code der Zählzeit) vorhanden ist",
    "440": "Wenn in demselben RFF der Code Z35 (vorgelagerte Netzlokation) im DE1153 vorhanden",
    "441": "Wenn im SG8+SEQ+Z03/ ZF5 (Zähleinrichtungsdaten ) für die in diesem RFF DE1154 genannte Gerätenummer eines Zählers das RFF+Z14 (Referenz auf das Smartmeter-Gateway) nicht vorhanden ist",
    "442": "Wenn in demselben RFF der Code Z34 (vorgelagerte Messlokation) im DE1153 vorhanden",
    "444": "Wenn in derselben SG8 (Produkt-Daten der Netzlokation) das PIA+5 (Produkt-Daten der Netzlokation) nicht vorhanden",
    "445": "Wenn in derselben SG8 (Produkt-Daten der Netzlokation) das SG10 CCI+11 (Details zum Produkt der Netzlokation) nicht vorhanden",
    "446": "Wenn in derselben SG8 das CCI+Z17 (Stromverbrauchsart) vorhanden",
    "447": "Wenn in derselben SG8 das CCI+Z50 (Stromerzeugungsart) vorhanden",
    "448": "Wenn in derselben SG8 das CCI+Z56 (Speicher) vorhanden",
    "449": "Wenn in derselben SG8 das SG10 CCI+6++ZA9 CAV=ZG3 (Aggreg.verantw. ÜNB und Lokation im Regelbetrieb) vorhanden",
    "450": "Wenn in demselben RFF der Code Z32 (Netzlokation) im DE1153 vorhanden",
    "451": "Wenn in demselben RFF der Code Z18 (Marktlokation) im DE1153 vorhanden",
    "452": "Wenn in demselben RFF der Code Z19 (Messlokation) im DE1153 vorhanden",
    "453": "Wenn bei der Bestellung ein Messprodukt der Codeliste der Konfigurationen aus dem Kapitel 4.4 mit dem Auslöser „Bei Schwellwertunter-/ - überschreitung“ mit selbständiger Änderungsmöglichkeit bestellt wurde",
    "454": "Das Bilanzierungsbeginn Datum muss kleiner sein als das Bilanzierungsende Datum in der SG8 „Datenstand des ÜNB“, SG 9 Energiemenge DZÜ Anteil",
    "455": "Das Bilanzierungsende-Datum muss größer sein, als das Bilanzierungsbeginn Datum in der SG8 „Datenstand des ÜNB“ , SG 9 Energiemenge DZÜ Anteil",
    "456": "Wenn in demselben RFF der Code Z37 (Technische Ressource) im DE1153 vorhanden",
    "457": "Wenn bei der Bestellung das Messprodukten 9991000001498 bestellt wurde",
    "458": "Wenn bei der Bestellung das Konfigurationsprodukte 9991000000739 bestellt wurde",
    "459": "NAD+MR (Nachrichtenempfänger) in der Rolle LF",
    "460": "Wenn bei der Bestellung ein Messprodukt der Codeliste der Konfigurationen aus dem Kapitel 4.4 mit dem Übertragungsweg \"aus dem SMGW\" bestellt wurde",
    "461": "Wenn in derselben SG10 das CCI (Art und Nutzung der Technischen Ressource) im CAV+ZG8 (Technischen Ressource fällt unter § 14a EnWG) vorhanden",
    "462": "Wenn in derselben SG10 das CCI+Z17 (Stromverbrauchsart) im CAV+ZH1 (Inbetriebsetzung der TR vor 2024) vorhanden",
    "463": "Wenn in derselben SG10 das CCI+Z61++ZF9 (Kunde erfüllt die Voraussetzung nach EnFG) vorhanden",
    "465": "Wenn in derselben SG8 (Daten der Technischen Ressource) das RFF+Z38 (Referenz auf die der Technischen Ressource zugeordnete Steuerbare Ressource) vorhanden ist",
    "466": "Wenn in derselben SG8 (Daten der Technischen Ressource) das RFF+Z32 (Referenz auf die der Technischen Ressource zugeordneten Netzlokation) vorhanden ist",
    "467": "Wenn in derselben SG8 (Daten der Technischen Ressource) das CAV+ZG8 (Technischen Ressource fällt unter § 14a EnWG) vorhanden ist",
    "468": "Wenn in derselben SG8 (Daten der Technischen Ressource) das SG10 CAV+ZH0 (Inbetriebsetzung der TR nach 2023) vorhanden ist",
    "469": "Wenn in derselben SG8 (Daten der Technischen Ressource) das SG10 CAV+ZH1 (Inbetriebsetzung der TR vor 2024) vorhanden ist",
    "470": "Wenn in derselben SG8 (Daten der Technischen Ressource) das CAV+ZH5 (Wechsel in das in das § 14a EnWG-Modell gem. Festlegung BK6-22-300 wurde durchgeführt) vorhanden ist",
    "471": "Wenn im selben ⊻ [473] SG6 RFF+Z49/ Z53 (Verwendungszeitraum der Daten: Gültige Daten/ Keine Daten) im DE1156 (Zeitraum-ID) eine Zeitraum ID genannt ist, die kleiner ist als in einem anderen SG6 RFF+Z49/ Z53 (Verwendungszeitraum der Daten: Gültige Daten/ Keine Daten) DE1156 (Zeitraum-ID)",
    "472": "Wenn im selben SG6 RFF+Z48/ Z55 (Verwendungszeitraum der Daten: Erwartete Daten/ Keine Daten erwartet) im DE1156 (Zeitraum-ID) eine Zeitraum ID genannt ist, die kleiner ist als in einem anderen SG6 RFF+Z48/ Z55 (Verwendungszeitraum der Daten: Erwartete Daten/ Keine Daten erwartet) DE1156 (Zeitraum-ID)",
    "473": "Wenn im selben SG6 RFF+Z47/ Z54 (Verwendungszeitraum der Daten: Im System vorhandene Daten/ Im System keine Daten vorhanden) im DE1156 (Zeitraum-ID) eine Zeitraum ID genannt ist, die kleiner ist als in einem anderen SG6 RFF+Z47/ Z54 (Verwendungszeitraum der Daten: Im System vorhandene Daten/ Im System keine Daten vorhanden) DE1156 (Zeitraum-ID)",
    "474": "Wenn SG4 STS+7++ZC8 (Transaktionsgrund \"Beendigung der Zuordnung\") vorhanden",
    "475": "Wenn SG4 STS+7++ZH1 (Transaktionsgrund \"Aufhebung einer zukünftigen Zuordnung wegen Stilllegung\") vorhanden",
    "476": "Wenn SG4 STS+7++xxx+ZW0 (Transaktionsgrundergänzung Geschäftsvorfall 1) vorhanden",
    "477": "Wenn SG4 STS+7++xxx+ZW1 (Transaktionsgrundergänzung Geschäftsvorfall 2) vorhanden",
    "478": "Wenn SG4 STS+7++xxx+ZW2 (Transaktionsgrundergänzung Geschäftsvorfall 3) vorhanden",
    "479": "Wenn SG4 STS+7++xxx+ZW3 (Transaktionsgrundergänzung Erzeugende Marktlokation) vorhanden",
    "480": "Wenn SG4 STS+7++xxx+ZW4 (Transaktionsgrundergänzung Verbrauchende Marktlokation) vorhanden",
    "481": "Wenn SG4 STS+7++xxx+ZW5 (Transaktionsgrundergänzung Tranche) vorhanden",
    "483": "Wenn SG4 STS+7++xxx+ZW7 (Transaktionsgrundergänzung Gemessene Marktlokation) vorhanden",
    "484": "Wenn SG4 STS+7++xxx+ZW8 (Transaktionsgrundergänzung Fall1) vorhanden",
    "487": "Wenn SG4 STS+7++xxx+ZX1 (Transaktionsgrundergänzung Fall4) vorhanden",
    "494": "Das hier genannte Datum muss der Zeitpunkt sein, zu dem das Dokument erstellt wurde, oder ein Zeitpunkt, der davor liegt",
    "500": "Hinweis: Code ist gemäß der Kategorie der zu stornierenden Meldung zu wählen",
    "501": "Hinweis: Es sind zur Unterstützung die Daten des LFA anzugeben",
    "502": "Hinweis: Es wird der Betrachtungsmonat der DZR bzw. BAS angegeben",
    "503": "Hinweis: Angabe des BGM DE1004 aus der ORDERS",
    "504": "Hinweis: Je Profil (ggf. inkl. Profilschar) ein Vorgang erforderlich",
    "505": "Hinweis: Je zugeordneter ID und je EEG-Überführungszeitreihe ein Vorgang erforderlich",
    "506": "Hinweis: Für jeden Code im LOC+Z16 (Marktlokation) sollen die entsprechenden Kundendaten des LF angegeben werden, falls bekannt",
    "507": "STS+7++ZH1 (Transaktionsgrund \"Aufhebung einer zukünftigen Zuordnung wegen Stilllegung\") vorhanden",
    "508": "Hinweis: Ausschließlich kME sind über die NNE abrechenbar",
    "509": "Hinweis: Handelt sich um ein mME oder iMS ist das RFF 1154 immer mit NEIN anzugeben",
    "510": "Hinweis: Zu verwenden bei der Abmeldung der ESV",
    "511": "Hinweis: Es sind alle Bilanzierungsgebiete anzugeben in denen das Profil verwendet wird",
    "512": "Hinweis: Es ist informativ die bisherige Veräußerungsform des LFA an der erzeugenden Marktlokation anzugeben",
    "513": "Hinweis: Es ist das nächstmögliche Datum ab dem DTM+471 aus der entsprechenden Anfrage zu ermitteln",
    "515": "Hinweis: Für den ZP der LieferantensummenZR anzugeben",
    "516": "Hinweis: Es ist der Änderungszeitpunkt anzugeben an dem das Zuordnungsende des NBA und der Zuordnungsbeginn des NBN zu einer Marktlokation fallen X",
    "517": "Hinweis: Anzuwenden, wenn einer Marktlokation eine Paket-ID zugeordnet wurde und diese wieder gelöscht werden soll, da sie nicht unter den genannten NB-Wechsel fällt",
    "518": "Hinweis: Es sind alle Altlieferanten anzugeben, an die eine Abmeldeanfrage gesendet wird",
    "519": "Hinweis: Wenn in der Anmeldung der Code ZAP vorhanden war, so ist dieser auch in der Antwort zu verwenden",
    "520": "Hinweis: Bei der Verwendung des Codes ZAP handelt es sich immer um eine gemessene Marktlokation",
    "521": "Hinweis: Wenn im zweiten DE 9013 des STS+7 (Transaktionsgrund) der Code ZAP vorhanden ist, so ist das hier angegebene Datum als Zuordnungsbeginn bei der Bildung der \"Ruhenden MaLo zu verstehen. Bei der Integration einer MaLo als Ruhenede MaLo in eine bestehende Marktlokation „Abbildung von § 20 Abs. 1d EnWG bzw. § 10c EEG“ ist dies das Datum ab welchem die zu integrierende MaLo hinzugefügt wurde. Am Zuordnungsbeginn der Marklokation „Abbildung von § 20 Abs. 1d EnWG bzw. § 10c EEG“ ändert sich nichts",
    "522": "Hinweis: Es ist der NBN anzugeben",
    "523": "Hinweis: Mindestens einmal für jede Marktlokation bzw. Tranche, die in der DZÜ / BG-CL / LF-SZR berücksichtigt wurde",
    "524": "(Identifikation einer Liste) STS+E01 (Status der Antwort der Liste) nicht vorhanden",
    "527": "Hinweis: Es sind alle Identifikatoren der Messlokationen anzugeben",
    "528": "Hinweis: Es ist das Datum/ Daten aus der Anfrage zu verwenden",
    "529": "Hinweis: Für zusätzliche nicht im Markt standardisierte Identifikatoren wie z.B. eine Netzbetreiber-Projektnummer",
    "530": "Hinweis: Es sind alle an der Lokation vorhandenen Daten, die mit dieser Segmentgruppe übermittelt werden und zum Datum „Änderung zum“ Gültigkeit haben, anzugeben. Dies kann zur Folge haben, dass Segmentgruppen bzw. Segmente zu wiederholen sind",
    "531": "Hinweis: Es ist das Jahr anzugeben in dem die nächste Netznutzungsabrechnung erfolgt. Diese Information ist zu der Zeitraum-ID anzugeben, welche SG6 RFF+Z49 (Verwendungszeitraum der Daten: Gültige Daten) beinhaltet und die nächste Netznutzungsabrechnung stattfindet",
    "532": "Hinweis: Kritische Daten (gemäß GPKE)",
    "533": "Hinweis: Es ist die MP-ID des Lieferanten anzugeben",
    "534": "Hinweis: Aufgrund der Wiederholbarkeit des SG4 STS Status der Antwort ist die Angabe von max. acht Verwendungszeiträumen möglich",
    "555": "Hinweis: Es sind die",
    "556": "Hinweis: Wenn keine Korrespondenzanschrift des Endverbrauchers/ Kunden vorliegt, ist die Anschrift der Marktlokation zu übermitteln",
    "557": "Hinweis: Wurden vom Verantwortlichen mehr als acht Verwendungszeiträume gesendet, so werden acht beliebige Verwendungszeiträume beantwortet",
    "558": "Segment geändert wird",
    "559": "Hinweis: Die Korrespondenzanschrift des Endverbrauchers/Kunde n wird nicht zur Identifikation genutzt",
    "560": "Hinweis: Dies entspricht dem Geschäftsvorfall A X",
    "561": "Geschäftsvorfall A X",
    "562": "Hinweis: Bei Marktlokationen, welche auf Basis von Werten bilanziert werden, wird der erste Tag des Jahres angegeben.",
    "563": "Hinweis: Für die ID der LieferantensummenZR",
    "564": "Hinweis: Das IDE+Z01 (Liste) definiert den Geschäftsvorfall. Alle aufgelisteten IDE+24 sind Bestandteil des Geschäftsvorfalls",
    "565": "Hinweis: Das IDE+24 beschreibt einen Bestandteil einer Liste, wenn ein IDE+Z01 vorhanden ist. Es beschreibt nicht den Geschäftsvorfall",
    "566": "Hinweis: Altlieferant",
    "567": "Hinweis: Neulieferant",
    "568": "Hinweis: Lieferant der LieferantensummenZR",
    "569": "Hinweis: Dritter Nutzer",
    "570": "STS+7++E03(Transaktionsgrund: Wechsel) vorhanden",
    "571": "Hinweis: Es sind alle erforderlichen Produkte aus der Anmeldung des LF des im selben SG8 genannten Produktpaket-ID zu nennen welche nicht umgesetzt werden konnten",
    "572": "STS+7++xxx+ZW4 / ZAP (Transaktionsgrundergänzung verbrauchende Marktlokation / ruhende Marktlokation) vorhanden",
    "576": "Hinweis: Stammdaten des bisherigen Messstellenbetreibers",
    "577": "STS+7++ZG9/ZH1/ZH2 (Transaktionsgrund: Aufhebung einer zukünftigen Zuordnung wegen Auszug des Kunden / -wegen Stilllegung / -wegen aufgehobenem Vertragsverhältnis) vorhanden",
    "578": "Hinweis: Dies gilt für den Zeitraum welcher mit Z53 (keine Daten) definiert ist",
    "579": "STS+7++ZG5 (Transaktionsgrund: Aufhebung der zukünftigen Zuordnung aufgrund § 38 EEG 2014 bzw. § 21b Abs. 1 Nr. 2 EEG 2017) nicht vorhanden",
    "580": "Hinweis: Ersatzbelieferung gibt es nur bei - Marktlokationen in der Niederspannung, die kein Haushaltskunde gem. EnWG sind und die nicht mehr der gesetzlichen Ersatzversorgung (drei Monate) unterliegen und - für Marktlokationen, die in Mittelspannung/Hochspannung einer Versorgung zugeführt werden sollen. Grundlage für eine Ersatzbelieferung ist die bilaterale Vereinbarung.",
    "581": "Hinweis: Es ist der Zeitpunkt anzugeben, zu welchem der Vertrag am Tag des Versandes der Antwort noch kündbar ist.",
    "586": "Hinweis: Die Messlokationsadresse ist der Messlokation zugeordnet, welche in SG8 SEQ+Z18/ ZF3 (Daten der Messlokation) mit CCI+Z01++Z82 (Verwendungsumfang: ID der prozessual behandelten Messlokation) gekennzeichnet ist",
    "590": "Hinweis: Für den Empfang des Steuerbefehls",
    "594": "ZPB des ZP der NGZ und die ZPB der NZR anzugeben",
    "599": "Hinweis: Es ist der Name und die Adresse des Ablesekartenempfängers für die Messlokation anzugeben, welche in SG8 SEQ+Z18 (Daten der Messlokation) mit CCI+Z01++Z82 (Verwendungsumfang: ID der prozessual behandelten Messlokation) gekennzeichnet ist",
    "601": "Hinweis: Es ist die ID der Marktlokation und alle Identifikatoren der Messlokationen anzugeben. Sowie wenn vorhanden die Tranche/n der Marklokation",
    "606": "IDE+24 das STS+E01++A06: E_0017 bzw. A05: E_0052 (Zu viele Marktlokationen enthalten / entfallene Marktlokation) nicht vorhanden",
    "609": "Hinweis: In diesem Segment bzw. SG sind die zwischen NB, LF und ÜNB im Rahmen der Marktkommunikation ausgetauschten Daten aus der Sicht des ÜNB anzugeben",
    "611": "Hinweis: Wenn das Unternehmen NB die Aufgaben der Marktrolle LF wahrnimmt, ist die MP-ID des Unternehmens NB in der Marktrolle LF anzugeben",
    "614": "Hinweis: Es werden nur die OBIS Kennzahlen übermittelt die für die Bilanzierung relevant sind",
    "617": "Hinweis: Mehrere Vorgänge für eine Marktlokation bei Wechsel bilanzierungsrelevanter Stammdaten innerhalb des Bilanzierungsmonats",
    "618": "Hinweis: Bisheriges Datum des MSBA. Sollte der MSBN ein abweichendes Datum verwenden wollen, so teilt er das neue Datum mit einer Stammdatenänderung mit Fehler (29.06.2026) Marklokation wird nur benötigt, wenn an dieser selbst eine kME/mME vorliegt, nicht an allen Marklokationen eines Lokationsbündels, wenn an (Marktlokation) aus einer SG8 SEQ+Z01 (Daten einer Marklokation des Lokationsbündels eine kME/ (Messtechnische Einordnung der Marktlokation) mME vorliegt. CAV+Z53 (kME/ mME) vorhanden ist, referenziert",
    "619": "Hinweis: Für die selbständige Änderungsmöglichkeit der Schwellwertunter- / -überschreitung",
    "621": "Hinweis: Es ist der MSB anzugeben, welcher ab dem Zeitpunkt der Lokation zugeordnet ist, der in DTM+76 (Datum zum geplanten Leistungsbeginn) genannt ist.",
    "622": "Hinweis: Falls die OBIS-Kennzahl für mehrere Marktrollen relevant ist, so muss die Segmentgruppe pro Marktrolle wiederholt werden",
    "623": "Hinweis: Es sind alle Identifikatoren der Messlokationen anzugeben, die zur Ermittlung der Energiemenge der im Vorgang genannten Marktlokation benötigt werden",
    "630": "Hinweis: Wenn die Liste abgelehnt wird, ist kein Vorgang enthalten",
    "631": "Hinweis: Es ist die Listennummer aus der Lieferanten- bzw. Bilanzierungsgebietsclearingliste zu verwenden",
    "632": "Hinweis: Es ist die Listennummer aus der Lieferanten-ausfallarbeitsclearingliste zu verwenden",
    "637": "Hinweis: Bei Verpflichtungsanfrage",
    "638": "Verpflichtungsanfrage",
    "639": "Hinweis: Wenn Antwort auf Deaktivierung",
    "640": "(Nachrichtenempfänger) X [233] ∧ in der Rolle NB",
    "641": "Hinweis: Wenn Einzelanforderung vorliegt",
    "642": "Hinweis: Wenn Abo vorliegt",
    "643": "STS+E01++A05/ A14 (Status der Antwort) vorhanden",
    "645": "Hinweis: Es ist der Bilanzkreis des LF anzugeben",
    "646": "Hinweis: Es ist der RD-Bilanzkreis des ANB anzugeben",
    "647": "Hinweis: Es ist der RD-Bilanzkreis des anfNB anzugeben",
    "648": "Datenclearing erforderlich",
    "651": "(Transaktionsgrund: Einzug in Neuanlage) nicht vorhanden",
    "653": "Hinweis: Es sind alle Netzlokationen, Marktlokationen, Tranchen und Messlokationen zu nennen, die durch die Bestätigung der Abmeldung der prozessual behandelten Messlokation nicht mehr dem MSB zugeordnet sind",
    "655": "Hinweis: Es ist die Listennummer aus der DZÜ Liste zu verwenden",
    "659": "Hinweis: Bei Tranchen ist nur der Meldepunkt der Tranche anzugeben",
    "660": "Hinweis: Es ist die ID der BK-Summenzeitreihe Aggregationsebene BG anzugeben",
    "662": "Hinweis: Es sind die Daten NGZ und die Daten der NZR anzugeben",
    "663": "DE9013 (Status der Antwort) ein Antwortcode aus dem Cluster Zustimmung vorhanden ist",
    "664": "Hinweis: Es ist das BG des NB (LPB) anzugeben",
    "665": "Hinweis: Wenn ein Zähler mit einem SMGW parametriert ist werden an dem Zähler keine OBIS-Kennzahlen angegeben Hier gibt es nur OBIS Kennzahlen vom SMGW",
    "667": "Hinweis: Für Zeiten die bilanziert wurden, aber inzwischen keine Aggregationsverantwortung beim ÜNB vorliegt, ist eine SG8 mit SG8 - SG10 CCI+6=ZA8 oder SG 10 CCI+6 = ZA9 CAV=ZG4 und SG8 - SG9 QTY+Z45 = 0 zu bilden",
    "670": "Hinweis: Es sind alle Netzlokationen, zu nennen, die dem gleichen Lokationsbündel angehören",
    "671": "Hinweis: Es sind alle Marktlokationen, zu nennen, die dem gleichen Lokationsbündel angehören",
    "672": "Hinweis: Es sind alle Technischen Ressourcen, zu nennen, die dem gleichen Lokationsbündel angehören",
    "673": "Hinweis: Es sind alle Steuerbaren Ressourcen, zu nennen, die dem gleichen Lokationsbündel angehören",
    "674": "Hinweis: Es sind alle Tranchen, zu nennen, die dem gleichen Lokationsbündel angehören",
    "675": "Hinweis: Es sind alle Messlokationen, zu nennen, die Lokationsbündel angehören",
    "677": "Hinweis: Es sind alle Netzlokationen, zu nennen, die aktuell und / oder zukünftig dem gleichen Lokationsbündel angehören",
    "678": "Datenclearing erforderlich",
    "679": "Hinweis: Es sind alle Technischen Ressourcen, zu nennen, die aktuell und / oder zukünftig dem gleichen Lokationsbündel angehören",
    "680": "Datenclearing erforderlich",
    "681": "Hinweis: Übergangsversorgung gibt es nur bei Marktlokationen, die unter § 38a EnWG fallen. Grundlage ist eine bilaterale Vereinbarung",
    "682": "Hinweis: Es sind alle Messlokationen, zu nennen, die aktuell und / oder zukünftig dem gleichen Lokationsbündel angehören",
    "683": "Datenclearing erforderlich",
    "684": "Hinweis: Es sind alle ID der Technischen Ressourcen, welche der im LOC+Z16/ Z22 angegebenen Marktlokation aktuell und / oder zukünftig zugehören, anzugeben",
    "685": "Hinweis: Es sind alle ID der Steuerbaren Ressourcen, welche der im LOC+Z20 angegebenen Technischen Ressourcen aktuell und / oder zukünftig zugeordnet sind, anzugeben.",
    "686": "Hinweis: Zu verwenden bei der Abmeldung der Übergangsversorgung. X",
    "687": "Hinweis: Es sind alle Messlokationen zu nennen, die für die Energiemengenermittlung aktuell und / oder zukünftig der im LOC+Z16/ Z22 angegebenen Marktlokation notwendig sind",
    "688": "Hinweis: Es sind alle ID der Netzlokationen, welche der im LOC+Z16 angegebenen Marktlokation vorgelagert sind, anzugeben",
    "689": "Hinweis: Es sind alle ID der Technischen Ressourcen, welche der im LOC+Z16 angegebenen Marktlokation zugehören, anzugeben",
    "690": "Hinweis: Es sind alle ID der Steuerbaren Ressourcen, welche der im LOC+Z20 angegebenen Technischen Ressourcen zugeordnet sind, anzugeben",
    "693": "Hinweis: Es sind die Daten NGZ anzugeben",
    "694": "Hinweis: Wenn in einer Marktlokation eine ID für eine Technischen Ressource vergeben wird, müssen für alle ggf. weitere Technische Ressourcen in der Marktlokation ID vergeben werden. Hintergrund: MSB und LF benötigen einen vollständigen Überblick auf die Art und Nutzung der Technischen Ressourcen in einer Marktlokation für die Plausibilisierung, Ersatzwertbildung, Produktauswahl bzw. Prognose",
    "695": "Hinweis: Verwendung, wenn Rolle LF einem Unternehmen NB zugeordnet ist X [696]",
    "696": "Hinweis: Verwendung, nur wenn die Rolle LF nicht einem Unternehmen NB zugeordnet ist",
    "698": "Hinweis: Für eine erzeugende Marktlokation muss für jede Technische Ressource eine ID der Technischen Ressourcen vergeben werden. Dies ist notwendig um die Nennleistung der Technische Ressource bekannt zu geben, da auf Basis diese Information die POG des MSB einer erzeugenden Marktlokation ermittelt wird",
    "699": "Hinweis: Es ist die ID der Steuerbare Ressource zu nennen über die die Technische Ressource gesteuert wird",
    "700": "Hinweis: Es ist die ID der Netzlokation zu nennen über die die Technische Ressource gesteuert wird",
    "701": "Hinweis: Es ist die Malo-ID der Tranche zu nennen, der die Technische Ressource zugeordnet ist",
    "704": "Hinweis: Segment ist zu verwenden, wenn es in Anfrage vorhanden war",
    "705": "Hinweis: Wenn die Aktion eines Sequenzdiagramms \"Rückmeldung auf Änderung\" durchgeführt wird",
    "706": "Hinweis: Wenn die Aktion eines Sequenzdiagramms \"Bestellung einer Änderung von Stammdaten...\" durchgeführt wird, mit dem Ziel ein Datenclearing durchzuführen",
    "707": "Hinweis: für weitere Details siehe Kapitel \"SG6 Verwendungszeitraum der Daten\"",
    "708": "Hinweis: Wenn die Aktion \"Ankündigung der Zuordnung des E/G zur Marktlokation\" durchgeführt wird",
    "709": "Aktion \"Ankündigung der Zuordnung des E/G zur Marktlokation\" durchgeführt wird",
    "710": "Hinweis: Wenn die Aktion \"Ankündigung der Zuordnung des LFN zur Marktlokation bzw. Tranche\" durchgeführt wird",
    "711": "Aktion \"Ankündigung der Zuordnung des LFN zur Marktlokation bzw. Tranche\" durchgeführt wird",
    "712": "Hinweis: Wenn die Aktion \"Ankündigung der Beendigung der Zuordnung des LF zur Marktlokation bzw. Tranche\" durchgeführt wird",
    "713": "Aktion \"Ankündigung der Beendigung der Zuordnung des LF zur Marktlokation bzw. Tranche\" durchgeführt wird",
    "714": "Hinweis: Es ist bei einer unterjährigen Gebietsübernahme möglich hier den bisherigen NB zu nennen um aufzuzeigen, dass die im PIA+5 dieser SG8 genannten Gruppenartikel-ID bzw. Artikel-ID auf die Preise des bisherigen NB beziehen. Wenn dies nicht der Fall ist wird die eigene MP-ID eingetragen",
    "715": "Hinweis: Dieser Transaktionsgrund darf für die betroffene Lokation nur X [719] angewendet werden, wenn zuvor vom LF eine Anfrage Abr.- Daten BK-Abr. in die Vergangenheit erfolgte oder eine Korrektur zuvor mit dem LF bilateral abgestimmt wurde (darunter fällt auch eine vom LF bestätigte rückwirkende E/G)",
    "716": "Hinweis: Wenn die Aktion eines Sequenzdiagramms \"Rückmeldung auf Abrechnungsdaten\" durchgeführt wird",
    "717": "Hinweis: Wenn die Aktion des Sequenzdiagramms \"Bestellung einer Änderung von Abrechnungsdaten\" durchgeführt wird, mit dem Ziel ein Datenclearing durchzuführen",
    "718": "Hinweis: Es sind alle Tranchen der im SG5 LOC+Z16 (Marktlokation) genannten Marktlokation anzugeben, die für die im SG6 (Verwendungszeitraum der Daten) genannten Zeiträume vorhanden sind",
    "719": "Hinweis: Dieser Transaktionsgrund darf für die betroffene Lokation nur angewendet werden wenn der LF auf eine Anfrage mit diesem Transaktionsgrund antwortet oder eine Anfrage Abr.-Daten BK-Abr. in die Vergangenheit startet um eine bilaterale Korrektur beim NB anzufragen",
    "902": "Format: Möglicher Wert: ≥ 0",
    "910": "Format: Möglicher Wert: < 0 oder ≥ 0",
    "914": "Format: Möglicher Wert: > 0",
    "922": "Format: TR-ID",
    "926": "Format: Möglicher Wert: 0",
    "930": "Format: max. 2 Nachkommastellen",
    "931": "Format: ZZZ = +00",
    "937": "Format: keine Nachkommastelle",
    "938": "Format: Möglicher Wert: <= 10",
    "942": "Format: n1-n2-n1-n3",
    "943": "Format: n1-n2-n1",
    "946": "Format: max. 11 Nachkommastellen",
    "948": "Format: n1-n2-n1-n8-n2",
    "950": "Format: Marktlokations-ID",
    "951": "Format: Zählpunktbezeichnung",
    "952": "Format: Gerätenummer nach DIN 43863-5",
    "955": "Format: Möglicher Wert: < 100",
    "957": "Format: n1-n2-n1-n8",
    "960": "Format: Netzlokations-ID",
    "961": "Format: SR-ID",
    "967": "Format: Zertifikatskörper gemäß X509.1, BSI TR-03109-4",
    "2000": "Je SG5 LOC+Z16 (Marktlokation) ist genau einmal die Segmentgruppe anzugeben",
    "2001": "STS+7++xxx+ZW5 (Transaktionsgrundergänzung Tranche) vorhanden",
    "2002": "Für jede Produktpaket-ID im SG8 SEQ+Z79 (Bestandteil eines Produktpakets) DE1050 genau einmal anzugeben",
    "2003": "Einmal für jede ruhende Marktlokation, die der Marktlokation \"Kundenanlage\" aus dem SG5 LOC+Z16 (Marktlokation) ab dem Zeitpunkt aus dem SG4 DTM+92 (Beginn zum) untergeordnet ist",
    "2004": "Segmentgruppe ist genau einmal für jede Zeitraum-ID aus dem DE1156 der SG6 RFF+Z49 (Verwendungszeitraum der Daten: \"Gültige Daten\") anzugeben",
    "2005": "Segmentgruppe ist mindesten einmal für jede Zeitraum-ID aus dem DE1156 der SG6 RFF+Z49 (Verwendungszeitraum der Daten: \"Gültige Daten\") anzugeben",
    "2006": "Datenclearing erforderlich",
    "2007": "Datenclearing erforderlich",
    "2008": "Datenclearing erforderlich",
    "2009": "Datenclearing erforderlich",
    "2010": "Segmentgruppe ist genau einmal für jede SG8 SEQ+Z01 (Daten der Marktlokation) anzugeben, bei der die Bedingungen [266] ∧ [479] an der Segmentgruppe erfüllt ist. Dabei ist die selbe Zeitraum-ID im nachfolgenden SEQ DE1050 anzugeben",
    "2011": "Segmentgruppe ist genau einmal für jede Zeitraum-ID aus dem DE1156 der SG6 RFF+Z49 / Z53 (Verwendungszeitraum der Daten: \"Gültige Daten\" / \"Keine Daten\") aus der Anfragennachricht aus SG6 RFF+TN DE1154 (Referenz Vorgangsnummer (aus Anfragenachricht)) anzugeben",
    "2012": "Segmentgruppe ist genau einmal für die Angabe der Informativen Daten der Marktlokation anzugeben",
    "2013": "Mindesten einmal anzugeben, wenn kein SG6 RFF+Z54 (Verwendungszeitraum der Daten: Im System keine Daten vorhanden) vorhanden",
    "2014": "Mindesten einmal anzugeben, wenn kein SG6 RFF+Z47 (Verwendungszeitraum der Daten: Im System vorhandene Daten) vorhanden",
    "2015": "Einmal für jede ruhende Marktlokation, die der Marktlokation \"Kundenanlage\" aus dem SG5 LOC+Z16 (Marktlokation) untergeordnet ist",
    "2016": "Segmentgruppe ist mind. einmal für jede Zeitraum-ID aus dem DE1156 der SG6 RFF+Z49 / Z53 (Verwendungszeitraum der Daten: \"Gültige Daten\" / \"Keine Daten\") aus der Anfragennachricht aus SG6 RFF+TN DE1154 (Referenz Vorgangsnummer (aus Anfragenachricht)) anzugeben",
    "2017": "(Messlokation) vorhanden",
    "2018": "Datenclearing erforderlich",
    "2060": "Wenn SG10 CAV+NZR ist die Segmentgruppe genau zwei Mal je IDE+24 anzugeben",
    "2061": "Segment bzw. Segmentgruppe ist genau einmal je SG4 IDE (Vorgang) anzugeben",
    "2071": "Für die ID der LieferantensummenZR einmal je SG4 IDE+24 (Vorgang)",
    "2073": "Für die ID der BilanzkreissummenZR einmal je SG4 IDE+24 (Vorgang)",
    "2075": "Für die ID der Zeitreihen (nicht bei EEG-EUZ und EUZ der AAÜZ) in der Clearingliste einmal je SG4 IDE+24 (Vorgang)",
    "2080": "Segmentgruppe ist max. zweimal je SG4 IDE+24 (Vorgang) anzugeben",
    "2095": "Je SG5 LOC+Z15 (MaBiS-Zählpunkt) ist genau einmal die Segmentgruppe anzugeben",
    "2096": "Segmentgruppe ist genau zweimal je SG4 IDE anzugeben",
    "2119": "Je SG8 SEQ+Z13/ ZG0 (Smartmeter-Gateway) ist genau einmal die Segmentgruppe anzugeben",
    "2121": "Segmentgruppe ist genau einmal je SG8 SEQ+Z01/ Z80/Z81 (Daten der Marktlokation/ Erwartete Daten der Marktlokation/ Im System vorhandene Daten der Marktlokation) anzugeben",
    "2140": "Für die ID der LieferantensummenZR einmal je SG4 IDE+Z01 (Liste)",
    "2182": "Segmentgruppe ist genau einmal je SG8 SEQ+Z01/ Z80/ Z81/ Z98 (Daten der Marktlokation/ Erwartete Daten der Marktlokation/ Im System vorhandene Daten der Marktlokation) anzugeben",
    "2183": "Segmentgruppe ist genau zweimal je SG8 SEQ+Z01/ Z80/ Z81/ Z98 (Daten der Marktlokation/ Erwartete Daten der Marktlokation/ Im System vorhandene Daten der Marktlokation) anzugeben",
    "2207": "Für die ID der Lieferanten-ausfall-arbeitssummen-zeitreihe einmal je SG4 IDE+Z01 (Liste)",
    "2225": "Einmal für jede Marktlokation bzw. Tranche für die der LF nicht die gemeldete Ansicht des NB teilt",
    "2236": "Code einmal je SG4 IDE+24 (Vorgang)",
    "2252": "Einmal für jede Marktlokation bzw. Tranche, die in der Lieferantenausfallarbeitssummenzeitreihe berücksichtigt wurde",
    "2261": "Für jede ID im SG5 LOC+Z21 (Tranche) DE3225, mindestens einmal anzugeben",
    "2284": "Für jede Messlokations-ID im SG5 LOC+Z17 (Messlokation) DE3225 genau einmal anzugeben",
    "2286": "Für jede SEQ+ZF3 (Daten der Messlokation) mindestens einmal anzugeben",
    "2287": "Für jede SEQ+Z03/ ZF5 (Zähleinrichtungsdaten ) mindestens einmal anzugeben",
    "2288": "Einmal für jede Zeitreihe, die in der DZR berücksichtigt wurde",
    "2307": "Für jede ID im SG5 LOC+Z21 (Tranche) DE3225 genau einmal anzugeben",
    "2308": "Für jede ID im SG5 LOC+Z16 (Marktlokation) DE3225, mindestens einmal anzugeben",
    "2309": "Für jede ID im SG5 LOC+Z17 (Messlokation) DE3225 mindestens einmal anzugeben",
    "2310": "Für jede ID im SG5 LOC+Z16 (Marktlokation) DE3225 genau einmal anzugeben",
    "2311": "Für jede ID im SG5 LOC+Z21 (Tranche) DE3225, mindestens einmal anzugeben",
    "2312": "Wenn der Objektcode \"9992000001256\" (Netzlokation) im DE1154 des selben RFF+Z33 nicht vorhanden ist, ist das RFF+Z33 in derselben SG8 SEQ+Z58/ ZC9/ ZD0/ ZD6 (Zuordnung Lokation zum Objektcode des Lokationsbündels) genau einmal anzugeben",
    "2313": "Je SG8 SEQ+Z58/ ZC9/ ZD0/ ZD6 (Zuordnung Lokation zum Objektcode des Lokationsbündels) genau einmal anzugeben",
    "2317": "Wenn in derselben SG8 SEQ+Z04/ ZF7 (Wandlerdaten) das SG10 CCI+++Z25 (Wandler) CAV+MIW/MPW/MUW vorhanden, ist das Segment mindestens zweimal anzugeben",
    "2318": "Wenn in derselben SG8 SEQ+Z04/ ZF7 (Wandlerdaten) das SG10 CCI+++Z25 (Wandler) CAV+MBW (Blockstromwandler) vorhanden, ist das Segment genau einmal anzugeben",
    "2344": "Einmal für jede Marktlokation bzw. Tranche, die in der DZÜ / BG-CL / LF-SZR berücksichtigt wurde",
    "2350": "Für jedes SMGW das im SEQ+Z13/ ZG0 (Smartmeter-Gateway) SG10 CCI+++Z75 CAV+Z30 (Gerätenummer) genannt ist, mindestens einmal je SEQ+Z03/ ZF5 (Zähleinrichtungsdaten ) das mit SG8 RFF+Z14 (Referenz auf das Smartmeter-Gateway) auf das SMGW referenziert",
    "2351": "Einmal je ZP einer BK-SZR, in der die Marktlokation in die Berechnung der abgerechneten Summenzeitreihe aufgenommen wurde",
    "2352": "Einmal je ZP einer BG-SZR, in der die Marktlokation in die Berechnung der abgerechneten Summenzeitreihe aufgenommen wurde",
    "2356": "Je SG5 LOC+Z18 (Netzlokation) ist genau einmal die Segmentgruppe anzugeben",
    "2357": "LOC+Z20 (Technische Ressource) vorhanden",
    "2358": "Je SG5 LOC+Z19 (Steuerbare Ressource) ist genau einmal die Segmentgruppe anzugeben",
    "2359": "Für jede ID im SG5 LOC+Z16 / Z17 / Z20 (Marktlokation / Messlokation / Technische Ressource) DE3225 mindestens einmal anzugeben",
    "2360": "Für jede ID im SG5 LOC+Z18 (Netzlokation) DE3225 mindestens einmal anzugeben",
    "2361": "Für jede ID im SG5 LOC+Z17 / Z20 / Z22 (Messlokation / Technische Ressource / ruhende Marktlokation) DE3225 mindestens einmal anzugeben",
};

// Zusammenführung: Text + abgeleitete Art + (falls vorhanden) Prüflogik-Overlay.
var ahbBedingungen = {};
for (const nr in bedingungTexte) {
    ahbBedingungen[nr] = Object.assign(
        { text: bedingungTexte[nr], art: bedingungsart(nr) },
        bedingungLogik[nr] || {}
    );
}

// Liefert Text zu einer Bedingungsnummer (für Meldungen).
function bedingungText(nr) {
    const b = ahbBedingungen[String(nr)];
    return b ? `[${nr}] ${b.text}` : `[${nr}]`;
}

// Ist die Bedingung eine harte (zu prüfende) Voraussetzung/Wiederholbarkeit/Format?
// Hinweise ([500]-[899]) sind NICHT hart und werden bei der Prüfung übersprungen.
function bedingungIstHart(nr) {
    const art = bedingungsart(nr);
    return art === "voraussetzung" || art === "wiederholbarkeit" || art === "format";
}

if (typeof module !== 'undefined')
    module.exports = { ahbBedingungen, bedingungTexte, bedingungLogik, bedingungText, bedingungsart, bedingungIstHart };

// Bedingungs-Hilfe (Fragezeichen-Symbol an den Bedingungsausdrücken): sie erwartet die
// Texte unter window.EdiBedingungen als { "nn": { text, art, check } }. Diese Datei
// führt sie in eigenen Strukturen; die folgende Brücke stellt sie bereit, ohne an der
// bestehenden Verwendung etwas zu ändern.
if (typeof window !== 'undefined') {
    window.EdiBedingungen = window.EdiBedingungen || {};
    Object.keys(bedingungTexte).forEach(function (nr) {
        if (window.EdiBedingungen[nr]) return;
        var eintrag = { text: bedingungTexte[nr] };
        try { eintrag.art = bedingungsart(nr); } catch (e) { eintrag.art = 'sonstige'; }
        if (typeof bedingungLogik !== 'undefined' && bedingungLogik[nr])
            eintrag.check = bedingungLogik[nr];
        window.EdiBedingungen[nr] = eintrag;
    });
}

// --- Nachtrag 28.07.2026 -------------------------------------------------
// Diese Bedingungen werden in den Formularen referenziert, fehlten aber in der
// Bedingungsdatei; die Texte stammen aus der AHB-Extraktion desselben Stands.
if (typeof window !== 'undefined') {
    window.EdiBedingungen = window.EdiBedingungen || {};
    var _nachtrag = {
        "432": { text: "Wenn in derselben SG8 SEQ+Z27 (Erforderliches Messprodukt der Marktlokation), das PIA+5+9991000000078: Z11 (Wirkarbeit Lastgang 1/4 stündlich) vorhanden ist", art: "voraussetzung" },
    };
    Object.keys(_nachtrag).forEach(function (nr) {
        if (!window.EdiBedingungen[nr]) window.EdiBedingungen[nr] = _nachtrag[nr];
    });
}
