// _bedingungen.js (REQOTE) - AHB-Bedingungen, extrahiert mit kohlrahbi (Hochfrequenz).
// Offizieller conditions-Scraper, Quelle FV2604.
var reqoteBedingungen = {
  "1": { text: "Wenn DTM+203 (Ausführungsdatum) nicht vorhanden", art: "voraussetzung" },
  "2": { text: "Wenn DTM+469 (Beginn zum (nächstmöglichen Termin)) nicht vorhanden", art: "voraussetzung" },
  "10": { text: "MP-ID nur aus Sparte Strom", art: "voraussetzung" },
  "15": { text: "Wenn DTM+76 (Datum zum geplanten Leistungsbeginn) nicht vorhanden", art: "voraussetzung" },
  "16": { text: "Wenn SG1 RFF+Z41 (Referenznummer des Vorgangs der Anmeldung nach WiM) nicht vorhanden", art: "voraussetzung" },
  "17": { text: "Wenn SG1 RFF+Z41 (Referenznummer des Vorgangs der Anmeldung nach WiM) vorhanden", art: "voraussetzung" },
  "18": { text: "Wenn IMD++Z55 (Änderung Konfiguration) vorhanden", art: "voraussetzung" },
  "19": { text: "Wenn SG27 LIN++Z64 (Erforderliches Produkt Schaltzeitdefinitionen) vorhanden", art: "voraussetzung" },
  "20": { text: "Wenn SG27 LIN++Z65 (Erforderliches Produkt Leistungskurvendefinitionen) vorhanden", art: "voraussetzung" },
  "21": { text: "Wenn SG27 LIN++Z66 (Erforderliches Produkt Ad-hoc- Steuerkanal) vorhanden", art: "voraussetzung" },
  "22": { text: "Wenn SG27 LIN++Z67 (Erforderliches Messprodukt für Werte nach Typ 2 aus Backend) vorhanden", art: "voraussetzung" },
  "23": { text: "Wenn SG27 LIN++Z68 (Erforderliches Produkt Konfigurationserlaubnis für Werte nach Typ 2 aus SMGW) vorhanden", art: "voraussetzung" },
  "24": { text: "Wenn Produkt bestellt werden soll", art: "voraussetzung" },
  "25": { text: "Wenn in LOC+172 DE3225 (Meldepunkt) die ID einer Marktlokation angegeben ist.", art: "voraussetzung" },
  "26": { text: "Wenn in LOC+172 DE3225 (Meldepunkt) die ID einer Messlokation angegeben ist.", art: "voraussetzung" },
  "27": { text: "Wenn in LOC+172 DE3225 (Meldepunkt) die ID einer Netzlokation angegeben ist.", art: "voraussetzung" },
  "28": { text: "Wenn in LOC+172 DE3225 (Meldepunkt) die ID einer Steuerbaren Ressource angegeben ist.", art: "voraussetzung" },
  "29": { text: "Es sind nur dieKonfigurations-Produkte erlaubt, die in der Codeliste der Konfigurationen im Kapitel 4.1 „Konfigurationsprodukte Schaltzeitdefinition“ enthalten sind.", art: "voraussetzung" },
  "30": { text: "Es sind nur die Konfigurations-Produkte erlaubt, die in der Codeliste der Konfigurationen im Kapitel 4.2 „Konfigurationsprodukte Leistungskurvendefinition“ enthalten sind.", art: "voraussetzung" },
  "31": { text: "Es sind nur die Konfigurations-Produkte erlaubt, die in der Codeliste der Konfigurationen im Kapitel 4.3 „Konfigurationsprodukte Ad- Hoc-Steuerkanal“ enthalten sind.", art: "voraussetzung" },
  "32": { text: "Es sind nur die Messprodukte erlaubt, die in der Codeliste der Konfigurationen im Kapitel 4.5 „Messprodukte für Werte nach Typ 2 aus Backend für LF und NB“ enthalten sind.", art: "voraussetzung" },
  "33": { text: "Es sind nur die Messprodukte erlaubt, die in der Codeliste der Konfigurationen im Kapitel 4.4 „Messprodukte mit Konfigurationserlaubnis für Werte nach Typ 2 aus SMGW“ enthalten sind.", art: "voraussetzung" },
  "35": { text: "Wenn MP-ID in SG11 NAD+MS mit Rolle LF vorhanden", art: "voraussetzung" },
  "36": { text: "Wenn MP-ID in SG11 NAD+MS mit Rolle NB vorhanden", art: "voraussetzung" },
  "37": { text: "Es sind nur die Messprodukt-Position-Codes erlaubt, die in der Codeliste der Konfigurationen im Kapitel 4.7 „Art der Werte für Messprodukte nach Typ 2“ enthalten sind.", art: "voraussetzung" },
  "38": { text: "Wenn innerhalb derselben SG27 LIN im PIA+5 DE7140 (Erforderliches Produkt Konfigurationserlaubnis für Werte nach Typ 2 aus SMGW) ein Produkt angegeben ist, das in der Codeliste der Konfigurationen im Kapitel 4.4 „Messprodukte mit Konfigurationserlaubnis für Werte nach Typ 2 aus SMGW“ in der Spalte \"Auslöser\" mit dem Wert \"Bei Schwellwertunter- / - überschreitung\" gekennzeichnet ist.", art: "voraussetzung" },
  "39": { text: "wenn im DE3155 in demselben COM der Code EM vorhanden ist", art: "voraussetzung" },
  "40": { text: "wenn im DE3155 in demselben COM der Code TE / FX / AJ / AL vorhanden ist", art: "voraussetzung" },
  "41": { text: "Es sind nur die Messprodukte erlaubt, die in der Codeliste der Konfigurationen im Kapitel 4.6.1 „Werte nach Typ 2 aus Backend“ enthalten sind.", art: "voraussetzung" },
  "42": { text: "Es sind nur die Messprodukte erlaubt, die in der Codeliste der Konfigurationen im Kapitel 4.6.2 „Werte nach Typ 2 aus SMGW“ enthalten sind.", art: "voraussetzung" },
  "43": { text: "Wenn innerhalb derselben SG27 LIN im PIA+5 DE7140 (Erforderliches Produkt Konfigurationserlaubnis für Werte nach Typ 2 aus SMGW) ein Produkt angegeben ist, das in der Codeliste der Konfigurationen im Kapitel 4.6.2 „Werte nach Typ 2 aus SMGW“ in der Spalte \"Auslöser\" mit dem Wert \"Bei Schwellwertunter- / - überschreitung\" gekennzeichnet ist.", art: "voraussetzung" },
  "44": { text: "Wenn in SG27 LIN (Erforderliches Produkt der Messlokation) das PIA+5 DE7140 mit einem Produkt-Code vorhanden ist der in der Codeliste der Konfigurationen im Kapitel 7 \"Produkte zur Bestellung einer Änderung an einer Lokation\" in der \"Spalte Bezeichnung\" mit dem Wert \"weitere Energieflussrichtung\" vorhanden ist.", art: "voraussetzung" },
  "45": { text: "Wenn in LOC+172 DE3225 (Meldepunkt) die ID einer Steuerbaren Ressource angegeben ist.", art: "voraussetzung" },
  "47": { text: "Es sind nur die Produkt-Codes erlaubt, die in der Codeliste der Konfigurationen im Kapitel 7 \"Produkte zur Bestellung einer Änderung an einer Lokation\" die in der Spalte \"Ebene\" mit dem Wert \"Messlokation\" vorhanden sind.", art: "voraussetzung" },
  "48": { text: "Es sind weiterhin nur die Produkt-Codes erlaubt, die in der Codeliste der Konfigurationen im Kapitel 7 \"Produkte zur Bestellung einer Änderung an einer Lokation\" die in der Spalte \"Produkt gegenüber MSB von Marktrolle bestellbar\" mit einem \"X\" in der Spalte \"NB\" gekennzeichnet ist.", art: "voraussetzung" },
  "49": { text: "Es sind weiterhin nur die Produkt-Codes erlaubt, die in der Codeliste der Konfigurationen im Kapitel 7 \"Produkte zur Bestellung einer Änderung an einer Lokation\" die in der Spalte \"Produkt gegenüber MSB von Marktrolle bestellbar\" mit einem \"X\" in der Spalte \"LF\" gekennzeichnet ist.", art: "voraussetzung" },
  "50": { text: "Es sind nur die Produkt-Codes erlaubt, die in der Codeliste der Konfigurationen im Kapitel 7 \"Produkte zur Bestellung einerÄnderung an einer Lokation\" die in der Spalte \"Ebene\" mit dem Wert \"Netzlokation\" vorhanden sind.", art: "voraussetzung" },
  "51": { text: "Es sind nur die Produkt-Codes erlaubt, die in der Codeliste der Konfigurationen im Kapitel 7 \"Produkte zur Bestellung einer Änderung an einer Lokation\" die in der Spalte \"Ebene\" mit dem Wert \"Steuerbare Ressource\" vorhanden sind.", art: "voraussetzung" },
  "52": { text: "wenn im DE3155 in demselben COM der Code TE / AL vorhanden ist", art: "voraussetzung" },
  "53": { text: "wenn der LF der Marktlokation der genannten Lokation im gewünschtenUmsetzungszeitraum nicht zugeordnet ist.", art: "voraussetzung" },
  "490": { text: "wenn Wert in diesem DE, an der Stelle CCYYMMDDHHMM ein Zeitpunkt aus dem angegeben Zeitraum der Tabelle Kapitel 3.5 „Übersicht gesetzliche deutsche Sommerzeit (MESZ)“ der Spalten:\n›\t„Sommerzeit (MESZ) von“ Darstellung in UTC und\n›\t„Sommerzeit (MESZ) bis“ Darstellung in UTC ist.", art: "voraussetzung" },
  "491": { text: "wenn Wert in diesem DE, an der Stelle CCYYMMDDHHMM ein Zeitpunkt aus dem angegeben Zeitraum der Tabelle Kapitel 3.6 „Übersicht gesetzliche deutsche Zeit (MEZ)“ der Spalten: \n›\t„Winterzeit (MEZ) von“ Darstellung in UTC und\n›\t„Winterzeit (MEZ) bis“ Darstellung in UTC ist.", art: "voraussetzung" },
  "492": { text: "wenn MP-ID in NAD+MR aus Sparte Strom", art: "voraussetzung" },
  "493": { text: "wenn MP-ID in NAD+MR aus Sparte Gas", art: "voraussetzung" },
  "494": { text: "Das hier genannte Datum muss der Zeitpunkt sein, zu dem das Dokument erstellt wurde, oder ein Zeitpunkt, der davor liegt.", art: "voraussetzung" },
  "500": { text: "Hinweis: Angabe eines technischen Ansprechpartners für die Geräteübernahme", art: "hinweis" },
  "501": { text: "Hinweis: Angabe eines Ansprechpartners für die Rechnungsabwicklung", art: "hinweis" },
  "502": { text: "Hinweis: Verwendung der ID der Marktlokation", art: "hinweis" },
  "503": { text: "Hinweis: Verwendung der ID der Messlokation", art: "hinweis" },
  "504": { text: "Hinweis: Verwendung der ID der Tranche", art: "hinweis" },
  "507": { text: "Hinweis: Vorgangsnummer aus SG4 IDE+24 DE7402 der UTILMD mit BGM+E01 mit der die Anmeldung des MSB-Wechsels erfolgt ist.", art: "hinweis" },
  "508": { text: "Hinweis: Wert aus BGM+Z73 DE1004 der IFTSTA mit der die Antwort auf die Bestellung der Konfiguration übermittelt wurde", art: "hinweis" },
  "509": { text: "Hinweis: Vorgangsnummer aus CNI DE1490 der IFTSTA mit BGM+Z73 mit der die Antwort auf die Bestellung der Konfiguration übermittelt wurde", art: "hinweis" },
  "510": { text: "Hinweis: Verwendung der ID der Netzlokation", art: "hinweis" },
  "511": { text: "Hinweis: Verwendung der ID der Steuerbaren Ressource", art: "hinweis" },
  "512": { text: "Hinweis: Für den Empfang der Werte nach Typ 2 aus dem SMGW.", art: "hinweis" },
  "514": { text: "Hinweis: Es darf nur eine Information im DE3148 übermittelt werden", art: "hinweis" },
  "515": { text: "Hinweis: Es ist eine URI IPv4 für die Bereitstellung der Werte anzugeben.", art: "hinweis" },
  "516": { text: "Hinweis: Es ist eine URI IPv6 für die Bereitstellung der Werte anzugeben.", art: "hinweis" },
  "517": { text: "Hinweis: Verwendung der ID der Technischen Ressource", art: "hinweis" },
  "518": { text: "Hinweis: zur Angabe von Kontaktdaten des Kunden des Lieferanten um die Änderung an der Technik zu vereinfachen.", art: "hinweis" },
  "520": { text: "Hinweis: Angabe des Beginnzeitpunkts des gewünschten Umsetzungstermins aus Sicht des Anfragenden.", art: "hinweis" },
  "521": { text: "Hinweis: Angabe des Endezeitpunkts des gewünschten Umsetzungstermins aus Sicht des Anfragenden.", art: "hinweis" },
  "903": { text: "Format: Möglicher Wert: 1", art: "format" },
  "906": { text: "Format: max. 3 Nachkommastellen", art: "format" },
  "911": { text: "Format: Mögliche Werte: 1 bis n, je Nachricht oder Segmentgruppe bei 1 beginnend und fortlaufend aufsteigend", art: "format" },
  "922": { text: "Format: TR-ID", art: "format" },
  "931": { text: "Format: ZZZ = +00", art: "format" },
  "932": { text: "Format: HHMM = 2200", art: "format" },
  "933": { text: "Format: HHMM = 2300", art: "format" },
  "934": { text: "Format: HHMM = 0400", art: "format" },
  "935": { text: "Format: HHMM = 0500", art: "format" },
  "939": { text: "Format: Die Zeichenkette muss die Zeichen @ und . enthalten", art: "format" },
  "940": { text: "Format: Die Zeichenkette muss mit dem Zeichen + beginnen und danach dürfen nur noch Ziffern folgen", art: "format" },
  "950": { text: "Format: Marktlokations-ID", art: "format" },
  "951": { text: "Format: Zählpunktbezeichnung", art: "format" },
  "960": { text: "Format: Netzlokations-ID", art: "format" },
  "961": { text: "Format: SR-ID", art: "format" },
  "962": { text: "Format: max. 6 Vorkommastellen", art: "format" },
  "967": { text: "Format: Zertifikatskörper gemäß X509.1, BSI TR-03109-4", art: "format" },
  "2005": { text: "Pro Nachricht ist die SG27 genau einmal anzugeben", art: "wiederholbarkeit" },
  "2060": { text: "Pro Nachricht ist die SG27 LIN+Z64 (Erforderliches Produkt Schaltzeitdefinitionen) maximal einmal anzugeben", art: "wiederholbarkeit" },
  "2061": { text: "Pro Nachricht ist die SG27 LIN++Z65 (Erforderliches Produkt Leistungskurvendefinitionen) maximal einmal anzugeben", art: "wiederholbarkeit" },
  "2062": { text: "Pro Nachricht ist die SG27 LIN++Z66 (Erforderliches Produkt Ad-hoc-Steuerkanal) maximal einmal anzugeben", art: "wiederholbarkeit" },
  "2063": { text: "Pro Nachricht ist die SG27 LIN++Z67 (Erforderliches Messprodukt für Werte nach Typ 2 aus Backend) maximal einmal anzugeben", art: "wiederholbarkeit" },
  "2064": { text: "Pro Nachricht ist die SG27 LIN++Z68 (Erforderliches Produkt Konfigurationserlaubnis für Werte nach Typ 2 aus SMGW) maximal einmal anzugeben", art: "wiederholbarkeit" },
  "2065": { text: "Diese SG28 ist so oft zu wiederholen, wie zu den unterschiedlichen Messprodukt- Position-Codes zu dem innerhalb derselben SG27 LIN im PIA+5 DE7140 (Erforderliches Produkt Konfigurationserlaubnis für Werte nach Typ 2 aus SMGW) angegebenen Produkt ein Produkt angegeben ist, das in der Codeliste der Konfigurationen im Kapitel 4.4 „Messprodukte mit Konfigurationserlaubnis für Werte nach Typ 2 aus SMGW“ in der Spalte \"Auslöser\" mit dem Wert \"Bei Schwellwertunter- / - überschreitung\" gekennzeichnet ist.", art: "wiederholbarkeit" },
  "2066": { text: "Diese SG28 ist so oft zu wiederholen, wie zu den unterschiedlichen Messprodukt-Position-Codes zu dem innerhalb derselben SG27 LIN im PIA+5 DE7140 (Erforderliches Produkt Konfigurationserlaubnis für Werte nach Typ 2 aus SMGW) angegebenen Produkt ein Produkt angegeben ist, das in der Codeliste der Konfigurationen im Kapitel 4.6.2 „Werte nach Typ 2 aus SMGW“ in der Spalte \"Auslöser\" mit dem Wert \"Bei Schwellwertunter- / - überschreitung\" gekennzeichnet ist.", art: "wiederholbarkeit" },
  "2067": { text: "Die SG12 RFF+Z37 Referenz auf ID der Technischen Ressource ist so oft zu wiederholen, bis alle IDs der Technischen Ressourcenangegeben sind, die der Steuerbaren Ressource in LOC+172 DE3225 (Meldepunkt) mit diesem Vorgang zugeordnet werden sollen, genannt sind.", art: "wiederholbarkeit" },
  "2068": { text: "Diese SG27 ist so oft zu wiederholen, dass alle Produkte zur Lokation die innerhalb des gewünschten Umsetzungstermins (Zeitintervall aus DTM+469 (Startdatum oder Zeitpunkt) und DTM+472 (Endedatum oder Zeitpunkt)) aus Sicht des Anfragenden gewünscht sind und deren Kombination gemäß Codeliste der Konfigurationen Kapitel 7 \"Produkte zur Bestellung einer Änderung an einer Lokation\"möglich sind, genannt sind.", art: "wiederholbarkeit" },
};
if (typeof window!=='undefined') window.EdiBedingungen = Object.assign(window.EdiBedingungen||{}, reqoteBedingungen);
if (typeof module!=='undefined') module.exports = reqoteBedingungen;
