// _bedingungen.js (REMADV) - AHB-Bedingungen, extrahiert mit kohlrahbi (Hochfrequenz).
// Offizieller conditions-Scraper, Quelle FV2604.
var remadvBedingungen = {
  "2": { text: "Wenn SG7 AJT+28 vorhanden", art: "voraussetzung", check: {"tag": "AJT", "qual": "28", "neg": false} },
  "3": { text: "Bei SG5 DOC+389 / Z25 ist der Wert aus derselben SG5 MOA+9 mit (-1) multipliziert anzugeben.", art: "voraussetzung" },
  "4": { text: "Bei SG5 DOC+380 / 457 ist der Wert aus derselben SG5 MOA+9 unverändert anzugeben.", art: "voraussetzung" },
  "8": { text: "Wenn SG7 AJT+A01/ A02+E_0505 vorhanden", art: "voraussetzung" },
  "9": { text: "Wenn SG7 AJT+A32/ A99+E_0503 vorhanden", art: "voraussetzung" },
  "11": { text: "Wenn in diesem AJT DE1082 = E_0406", art: "voraussetzung" },
  "12": { text: "Wenn in diesem AJT DE1082 = E_0407", art: "voraussetzung" },
  "14": { text: "A-Code aus Cluster Ablehnung auf Kopfebene", art: "voraussetzung" },
  "15": { text: "A-Code aus Cluster Ablehnung auf Positionsebene", art: "voraussetzung" },
  "16": { text: "A-Code aus Cluster Ablehnung auf Summenebene", art: "voraussetzung" },
  "18": { text: "Wenn in dieser SG7 AJT DE4465 = A74/A75/A76/AC5", art: "voraussetzung" },
  "22": { text: "Wenn in dieser SG7 AJT DE4465 = A02/A06/A16/ A66/A67/A68/A69/A78/A90/ A95/A96/AC3/AC4", art: "voraussetzung" },
  "26": { text: "Wenn in dieser SG12 AJT DE4465 = A51/A62/A82/ AA1/AA6/AA7/AB8/AD6", art: "voraussetzung" },
  "28": { text: "Wenn in dieser SG12 AJT DE4465 = A23/A26/A35/ A36/A38/A46/A47/A48/A50/ A58/A59/A61/A77/A84/A99", art: "voraussetzung" },
  "33": { text: "Wenn in diesem AJT DE1082 = S_0103", art: "voraussetzung" },
  "34": { text: "Wenn in diesem AJT DE1082 = S_0104", art: "voraussetzung" },
  "35": { text: "Wenn in dieser SG12 AJT DE4465 = A34/A39/AA2/AB2", art: "voraussetzung" },
  "36": { text: "Wenn in dieser SG7 AJT DE4465 = A12/A75/A80/AE1", art: "voraussetzung" },
  "39": { text: "Wenn in dieser SG7 AJT DE4465 = AC1", art: "voraussetzung" },
  "40": { text: "Wenn in dieser SG7 AJT DE1082 = E_0406", art: "voraussetzung" },
  "41": { text: "Wenn in dieser SG7 AJT DE1082 = E_0407", art: "voraussetzung" },
  "42": { text: "Wenn in SG7 AJT DE1082 = E_0407/E_0568/E_0521/ E_0517/E_0266", art: "voraussetzung" },
  "43": { text: "Wenn in SG12 AJT DE4465=28", art: "voraussetzung" },
  "45": { text: "Nur MP-ID aus Sparte Strom", art: "voraussetzung" },
  "47": { text: "Wenn in diesem AJT DE1082 = E_0210", art: "voraussetzung" },
  "48": { text: "Wenn in diesem AJT DE1082 = E_0259", art: "voraussetzung" },
  "49": { text: "Wenn in dieser SG7 AJT DE4465 = A01/A05/A22/ A23/A90/A96", art: "voraussetzung" },
  "50": { text: "Wenn in dieser SG7 AJT DE4465 = A01/A05/A18/ A19/A20/A90/A96", art: "voraussetzung" },
  "51": { text: "Wenn in dieser SG12 AJT DE1082 = E_0406", art: "voraussetzung" },
  "52": { text: "Wenn in dieser SG12 AJT DE1082 = E_0407", art: "voraussetzung" },
  "53": { text: "Wenn in dieser SG12 AJT DE4465 = A25/A31/A99/AF1", art: "voraussetzung" },
  "54": { text: "Wenn in dieser SG12 AJT DE1082 = E_0210", art: "voraussetzung" },
  "55": { text: "Wenn in dieser SG12 AJT DE1082 = E_0259", art: "voraussetzung" },
  "56": { text: "Wenn in dieser SG7 AJT DE4465 = A21", art: "voraussetzung" },
  "57": { text: "Wenn in dieser SG7 AJT DE1082 = E_0210", art: "voraussetzung" },
  "58": { text: "Wenn in dieser SG7 AJT DE1082 = E_0259", art: "voraussetzung" },
  "59": { text: "Wenn SG7 AJT+A08/ A99+E_0459 vorhanden", art: "voraussetzung" },
  "60": { text: "Wenn SG7 AJT+A99+E_0243 vorhanden", art: "voraussetzung" },
  "61": { text: "Wenn SG7 AJT+A99+E_0261 vorhanden", art: "voraussetzung" },
  "62": { text: "Wenn SG7 AJT+A99+E_1007 vorhanden", art: "voraussetzung" },
  "63": { text: "Wenn SG7 AJT+A01/ A02+E_1009 vorhanden", art: "voraussetzung" },
  "64": { text: "Wenn in dieser SG12 AJT DE1082 = E_0264", art: "voraussetzung" },
  "65": { text: "Wenn in dieser SG12 AJT DE1082 = E_0515", art: "voraussetzung" },
  "66": { text: "Wenn in dieser SG12 AJT DE1082 = E_0519", art: "voraussetzung" },
  "67": { text: "Wenn in dieser SG12 AJT DE1082 = E_0266", art: "voraussetzung" },
  "68": { text: "Wenn in dieser SG12 AJT DE1082 = E_0517", art: "voraussetzung" },
  "69": { text: "Wenn in dieser SG12 AJT DE1082 = E_0521", art: "voraussetzung" },
  "70": { text: "Wenn in dieser SG12 AJT DE4465 = A15", art: "voraussetzung" },
  "71": { text: "Wenn in dieser SG12 AJT DE4465 = A99", art: "voraussetzung" },
  "72": { text: "Wenn SG7 AJT+A99+E_0518 vorhanden", art: "voraussetzung" },
  "73": { text: "Wenn SG7 AJT+A99+E_0522 vorhanden", art: "voraussetzung" },
  "74": { text: "Wenn SG7 AJT+A99+E_0267 vorhanden", art: "voraussetzung" },
  "75": { text: "Wenn in diesem AJT DE1082 = E_0264", art: "voraussetzung" },
  "76": { text: "Wenn in diesem AJT DE1082 = E_0266", art: "voraussetzung" },
  "77": { text: "Wenn in diesem AJT DE1082 = E_0515", art: "voraussetzung" },
  "78": { text: "Wenn in diesem AJT DE1082 = E_0517", art: "voraussetzung" },
  "79": { text: "Wenn in diesem AJT DE1082 = E_0519", art: "voraussetzung" },
  "80": { text: "Wenn in diesem AJT DE1082 = E_0521", art: "voraussetzung" },
  "81": { text: "Wenn in dieser SG7 AJT DE1082 = E_0264", art: "voraussetzung" },
  "82": { text: "Wenn in dieser SG7 AJT DE1082 = E_0515", art: "voraussetzung" },
  "83": { text: "Wenn in dieser SG7 AJT DE1082 = E_0519", art: "voraussetzung" },
  "84": { text: "Wenn in dieser SG7 AJT DE1082 = E_0266", art: "voraussetzung" },
  "85": { text: "Wenn in dieser SG7 AJT DE1082 = E_0517", art: "voraussetzung" },
  "86": { text: "Wenn in dieser SG7 AJT DE1082 = E_0521", art: "voraussetzung" },
  "87": { text: "Wenn in dieser SG7 AJT DE4465 = A05/A21/A22/ A23/A90/A96/AE7", art: "voraussetzung" },
  "88": { text: "Wenn in dieser SG7 AJT DE4465 = A25", art: "voraussetzung" },
  "89": { text: "wenn im DE3155 in demselben COM der Code EM vorhanden ist", art: "voraussetzung" },
  "90": { text: "wenn im DE3155 in demselben COM der Code TE / FX / AJ / AL vorhanden ist", art: "voraussetzung" },
  "91": { text: "Wenn in diesem AJT DE1082 = E_0566", art: "voraussetzung" },
  "92": { text: "Wenn in diesem AJT DE1082 = E_0568", art: "voraussetzung" },
  "93": { text: "Wenn SG7 AJT+A99+E_0804 vorhanden", art: "voraussetzung" },
  "94": { text: "Wenn SG7 AJT+A99+E_0806 vorhanden", art: "voraussetzung" },
  "95": { text: "Wenn SG7 AJT+A99+E_0569 vorhanden", art: "voraussetzung" },
  "96": { text: "Wenn SG7 AJT+E_0503/ E_1007 vorhanden", art: "voraussetzung" },
  "97": { text: "Wenn in dieser SG12 AJT DE4465 = A27", art: "voraussetzung" },
  "98": { text: "Wenn in SG12 AJT DE1082 = E_0407", art: "voraussetzung" },
  "99": { text: "Wenn in SG12 AJT DE1082 = E_0568", art: "voraussetzung" },
  "100": { text: "Wenn SG7 AJT+A01 vorhanden", art: "voraussetzung", check: {"tag": "AJT", "qual": "A01", "neg": false} },
  "101": { text: "Wenn in dieser SG7 AJT DE1082 = E_0566", art: "voraussetzung" },
  "102": { text: "Wenn in dieser SG7 AJT DE1082 = E_0568", art: "voraussetzung" },
  "103": { text: "Wenn in dieser SG12 AJT DE1082 = E_0566", art: "voraussetzung" },
  "104": { text: "Wenn in dieser SG12 AJT DE1082 = E_0568", art: "voraussetzung" },
  "105": { text: "Wenn in diesem AJT DE1082 = E_0270", art: "voraussetzung" },
  "106": { text: "Wenn in diesem AJT DE1082 = E_0273", art: "voraussetzung" },
  "107": { text: "Wenn in diesem AJT DE1082 = E_0276", art: "voraussetzung" },
  "108": { text: "Wenn in diesem AJT DE1082 = E_0277", art: "voraussetzung" },
  "109": { text: "Wenn in dieser SG7 AJT DE4465 = A01/A21/A22/ A23/A90/A96", art: "voraussetzung" },
  "110": { text: "Wenn in dieser SG7 AJT DE1082 = E_0270", art: "voraussetzung" },
  "111": { text: "Wenn in dieser SG7 AJT DE1082 = E_0273", art: "voraussetzung" },
  "112": { text: "Wenn in dieser SG7 AJT DE1082 = E_0276", art: "voraussetzung" },
  "113": { text: "Wenn in dieser SG7 AJT DE1082 = E_0277", art: "voraussetzung" },
  "114": { text: "Wenn in dieser SG12 AJT DE1082 = E_0270", art: "voraussetzung" },
  "115": { text: "Wenn in dieser SG12 AJT DE1082 = E_0273", art: "voraussetzung" },
  "116": { text: "Wenn in dieser SG12 AJT DE1082 = E_0276", art: "voraussetzung" },
  "117": { text: "Wenn in dieser SG12 AJT DE1082 = E_0277", art: "voraussetzung" },
  "118": { text: "Wenn SG7 AJT+A99+E_0272 vorhanden", art: "voraussetzung" },
  "119": { text: "Wenn SG7 AJT+A99+E_0275 vorhanden", art: "voraussetzung" },
  "120": { text: "Wenn in dieser SG7 AJT DE4465 = A01", art: "voraussetzung" },
  "121": { text: "Wenn SG7 AJT+A08/ A99+E_3038 vorhanden", art: "voraussetzung" },
  "490": { text: "wenn Wert in diesem DE, an der Stelle CCYYMMDDHHMM ein Zeitpunkt aus dem angegeben Zeitraum der Tabelle Kapitel 3.5 „Übersicht gesetzliche deutsche Sommerzeit (MESZ)“ der Spalten:\n›\t„Sommerzeit (MESZ) von“ Darstellung in UTC und\n›\t„Sommerzeit (MESZ) bis“ Darstellung in UTC ist.", art: "voraussetzung" },
  "491": { text: "wenn Wert in diesem DE, an der Stelle CCYYMMDDHHMM ein Zeitpunkt aus dem angegeben Zeitraum der Tabelle Kapitel 3.6 „Übersicht gesetzliche deutsche Zeit (MEZ)“ der Spalten: \n›\t„Winterzeit (MEZ) von“ Darstellung in UTC und\n›\t„Winterzeit (MEZ) bis“ Darstellung in UTC ist.", art: "voraussetzung" },
  "492": { text: "Wenn MP-ID in NAD+MR (Nachrichtenempfänger) aus Sparte Strom", art: "voraussetzung" },
  "493": { text: "Wenn MP-ID in NAD+MR (Nachrichtenempfänger) aus Sparte Gas", art: "voraussetzung" },
  "501": { text: "Hinweis: An dieser Stelle ist der Betrag aus SG50 MOA+9 der zugrundeliegenden INVOIC zu übernehmen.", art: "hinweis" },
  "502": { text: "Hinweis: Bei positivem Betrag ergibt sich eine Forderung des Rechnungsstellers. Bei negativem Betrag ergibt sich eine Forderung für den Rechnungsempfänger.", art: "hinweis" },
  "503": { text: "Hinweis: Empfohlen, um bei Abweisung Ansprechpartner für Rückfragen zu erreichen.", art: "hinweis" },
  "510": { text: "Hinweis: Bei Ablehnung einer vorherigen COMDIS", art: "hinweis" },
  "511": { text: "Hinweis: BGM DE1004 aus der abgelehnten INVOIC- Nachricht", art: "hinweis" },
  "512": { text: "Hinweis: BGM DE1004 aus der abgelehnten COMDIS-Nachricht", art: "hinweis" },
  "515": { text: "Hinweis: BGM DE1004 aus der bestätigten INVOIC- Nachricht", art: "hinweis" },
  "517": { text: "Hinweis: Wenn in dieserSG5 in AJT DE4465 ein Code aus Cluster Ablehnung auf Summenebene verwendet wird, ist diese SG7 so oft zu wiederholen, bis alle Fehler der Summenebene genannt sind.", art: "hinweis" },
  "518": { text: "Hinweis: Wenn in dieser SG5 in AJT DE4465 ein Code aus Cluster Ablehnung auf Kopfebene verwendet wird, der von A80 abweicht, ist diese SG7 genau einmal zu nutzen.", art: "hinweis" },
  "519": { text: "Hinweis: Diese SG7 ist so oft mit AJT DE4465 = A74 zu wiederholen, bis alle Rechnungsnummern im RFF- Segment dieser SG7 genannt sind, die in der INVOIC fehlen, die in diesem SG5 DOC DE1004 genannt ist", art: "hinweis" },
  "520": { text: "Hinweis: Diese SG7 ist so oft mit AJT DE4465 = A75 zu wiederholen, bis alle Rechnungsnummern der Rechnungen genannt sind, die mindestens eine Abschlagsrechnung enthalten, die in der INVOIC abgerechnet wurden, die in diesem SG5 DOC DE1004 genannt ist.", art: "hinweis" },
  "521": { text: "Hinweis: Diese SG7 ist so oft mit AJT DE4465 = A76 zu wiederholen, bis alle Rechnungsnummern der Abschlagsrechnungen genannt sind, die in der INVOIC, die in diesem SG5 DOC DE1004 genannt ist, nicht hätten berücksichtigt werden dürfen.", art: "hinweis" },
  "523": { text: "Hinweis: Jede Rechnungsnummer einer Abschlagsrechnung muss in einem separaten DE4440 angegeben werden. Reichen die fünf DE4440 für die Rechnungsnummern aller anzugebenden Abschlagrechnungen nicht aus, ist das FTX+Z14 zu wiederholen.", art: "hinweis" },
  "525": { text: "Hinweis: Diese SG10 ist so oft zu wiederholen, bis alle Fehler der Positionsebene genannt sind.", art: "hinweis" },
  "526": { text: "Hinweis: Wert aus DE1082 der SG26 in der sich der nachfolgende Fehler in der INVOIC befindet, die in diesem SG5 DOC DE1004 genannt ist.", art: "hinweis" },
  "529": { text: "Hinweis: Wenn in dieser SG7 AJT DE4465 = A75 vorhanden, dann dürfen in den DE4440 dieses FTX- Segments nur Abschlagsrechnungsnummern genannt sein, welche in der Rechnung enthalten sind, deren Nummer in dieser SG7in SG7 RFF+AFL angegeben ist.", art: "hinweis" },
  "533": { text: "Hinweis: Wenn in dieser SG12 AJT DE4465 = AA1/ AA6/AA7/AB8/AD6, ist diese SG12 so oft mit AJT DE4465 = Code zu wiederholen, bis alle Rechnungsnummern im RFF- Segment dieser SG12 genannt sind.", art: "hinweis" },
  "534": { text: "Hinweis: Wenn in dieser SG12 AJT DE4465 = A34/ A39/AA2/AB2, ist diese SG12 ist so oft mit AJT DE4465 = Code zu wiederholen, bis alle Nummern der Reklamationen im RFF-Segment dieser SG12 genannt sind.", art: "hinweis" },
  "535": { text: "Hinweis: Diese SG7 ist so oft mit AJT DE4465 = A80 zu wiederholen, bis die Rechnungsnummern der nicht stornierten Sonderrechnungen mit derselben Sonderrechnungsart wie sie in Sonderrechnung genannt ist die in diesem SG5 DOC DE1004 genannt ist, und sich auf dieselbe Rechnung beziehen, die die in diesem SG5 DOC DE1004 genannt ist.", art: "hinweis" },
  "536": { text: "Hinweis: Dieses DE darf keine Abschlagsrechnungsnummer enthalten", art: "hinweis" },
  "537": { text: "Hinweis: Diese SG7 ist sooft mit AJT DE4465 = AC5 zu wiederholen, bis alle Rechnungsnummern im RFF Segment dieser SG7 genannt sind, die in der INVOIC berücksichtigt werden sollten, die in diesem SG5 DOC DE1004 genannt ist, aber mindestens eine davon offensichtlich nicht berücksichtigt wurde.", art: "hinweis" },
  "538": { text: "Hinweis: Jede Positionsnummer eines Angebotes muss in einem separaten DE4440 angegebenwerden. Reichen die fünf DE4440 für die Positionsnummern aller anzugebenden Angebote nicht aus, ist das SG7 FTX+Z16 zu wiederholen.", art: "hinweis" },
  "544": { text: "Hinweis: Wenn in dieser SG7 AJT DE4465 = A21 vorhanden, dann darf in den DE4440 dieses FTX-Segments jeweils nur eine Positionsnummer genannt sein, welche aus dem bestätigten Angebot nicht in der Rechnung enthalten sind.", art: "hinweis" },
  "548": { text: "Hinweis: Die Befüllung des Datenelements ergibt sich aus dem zugehörigen EBD.", art: "hinweis" },
  "549": { text: "Hinweis: Es darf nur eine Information im DE3148 übermittelt werden", art: "hinweis" },
  "926": { text: "Format: Möglicher Wert: 0", art: "format" },
  "930": { text: "Format: max. 2 Nachkommastellen", art: "format" },
  "931": { text: "Format: ZZZ = +00", art: "format" },
  "932": { text: "Format: HHMM = 2200", art: "format" },
  "933": { text: "Format: HHMM = 2300", art: "format" },
  "934": { text: "Format: HHMM = 0400", art: "format" },
  "935": { text: "Format: HHMM = 0500", art: "format" },
  "939": { text: "Format: Die Zeichenkette muss die Zeichen @ und . enthalten", art: "format" },
  "940": { text: "Format: Die Zeichenkette muss mit dem Zeichen + beginnen und danach dürfen nur noch Ziffern folgen", art: "format" },
};
if (typeof window!=='undefined') window.EdiBedingungen = Object.assign(window.EdiBedingungen||{}, remadvBedingungen);
if (typeof module!=='undefined') module.exports = remadvBedingungen;
