// _bedingungen.js (PARTIN) - AHB-Bedingungen via kohlrahbi-Parser (an unser docx-Layout adaptiert).
// parse_conditions_from_string (kohlrahbi/Hochfrequenz), Quelle AHB_PARTIN_1.0f_20260401_20260930_20260401_ooox_11943.docx.
var partinBedingungen = {
  "1": { text: "Nur MP-ID aus Sparte Strom", art: "voraussetzung" },
  "2": { text: "Wenn der Code im DE3207 in der \"EDI@Energy Codeliste der europäischen Ländercodes\" in der Spalte \"PLZ vorhanden\" ein \"X\" enthält", art: "voraussetzung" },
  "3": { text: "wenn vorhanden", art: "voraussetzung" },
  "4": { text: "Wenn Vorgängerversion vorhanden", art: "voraussetzung" },
  "5": { text: "Wenn MP-ID in SG2 NAD+MR (Nachrichtenempfänger) in der Rolle LF", art: "voraussetzung" },
  "6": { text: "wenn im DE3155 im demselben COM der Code EM vorhanden ist", art: "voraussetzung" },
  "7": { text: "wenn im DE3155 im demselben COM der Code TE / FX / AJ / AL vorhanden ist", art: "voraussetzung" },
  "8": { text: "wenn im DE3155 im demselben COM der Code TE / FX vorhanden ist", art: "voraussetzung" },
  "9": { text: "Wenn die Kommunikationsdaten vom Absender nicht mehr aktiv sind.", art: "voraussetzung" },
  "10": { text: "Wenn BGM DE1373 = 11 (Dokument nicht verfügbar) nicht vorhanden", art: "voraussetzung" },
  "11": { text: "Wenn SG4 NAD+SU (Lieferant) DE3207 mit Code „DE“ vorhanden", art: "voraussetzung" },
  "12": { text: "Wenn SG4 NAD+DDM (Netzbetreiber) DE3207 mit Code „DE“ vorhanden", art: "voraussetzung" },
  "13": { text: "Wenn SG4 NAD+DEB (Messstellenbetreiber) DE3207 mit Code „DE“ vorhanden", art: "voraussetzung" },
  "14": { text: "Wenn SG4 NAD+SU (Lieferant) DE3207 der Code „DE“ nicht vorhanden ist", art: "voraussetzung" },
  "15": { text: "Wenn SG4 NAD+DDM (Netzbetreiber) DE3207 der Code „DE“ nicht vorhanden ist", art: "voraussetzung" },
  "16": { text: "Wenn SG4 NAD+DEB (Messstellenbetreiber) DE3207 der Code „DE“ nicht vorhanden ist", art: "voraussetzung" },
  "17": { text: "Wenn MP-ID in SG2 NAD+MR (Nachrichtenempfänger) in der Rolle LF/NB/MSB", art: "voraussetzung" },
  "18": { text: "Wenn MP-ID in SG2 NAD+MR (Nachrichtenempfänger) in der Rolle LF/MSB", art: "voraussetzung" },
  "19": { text: "Wenn MP-ID in SG2 NAD+MR (Nachrichtenempfänger) in der Rolle LF/MSB/NB/ÜNB", art: "voraussetzung" },
  "20": { text: "Wenn MP-ID in SG2 NAD+MR (Nachrichtenempfänger) in der Rolle LF/MSB/ÜNB", art: "voraussetzung" },
  "21": { text: "Wenn MP-ID in SG2 NAD+MR (Nachrichtenempfänger) in der Rolle LF/NB/ESA", art: "voraussetzung" },
  "22": { text: "Wenn MP-ID in SG2 NAD+MR (Nachrichtenempfänger) in der Rolle MSB", art: "voraussetzung" },
  "23": { text: "Wenn MP-ID in SG2 NAD+MR (Nachrichtenempfänger) in der Rolle NB/ÜNB", art: "voraussetzung" },
  "24": { text: "Wenn MP-ID in SG2 NAD+MR (Nachrichtenempfänger) in der Rolle NB/LF/MSB/ESA", art: "voraussetzung" },
  "25": { text: "Wenn MP-ID in SG2 NAD+MR (Nachrichtenempfänger) in der Rolle NB", art: "voraussetzung" },
  "26": { text: "Wenn MP-ID in SG2 NAD+MR (Nachrichtenempfänger) in der Rolle NB/LF/BKV/BIKO", art: "voraussetzung" },
  "27": { text: "Wenn SG4 NAD+Z31 (Übertragungsnetzbetreiber) DE3207 mit Code „DE“ vorhanden", art: "voraussetzung" },
  "28": { text: "Wenn SG4 NAD+Z34 (Bilanzkoordinator) DE3207 mit Code „DE“ vorhanden", art: "voraussetzung" },
  "29": { text: "Wenn SG4 NAD+Z35 (Bilanzkreisverantwortlicher) DE3207 mit Code „DE“ vorhanden", art: "voraussetzung" },
  "30": { text: "Wenn SG4 NAD+Z36 (Energieserviceanbieter) DE3207 mit Code „DE“ vorhanden", art: "voraussetzung" },
  "31": { text: "Wenn SG4 NAD+Z31 (Übertragungsnetzbetreiber) DE3207 mit Code „DE“ nicht vorhanden", art: "voraussetzung" },
  "32": { text: "Wenn SG4 NAD+Z34 (Bilanzkoordinator) DE3207 mit Code „DE“ nicht vorhanden", art: "voraussetzung" },
  "33": { text: "Wenn SG4 NAD+Z35 (Bilanzkreisverantwortlicher) DE3207 mit Code „DE“ nicht vorhanden", art: "voraussetzung" },
  "34": { text: "Wenn SG4 NAD+Z36 (Energieserviceanbieter) DE3207 mit Code „DE“ nicht vorhanden", art: "voraussetzung" },
  "35": { text: "Wenn MP-ID in SG2 NAD+MR (Nachrichtenempfänger) in der Rolle ÜNB", art: "voraussetzung" },
  "36": { text: "Wenn MP-ID in SG2 NAD+MR (Nachrichtenempfänger) in der Rolle BKV", art: "voraussetzung" },
  "41": { text: "Nur MP-ID aus Sparte Gas", art: "voraussetzung" },
  "43": { text: "Wenn SG4 NAD+Z71 (Marktgebietsverantwortlicher) DE3207 mit Code „DE“ vorhanden", art: "voraussetzung" },
  "44": { text: "Wenn SG4 NAD+Z71 (Marktgebietsverantwortlicher) DE3207 mit Code „DE“ nicht vorhanden", art: "voraussetzung" },
  "45": { text: "Wenn MP-ID in SG2 NAD+MR (Nachrichtenempfänger) in der Rolle LF/NB", art: "voraussetzung" },
  "46": { text: "Wenn MP-ID in SG2 NAD+MR (Nachrichtenempfänger) in der Rolle LF/MSB/MGV", art: "voraussetzung" },
  "49": { text: "Wenn MP-ID in SG2 NAD+MR (Nachrichtenempfänger) in der Rolle LF/MGV", art: "voraussetzung" },
  "50": { text: "Wenn MP-ID in SG2 NAD+MR (Nachrichtenempfänger) in der Rolle LF/MGV/NB", art: "voraussetzung" },
  "494": { text: "Das hier genannte Datum muss der Zeitpunkt sein, zu dem das Dokument erstellt wurde, oder ein Zeitpunkt, der davor liegt.", art: "voraussetzung" },
  "500": { text: "Hinweis: Es kann der Firmenname eines Dienstleisters oder die identische Firmenbezeichnung aus SG4 NAD+SU / DDM / DEB / Z31 / Z34 / Z35 / Z36 / Z71 eingetragen werden.", art: "hinweis" },
  "501": { text: "Hinweis: Es darf kein Name einer natürlichen Person übermittelt werden, stattdessen ist die organisatorische Einheit im Unternehmen zu nennen.", art: "hinweis" },
  "502": { text: "Hinweis: Es darf nur eine Information im DE3148 übermittelt werden", art: "hinweis" },
  "503": { text: "Hinweis: Angabe erfolgt in gesetzlicher deutscher Zeit", art: "hinweis" },
  "504": { text: "Hinweis: Es ist mindestens die Umsatzsteuer- bzw. Steuernummer zu nennen, die in der INVOIC genutzt wird.", art: "hinweis" },
  "505": { text: "Wenn eine Vorgängerversion (RFF+ACW) angegeben ist, so muss der Wert in diesem DE1056 mindestens um 1 höher sein, als der Wert aus DE1056 der Vorgängerversion (RFF+ACW).", art: "hinweis" },
  "506": { text: "Hinweis: Das Datenelement ist so zu füllen, dass sein Inhalt den Vorgaben des USt.-Gesetzes genügt, so dass der Empfänger diese Daten in einer INVOIC nutzen kann.", art: "hinweis" },
  "508": { text: "Hinweis: Der LF in seiner Funktion als Grund- und Ersatzversorger muss den NB, in deren Netzgebiet der LF als Grund- und Ersatzversorger ist, einen Bilanzkreis für verbrauchende Marktlokationen übermitteln, um dem NB die Möglichkeit zu geben, eine Zuordnung bei fehlender Antwort auf die EoG Anmeldung durchführen zu können.", art: "hinweis" },
  "908": { text: "Format: Mögliche Werte: 1 bis n", art: "format" },
  "931": { text: "Format: ZZZ = +00", art: "format" },
  "939": { text: "Format: Die Zeichenkette muss die Zeichen @ und . enthalten", art: "format" },
  "940": { text: "Format: Die Zeichenkette muss mit dem Zeichen + beginnen und danach dürfen nur noch Ziffern folgen", art: "format" },
};
if (typeof window!=='undefined') window.EdiBedingungen = Object.assign(window.EdiBedingungen||{}, partinBedingungen);
if (typeof module!=='undefined') module.exports = partinBedingungen;
