// _bedingungen.js (ORDRSP) - AHB-Bedingungen via kohlrahbi-Parser (an unser docx-Layout adaptiert).
// parse_conditions_from_string (kohlrahbi/Hochfrequenz), Quelle AHB_ORDRSP_1.1a_20260401_20260930_20260401_ooox_11937.docx.
var ordrspBedingungen = {
  "1": { text: "Wenn BGM+7 vorhanden", art: "voraussetzung", check: {"tag": "BGM", "qual": "7", "neg": false} },
  "3": { text: "Wenn MP-ID in SG3 NAD+MS mit Rolle NB vorhanden", art: "voraussetzung" },
  "4": { text: "Wenn MP-ID in SG3 NAD+MR mit Rolle LF vorhanden", art: "voraussetzung" },
  "5": { text: "Wenn MP-ID in SG3 NAD+MS mit Rolle LF vorhanden", art: "voraussetzung" },
  "7": { text: "Wenn MP-ID in SG3 NAD+MR aus Sparte Strom", art: "voraussetzung" },
  "9": { text: "Wenn MP-ID in SG3 NAD+MS mit Rolle LF vorhanden", art: "voraussetzung" },
  "10": { text: "Wenn MP-ID in SG3 NAD+MS mit Rolle MSB vorhanden", art: "voraussetzung" },
  "11": { text: "Wenn AJT+A09+E_0470 vorhanden", art: "voraussetzung" },
  "12": { text: "Wenn der NB eine unverbindliche Preisinformation angeben kann", art: "voraussetzung" },
  "13": { text: "Wenn MP-ID in SG3 NAD+MR aus Sparte Gas", art: "voraussetzung" },
  "14": { text: "Wenn MP-ID in SG3 NAD+MR mit Rolle MSB vorhanden", art: "voraussetzung" },
  "15": { text: "Wenn MP-ID in SG3 NAD+MR mit Rolle NB vorhanden", art: "voraussetzung" },
  "16": { text: "Wenn MP-ID in SG3 NAD+MR mit Rolle ÜNB vorhanden", art: "voraussetzung" },
  "17": { text: "Der hier angegebene Code des Prüfschritts muss im EBD dem Cluster Zustimmung zugeordnet sein", art: "voraussetzung" },
  "18": { text: "Der hier angegebene Code des Prüfschritts muss im EBD dem Cluster Ablehnung zugeordnet sein", art: "voraussetzung" },
  "21": { text: "Wenn IMD++Z01 vorhanden", art: "voraussetzung", check: {"tag": "IMD", "qual": "Z01", "neg": false} },
  "22": { text: "Wenn IMD++Z02 vorhanden", art: "voraussetzung", check: {"tag": "IMD", "qual": "Z02", "neg": false} },
  "23": { text: "Wenn IMD++Z03 vorhanden", art: "voraussetzung", check: {"tag": "IMD", "qual": "Z03", "neg": false} },
  "24": { text: "Wenn BGM+Z51 vorhanden", art: "voraussetzung", check: {"tag": "BGM", "qual": "Z51", "neg": false} },
  "25": { text: "Wenn BGM+Z52 vorhanden", art: "voraussetzung", check: {"tag": "BGM", "qual": "Z52", "neg": false} },
  "27": { text: "Wenn AJT+A05+E_0470 vorhanden", art: "voraussetzung" },
  "28": { text: "Wenn AJT+A99 vorhanden", art: "voraussetzung", check: {"tag": "AJT", "qual": "A99", "neg": false} },
  "29": { text: "MP-ID nur aus Sparte Gas", art: "voraussetzung" },
  "30": { text: "MP-ID nur aus Sparte Strom", art: "voraussetzung" },
  "31": { text: "MP-ID mit Rolle MSB", art: "voraussetzung" },
  "32": { text: "MP-ID mit Rolle NB", art: "voraussetzung" },
  "33": { text: "Wenn AJT+A02/A03+E_0488 vorhanden", art: "voraussetzung" },
  "34": { text: "wenn vorhanden", art: "voraussetzung" },
  "37": { text: "Wenn in dieser Nachricht das SG8 CUX+2 vorhanden", art: "voraussetzung" },
  "38": { text: "Möglicher Wert: ZB4 oder ZB5", art: "voraussetzung" },
  "39": { text: "Möglicher Wert: E17 oder Z07", art: "voraussetzung" },
  "40": { text: "Wenn der Code im DE3207 in der \"EDI@Energy Codeliste der europäischen Ländercodes\" in der Spalte \"PLZ vorhanden\" ein \"X\" enthält", art: "voraussetzung" },
  "41": { text: "wenn SG2 AJT (Einzelheiten zu einer Anpassung/Änderung) DE4465 mit Wert ZB5 vorhanden", art: "voraussetzung" },
  "42": { text: "Wenn SG2 AJT+Z07 (Antwortkategorie: Ablehnung (Keine Berechtigung)) vorhanden", art: "voraussetzung" },
  "43": { text: "Wenn AJT+A02/A03+E_1001 vorhanden", art: "voraussetzung" },
  "44": { text: "Wenn AJT+A05+E_1000 vorhanden", art: "voraussetzung" },
  "45": { text: "Wenn AJT+A09+E_1000 vorhanden", art: "voraussetzung" },
  "46": { text: "Wenn AJT+A06+E_0552 vorhanden", art: "voraussetzung" },
  "47": { text: "Wenn AJT+A06+E_0553 vorhanden", art: "voraussetzung" },
  "48": { text: "Wenn AJT+A06+E_0554 vorhanden", art: "voraussetzung" },
  "49": { text: "nur, wenn in ursprünglicher Nachricht IMD++Z60 (Abbestellung Messprodukt mit Zählzeitdefinition des LF) vorhanden war", art: "voraussetzung" },
  "50": { text: "wenn im DE3155 in demselben COM der Code EM vorhanden ist", art: "voraussetzung" },
  "51": { text: "wenn im DE3155 in demselben COM der Code TE / FX / AJ / AL vorhanden ist", art: "voraussetzung" },
  "52": { text: "wenn es sich bei der Reklamation um die Reklamation der ausgerollten Leistungskurvendefinitionen handelte", art: "voraussetzung" },
  "53": { text: "Vorgangsnummer aus IDE DE7402 der UTILTS mit BGM+Z59", art: "voraussetzung" },
  "54": { text: "Vorgangsnummer aus IDE DE7402 der UTILTS mit BGM+Z80", art: "voraussetzung" },
  "55": { text: "Vorgangsnummer aus IDE DE7402 der UTILTS mit BGM+Z81", art: "voraussetzung" },
  "56": { text: "wenn SG2 AJT+A02/A03/A06/A07/A10/A11+E_0548 vorhanden", art: "voraussetzung" },
  "57": { text: "wenn SG2 AJT+A02/A03/A06/A07/A10/A11+E_0549 vorhanden", art: "voraussetzung" },
  "58": { text: "wenn SG2 AJT+A02/A03/A06/A07+E_0550 vorhanden", art: "voraussetzung" },
  "59": { text: "wenn SG2 AJT+A02/A03/A06/A07/A10/A11+E_0551 vorhanden", art: "voraussetzung" },
  "60": { text: "wenn es sich bei der Reklamation um die Reklamation der Übersicht der Zählzeitdefinitionen handelte", art: "voraussetzung" },
  "61": { text: "wenn es sich bei der Reklamation um die Reklamation der Übersicht der Schaltzeitdefinitionen handelte", art: "voraussetzung" },
  "62": { text: "wenn es sich bei der Reklamation um die Reklamation der Übersicht der Leistungskurvendefinitionen handelte", art: "voraussetzung" },
  "63": { text: "Dokumentennummer aus BGM+Z60 DE1004 der UTILTS", art: "voraussetzung" },
  "64": { text: "Dokumentennummer aus BGM+Z78 DE1004 der UTILTS", art: "voraussetzung" },
  "65": { text: "Dokumentennummer aus BGM+Z79 DE1004 der UTILTS", art: "voraussetzung" },
  "66": { text: "wenn SG2 AJT+A01/A02/A03+E_0544 vorhanden", art: "voraussetzung" },
  "67": { text: "wenn SG2 AJT+A01/A02/A03+E_0545 vorhanden", art: "voraussetzung" },
  "68": { text: "wenn SG2 AJT+A02/A03+E_0546 vorhanden", art: "voraussetzung" },
  "69": { text: "wenn SG2 AJT+A01/A02/A03+E_0547 vorhanden", art: "voraussetzung" },
  "70": { text: "wenn es sich bei der Reklamation um die Reklamation der ausgerollten Zählzeitdefinitionen handelte", art: "voraussetzung" },
  "71": { text: "wenn es sich bei der Reklamation um die Reklamation der ausgerollten Schaltzeitdefinitionen handelte", art: "voraussetzung" },
  "72": { text: "wenn AJT+A04+E_0552 vorhanden", art: "voraussetzung" },
  "73": { text: "wenn AJT+A04+E_0553 vorhanden", art: "voraussetzung" },
  "74": { text: "wenn AJT+A04+E_0554 vorhanden", art: "voraussetzung" },
  "75": { text: "Wenn es sich um die Antwort auf eine Bestellung handelt in der ein Messprodukt der Codeliste der Konfigurationen aus dem Kapitel 4.6.2 „Werte nach Typ 2 aus SMGW“ bestellt wurde.", art: "voraussetzung" },
  "76": { text: "Wenn FTX+Z27 (IP-Adresse des Absenders) nicht vorhanden", art: "voraussetzung" },
  "77": { text: "Wenn FTX+Z28 (IP-Range des Absenders) nicht vorhanden", art: "voraussetzung" },
  "78": { text: "Wenn AJT+A04+E_0279 vorhanden", art: "voraussetzung" },
  "79": { text: "Wenn AJT+A04+E_0283 vorhanden", art: "voraussetzung" },
  "80": { text: "Wenn AJT+A05+E_0279 vorhanden", art: "voraussetzung" },
  "81": { text: "Wenn AJT+A05+E_0283 vorhanden", art: "voraussetzung" },
  "82": { text: "Wenn BGM+Z93 (Bestellung eines Angebots Änderung der Technik der Lokation) vorhanden", art: "voraussetzung" },
  "83": { text: "Wenn BGM+Z12 (Änderung der Technik der Lokation) vorhanden", art: "voraussetzung" },
  "492": { text: "wenn MP-ID in NAD+MR aus Sparte Strom", art: "voraussetzung" },
  "493": { text: "wenn MP-ID in NAD+MR aus Sparte Gas", art: "voraussetzung" },
  "494": { text: "Das hier genannte Datum muss der Zeitpunkt sein, zu dem das Dokument erstellt wurde, oder ein Zeitpunkt, der davor liegt.", art: "voraussetzung" },
  "500": { text: "Hinweis: Angabe eines technischen Ansprechpartners für die Geräteübernahme", art: "hinweis" },
  "503": { text: "Hinweis: Datum, bis zu dem der MSBA zur Fortführung verpflichtet wurde", art: "hinweis" },
  "504": { text: "Hinweis: Ggf. korrigiert bei einer Zeitangabe in der ORDERS, die außerhalb des max. möglichen Weiterverpflichtungszeitraums ist. Als Antwort wird dann in SG2 AJT Zustimmung mit Terminänderung angegeben.", art: "hinweis" },
  "513": { text: "Hinweis: Wert aus BGM+Z12 (Änderung der Technik der Lokation) DE1004 der ORDERS, mit der die Bestellung erfolgt ist.", art: "hinweis" },
  "518": { text: "Hinweis: Wert aus BGM+Z10 DE1004 der ORDERS, mit der die Bestellung erfolgt ist", art: "hinweis" },
  "519": { text: "Hinweis: Wert aus BGM+7 DE1004 der ORDERS, mit der die Bestellung erfolgt ist.", art: "hinweis" },
  "520": { text: "Hinweis: Wert aus BGM+Z29 DE1004 der ORDERS, mit der die Anfrage zur Beendigung der Rechnungsabwicklung erfolgt ist.", art: "hinweis" },
  "521": { text: "Hinweis: Wert aus BGM+Z14/Z61/Z62 DE1004 der ORDERS, mit der die Anforderung von Stammdaten erfolgt ist", art: "hinweis" },
  "522": { text: "Hinweis: Wert aus BGM+7/Z28/Z48 DE1004 der ORDERS, mit der die Anforderung von Werten erfolgt ist.", art: "hinweis" },
  "523": { text: "Hinweis: Wert aus BGM+7 DE1004 der ORDERS, mit der die Anforderung Anforderung von Brennwert und Zustandszahl erfolgt ist.", art: "hinweis" },
  "524": { text: "Hinweis: Wert aus BGM+Z14 DE1004 der ORDERS, mit der die Anfrage vom MSB Gas erfolgt ist.", art: "hinweis" },
  "525": { text: "Hinweis: Wert aus BGM+Z24 DE1004 der ORDERS, mit der die Anforderung Allokationsliste erfolgt ist", art: "hinweis" },
  "526": { text: "Hinweis: Wert aus BGM+Z23 DE1004 der ORDERS, mit der die Anforderung bilanzierte Menge erfolgt ist", art: "hinweis" },
  "527": { text: "Hinweis: Wert aus BGM+Z34 DE1004 der ORDERS, mit der die Reklamation von Werten erfolgt ist.", art: "hinweis" },
  "529": { text: "Hinweis: Dokumentennummer aus BGM DE1004 der ORDERS", art: "hinweis" },
  "530": { text: "Hinweis: Dokumentennummer aus BGM DE1004 der ORDCHG", art: "hinweis" },
  "533": { text: "Hinweis: Wert aus BGM+Z51 DE1004 der ORDCHG", art: "hinweis" },
  "534": { text: "Hinweis: Wert aus BGM+Z52 DE1004 der ORDCHG", art: "hinweis" },
  "535": { text: "Hinweis: Wert aus BGM+Z13 DE1004 der ORDERS, mit der die Ankündigung Gerätewechselabsicht erfolgt ist.", art: "hinweis" },
  "536": { text: "Hinweis: Es ist die MP-ID des Eigentümers (MSB) zur bilateralen Klärung anzugeben, wenn der angefragte MSB nicht selber der Eigentümer ist.", art: "hinweis" },
  "537": { text: "Hinweis: Wert aus BGM+Z72 DE1004 der ORDERS, mit der die Bestellung Beendigung der Konfiguration erfolgt ist.", art: "hinweis" },
  "538": { text: "Hinweis: Wert aus BGM+Z76 DE1004 der ORDERS, mit der die Reklamation der Konfiguration erfolgt ist.", art: "hinweis" },
  "539": { text: "Hinweis: Wert aus BGM+Z73/Z74 DE1004 der ORDERS, mit der die Bestellung der Konfiguration erfolgt ist.", art: "hinweis" },
  "540": { text: "Hinweis: Es darf nur eine Information im DE3148 übermittelt werden", art: "hinweis" },
  "542": { text: "Hinweis: Wert aus BGM+Z91 DE1004 der ORDERS, mit der die Bestellung Änderung der Abrechnungsdaten erfolgt ist.", art: "hinweis" },
  "543": { text: "Hinweis: Wert aus BGM+Z93 (Bestellung eines Angebots Änderung der Technik der Lokation) DE1004 der ORDERS, mit der die Bestellung erfolgt ist.", art: "hinweis" },
  "544": { text: "Hinweis: Wert aus BGM DE1004 der PRICAT mit der das Preisblatt B des MSB, auf die aus Sicht des MSB das Angebot basiert, übermittelt wurde.", art: "hinweis" },
  "545": { text: "Hinweis: Angabe des Beginnzeitpunkts des realistisch möglichen Umsetzungstermins der zum Zeitpunkt der Ablehnung ermittelt werden kann.", art: "hinweis" },
  "546": { text: "Hinweis: Angabe des Endezeitpunkts des realistisch möglichen Umsetzungstermins der zum Zeitpunkt der Ablehnung ermittelt werden kann.", art: "hinweis" },
  "547": { text: "Hinweis: Wenn es sich um die Bestellung eines vorherigen Angebots im Rahmen der BDEW Anwendungshilfe \"Prozesse zur Änderung der Technik an Lokationen\" handelt.", art: "hinweis" },
  "548": { text: "Hinweis: Hinweis: wenn es sich um die Beauftragung einer Änderung gemäß WiM Teil1 UC \"Messlokationsänderung\" handelt.", art: "hinweis" },
  "902": { text: "Format: Format: Möglicher Wert: ≥ 0", art: "format" },
  "903": { text: "Format: Möglicher Wert: 1", art: "format" },
  "930": { text: "Format: max. 2 Nachkommastellen", art: "format" },
  "931": { text: "Format: ZZZ = +00", art: "format" },
  "939": { text: "Format: Die Zeichenkette muss die Zeichen @ und . enthalten", art: "format" },
  "940": { text: "Format: Die Zeichenkette muss mit dem Zeichen + beginnen und danach dürfen nur noch Ziffern folgen", art: "format" },
  "2036": { text: "Pro Nachricht ist die SG27 genau einmal anzugeben", art: "wiederholbarkeit" },
};
if (typeof window!=='undefined') window.EdiBedingungen = Object.assign(window.EdiBedingungen||{}, ordrspBedingungen);
if (typeof module!=='undefined') module.exports = ordrspBedingungen;
