// _bedingungen.js (QUOTES) - AHB-Bedingungen, extrahiert mit kohlrahbi (Hochfrequenz).
// Offizieller conditions-Scraper, Quelle FV2604.
var quotesBedingungen = {
  "1": { text: "Wenn Position nicht angeboten werden kann, weil rechtliche Regelungen oder Rechte Dritter dem entgegenstehen", art: "voraussetzung" },
  "2": { text: "Wenn in derselben SG27 LIN IMD DE7081 (Produkt-/ Leistungsbeschreibung) mit Code Z09 (Kann nicht angeboten werden) nicht vorhanden.", art: "voraussetzung" },
  "3": { text: "Wenn CCI+++Z64 vorhanden ist", art: "voraussetzung" },
  "4": { text: "Wenn am Gerät vorhanden und abweichend von Gerätenummer", art: "voraussetzung" },
  "5": { text: "Wenn in derselben SG27 LIN die Artikelnummer 9990001000649 vorhanden ist", art: "voraussetzung" },
  "8": { text: "Wenn SG28 CCI+++E13 CAV+EHZ vorhanden", art: "voraussetzung" },
  "9": { text: "Wenn in derselben SG27 LIN die Artikelnummer 9990001000657 vorhanden ist", art: "voraussetzung" },
  "10": { text: "Wenn SG28 CAV+MIW/ MPW/MBW vorhanden", art: "voraussetzung" },
  "11": { text: "Wenn in derselben SG27 LIN die Artikelnummer 9990001000665 vorhanden ist", art: "voraussetzung" },
  "12": { text: "Wenn in derselben SG27 LIN die Artikelnummer 9990001000673 vorhanden ist", art: "voraussetzung" },
  "13": { text: "Wenn am Gerät vorhanden", art: "voraussetzung" },
  "15": { text: "Wenn in derselben SG27 LIN die Artikelnummer 9990001000772 vorhanden ist", art: "voraussetzung" },
  "16": { text: "Wenn in derselben SG27 LIN die Artikelnummer 9990001000780 vorhanden ist", art: "voraussetzung" },
  "17": { text: "Wenn das Angebot per REQOTE angefragt wurde", art: "voraussetzung" },
  "18": { text: "Wenn Angebot mehrere Marktlokationen abdeckt, an welchen der identische Anschlussnutzer vorhanden ist und deren messtechnische Einordnung iMS ist (Marktlokation aus SG11 LOC+172 und alle Marktlokationen, die in einem SG29 RFF+Z18 aufgeführt sind).", art: "voraussetzung" },
  "20": { text: "Wenn IMD++Z33 vorhanden", art: "voraussetzung", check: {"tag": "IMD", "qual": "Z33", "neg": false} },
  "21": { text: "Wenn IMD++Z34 vorhanden", art: "voraussetzung", check: {"tag": "IMD", "qual": "Z34", "neg": false} },
  "22": { text: "Wenn CCI+++Z75 vorhanden ist", art: "voraussetzung" },
  "25": { text: "Wenn SG28 CCI+++E13 CAV+MME vorhanden", art: "voraussetzung" },
  "26": { text: "Wenn DTM+203 nicht vorhanden", art: "voraussetzung", check: {"tag": "DTM", "qual": "203", "neg": true} },
  "27": { text: "Wenn DTM+469 nicht vorhanden", art: "voraussetzung", check: {"tag": "DTM", "qual": "469", "neg": true} },
  "28": { text: "Wenn RFF+AAV vorhanden", art: "voraussetzung", check: {"tag": "RFF", "qual": "AAV", "neg": false} },
  "29": { text: "Wenn DTM+469 in Anfrage (REQOTE) vorhanden war", art: "voraussetzung" },
  "30": { text: "Wenn SG27 IMD+Z09 vorhanden", art: "voraussetzung", check: {"tag": "IMD", "qual": "Z09", "neg": false} },
  "31": { text: "Es sind nur die Artikelnummern erlaubt, die in der Codeliste der Artikelnummern des BDEW mit dem entsprechenden Prüfidentifikator versehen sind.", art: "voraussetzung" },
  "39": { text: "MP-ID nur aus Sparte Strom", art: "voraussetzung" },
  "44": { text: "Wenn MSBA nicht Eigentümer des Gerätes/der Geräte ist", art: "voraussetzung" },
  "49": { text: "Wenn SG27 LIN++Z64 (Erforderliches Produkt Schaltzeitdefinitionen) vorhanden", art: "voraussetzung" },
  "50": { text: "Wenn SG27 LIN++Z65 (Erforderliches Produkt Leistungskurvendefinitionen) vorhanden", art: "voraussetzung" },
  "51": { text: "Wenn SG27 LIN++Z66 (Erforderliches Produkt Ad-hoc- Steuerkanal) vorhanden", art: "voraussetzung" },
  "52": { text: "Wenn SG27 LIN++Z67 (Erforderliches Messprodukt für Werte nach Typ 2 aus Backend) vorhanden", art: "voraussetzung" },
  "53": { text: "Wenn SG27 LIN++Z68 (Erforderliches Produkt Konfigurationserlaubnis für Werte nach Typ2 aus SMGW) vorhanden", art: "voraussetzung" },
  "54": { text: "Wenn in der Anfrage zum Angebot einer Konfiguration vorhanden", art: "voraussetzung" },
  "55": { text: "Wenn in LOC+172 DE3225 (Meldepunkt) die ID einer Marktlokation angegeben ist.", art: "voraussetzung" },
  "56": { text: "Wenn in LOC+172 DE3225 (Meldepunkt) die ID einer Messlokation angegeben ist.", art: "voraussetzung" },
  "57": { text: "Wenn in LOC+172 DE3225 (Meldepunkt) die ID einer Netzlokation angegeben ist.", art: "voraussetzung" },
  "58": { text: "Wenn in LOC+172 DE3225 (Meldepunkt) die ID einer Steuerbaren Ressource angegeben ist.", art: "voraussetzung" },
  "59": { text: "Es sind nur die Konfigurations-Produkte erlaubt, die in der Codeliste derKonfigurationen im Kapitel 4.1 „Konfigurationsprodukte Schaltzeitdefinition“ enthalten sind.", art: "voraussetzung" },
  "60": { text: "Es sind nur die Konfigurations-Produkte erlaubt, die in der Codeliste der Konfigurationen im Kapitel 4.2 „Konfigurationsprodukte Leistungskurvendefinition“ enthalten sind.", art: "voraussetzung" },
  "61": { text: "Es sind nur die Konfigurations-Produkte erlaubt, die in der Codeliste der Konfigurationen im Kapitel 4.3 „Konfigurationsprodukte Ad-hoc- Steuerkanal“ enthalten sind.", art: "voraussetzung" },
  "62": { text: "Es sind nur die Messprodukte erlaubt, die in der Codeliste der Konfigurationen im Kapitel 4.5 „Messprodukte für Werte nach Typ 2 aus Backend für LF und NB“ enthalten sind.", art: "voraussetzung" },
  "63": { text: "Es sind nur die Messprodukte erlaubt, die in der Codeliste der Konfigurationen im Kapitel 4.4 „Messprodukte mit Konfigurationserlaubnis für Werte nach Typ 2 aus SMGW“ enthalten sind.", art: "voraussetzung" },
  "65": { text: "Wenn DTM+203 (Ausführungsdatum) im DE2380 < 202312312300?+00", art: "voraussetzung" },
  "66": { text: "Wenn DTM+469 (Beginn zum (nächstmöglichen Termin)) im DE2380 < 202312312300?+00", art: "voraussetzung" },
  "67": { text: "Wenn DTM+203 (Ausführungsdatum) im DE2380 ≥ 202312312300?+00", art: "voraussetzung" },
  "68": { text: "Wenn DTM+469 (Beginn zum (nächstmöglichen Termin)) im DE2380 ≥ 202312312300?+00", art: "voraussetzung" },
  "69": { text: "Es sind nur Werte aus der EDI@Energy Codeliste der Artikelnummern und Artikel-ID erlaubt, die im Kapitel 3.5 \"Abrechnung Messstellenbetrieb für die Sparte Strom\" genannt sind.", art: "voraussetzung" },
  "70": { text: "Es sind nur die Messprodukt-Position-Codes erlaubt, die in der Codeliste der Konfigurationen im Kapitel 4.7 „Art der Werte für Messprodukte nach Typ 2“ enthalten sind.", art: "voraussetzung" },
  "71": { text: "Wenn innerhalb derselben SG27 LIN im PIA+5 DE7140 (Erforderliches Produkt Konfigurationserlaubnis für Werte nach Typ 2 aus SMGW) ein Produkt angegeben ist, das in der Codeliste der Konfigurationen im Kapitel 4.4 „Messprodukte mit Konfigurationserlaubnis für Werte nach Typ 2 aus SMGW“ in der Spalte \"Auslöser\" mit dem Wert \"Bei Schwellwertunter- / -überschreitung\" gekennzeichnet ist.", art: "voraussetzung" },
  "72": { text: "wenn im DE3155 in demselben COM der Code EM vorhanden ist", art: "voraussetzung" },
  "73": { text: "wenn im DE3155 in demselben COM der Code TE / FX / AJ / AL vorhanden ist", art: "voraussetzung" },
  "74": { text: "Es sind nur die Messprodukte erlaubt, die in der Codeliste der Konfigurationen im Kapitel 4.6.1 \"Werte nach Typ 2 aus Backend\" enthalten sind.", art: "voraussetzung" },
  "75": { text: "Es sind nur die Messprodukte erlaubt, die in der Codeliste der Konfigurationen im Kapitel 4.6.2 \"Werte nach Typ 2 aus SMGW\" enthalten sind.", art: "voraussetzung" },
  "77": { text: "Wenn in der Anfrage nach Werten ein Messprodukt enthalten war, das in der Codeliste der Konfigurationen im Kapitel 4.6.1 \"Werte nach Typ 2 aus Backend\" enthalten ist.", art: "voraussetzung" },
  "78": { text: "Wenn in der Anfrage nach Werten ein Messprodukt enthalten war, das in der Codeliste der Konfigurationen im Kapitel 4.6.2 \"Werte nach Typ 2 aus SMWG\" enthalten ist.", art: "voraussetzung" },
  "79": { text: "Wenn IMD DE7081 (Produkt-/Leistungsbeschreibung) mit Wert Z07 (Kauf) vorhanden.", art: "voraussetzung" },
  "80": { text: "Wenn IMD DE7081 (Produkt-/Leistungsbeschreibung) mit Wert Z08 (Nutzungsüberlassung) vorhanden.", art: "voraussetzung" },
  "81": { text: "Wenn IMD DE7081 (Produkt-/Leistungsbeschreibung) mit Wert Z33 (Angebot auf Basis Preisblatt) vorhanden.", art: "voraussetzung" },
  "82": { text: "Wenn IMD DE7081 (Produkt-/Leistungsbeschreibung) mit Wert Z34 (Individuelles Angebot) vorhanden.", art: "voraussetzung" },
  "83": { text: "Wenn in derselben SG27 LIN ein PIA+Z02 (Artikel-ID) mit einer Artikel-ID im DE7140 bei der die letzten beiden Stellen mit dem Wert \"01\" (Kosten für das Einrichten des Messprodukts) vorhanden ist.", art: "voraussetzung" },
  "84": { text: "Wenn in derselben SG27 LIN ein PIA+Z02 (Artikel-ID) mit einer Artikel-ID im DE7140 bei der die letzten beiden Stellen mit dem Wert \"02\" (Kosten für den Betrieb des Messprodukts) vorhanden ist.", art: "voraussetzung" },
  "85": { text: "Wenn in derselben SG27 LIN ein PIA+Z02 (Artikel-ID) mit einer Artikel-ID im DE7140 bei der die letzten beiden Stellen mit dem Wert \"03\" (Kosten für die anfallenden Transaktionen des Messprodukts) vorhanden ist.", art: "voraussetzung" },
  "86": { text: "Wenn in derselben SG31 PRI (Preisangabe zur Position) das DE5387 mit dem Wert Z01 (Einrichtungspreis) vorhanden ist.", art: "voraussetzung" },
  "87": { text: "Wenn in derselben SG31 PRI (Preisangabe zur Position) das DE5387 mit dem Wert Z02 (Transaktionspreis) vorhanden ist.", art: "voraussetzung" },
  "88": { text: "Wenn in derselben SG31 PRI (Preisangabe zur Position) das DE5387 mit dem Wert Z03 (Betriebspreis) vorhanden ist.", art: "voraussetzung" },
  "90": { text: "Es sind nur die Produkt-Codes erlaubt, die in der Codeliste der Konfigurationen im Kapitel 7 \"Produkte zur Bestellung einer Änderung an einer Lokation\" die in der Spalte \"Ebene\" mit dem Wert \"Messlokation\" vorhanden sind.", art: "voraussetzung" },
  "91": { text: "Es sind nur die Produkt-Codes erlaubt, die in der Codeliste der Konfigurationen im Kapitel 7\"Produkte zur Bestellung einer Änderung an einer Lokation\" die in der Spalte \"Ebene\" mit dem Wert \"Netzlokation\" vorhanden sind.", art: "voraussetzung" },
  "92": { text: "Es sind nur die Produkt-Codes erlaubt, die in der Codeliste der Konfigurationen im Kapitel 7 \"Produkte zur Bestellung einer Änderung an einer Lokation\" die in der Spalte \"Ebene\" mit dem Wert \"Steuerbare Ressource\" vorhanden sind.", art: "voraussetzung" },
  "93": { text: "Wenn RNG+Z03 (verbindliche Mengenangabe) in dieser SG31 nicht vorhanden", art: "voraussetzung" },
  "94": { text: "Wenn RNG+Z04 (unverbindliche Mengenangabe) in dieser SG31 nicht vorhanden", art: "voraussetzung" },
  "490": { text: "wenn Wert in diesem DE, an der Stelle CCYYMMDDHHMM ein Zeitpunkt aus dem angegeben Zeitraum der Tabelle Kapitel 3.5 „Übersicht gesetzliche deutsche Sommerzeit (MESZ)“ der Spalten:\n›\t„Sommerzeit (MESZ) von“ Darstellung in UTC und\n›\t„Sommerzeit (MESZ) bis“ Darstellung in UTC ist.", art: "voraussetzung" },
  "491": { text: "wenn Wert in diesem DE, an der Stelle CCYYMMDDHHMM ein Zeitpunkt aus dem angegeben Zeitraum der Tabelle Kapitel 3.6 „Übersicht gesetzliche deutsche Zeit (MEZ)“ der Spalten: \n›\t„Winterzeit (MEZ) von“ Darstellung in UTC und\n›\t„Winterzeit (MEZ) bis“ Darstellung in UTC ist.", art: "voraussetzung" },
  "492": { text: "wenn MP-ID in NAD+MR aus Sparte Strom", art: "voraussetzung" },
  "493": { text: "wenn MP-ID in NAD+MR aus Sparte Gas", art: "voraussetzung" },
  "494": { text: "Das hier genannte Datum muss der Zeitpunkt sein, zu dem das Dokument erstellt wurde, oder ein Zeitpunkt, der davor liegt.", art: "voraussetzung" },
  "500": { text: "Hinweis: Angabe eines technischen Ansprechpartners für die Geräteübernahme", art: "hinweis" },
  "501": { text: "Hinweis: Verwendung der ID der Marktlokation", art: "hinweis" },
  "502": { text: "Hinweis: Verwendung der ID der Messlokation", art: "hinweis" },
  "503": { text: "Hinweis: Es ist die MP-ID desEigentümers (MSB) zur bilateralen Klärung anzugeben, wenn z. B. der MSBA das Gerät / die Geräte selbst gepachtet hat.", art: "hinweis" },
  "504": { text: "Hinweis: Wert aus BGM+311 DE1004 der REQOTE mit der die Angebotsanfrage erfolgt ist.", art: "hinweis" },
  "505": { text: "Hinweis: Wert aus BGM+Z29 DE1004 der REQOTE, mit der die Anfrage Rechnungsabwicklung erfolgt ist.", art: "hinweis" },
  "506": { text: "Hinweis: Wenn zu einer Position (z. B. Messwandlersatz) mehrere Gerätenummern existieren, sind die Gerätenummern in derselben Position (LIN-Segment) mittels Wiederholung der SG32 RFF+Z09 anzugeben", art: "hinweis" },
  "507": { text: "Hinweis: Verwendung der ID der Tranche", art: "hinweis" },
  "511": { text: "Hinweis: Wert aus BGM+Z74 (Bestellung eines Angebots einer Konfiguration) DE1004 der REQOTE mit der die Anfrage einer Konfiguration erfolgt ist.", art: "hinweis" },
  "512": { text: "Hinweis: Verwendung der ID der Netzlokation", art: "hinweis" },
  "513": { text: "Hinweis: Verwendung der ID der Steuerbaren Ressource", art: "hinweis" },
  "514": { text: "Hinweis: Angabe gemäß Preisblatt des MSB. Bis zu einmal für die Parametrierung, bis zu einmal für den Betrieb und bis zu einmal für die Transaktion, sofern im Preisblatt des MSB vorhanden.", art: "hinweis" },
  "516": { text: "Hinweis: Es darf nur eine Information im DE3148 übermittelt werden", art: "hinweis" },
  "517": { text: "Hinweis: Wert aus BGM+Z93 (Bestellung eines Angebots Änderung der Technik der Lokation) DE1004 der REQOTE mit der die Anfrage Angebot Änderung Technik erfolgt ist.", art: "hinweis" },
  "518": { text: "Hinweis: Angabe gemäß Preisblatt B des MSB.", art: "hinweis" },
  "519": { text: "Hinweis: Wert aus BGM DE1004 der PRICAT mit der das Preisblatt B des MSB, auf dem dieses Angebot basiert, übermittelt wurde.", art: "hinweis" },
  "520": { text: "Hinweis: Angabe des Beginnzeitpunkts des voraussichtlich frühesten Umsetzungstermins, der zum Zeitpunkt der Angebotserstellung ermittelt werden kann.", art: "hinweis" },
  "521": { text: "Hinweis: Angabe des Endezeitpunkts des voraussichtlich frühesten Umsetzungstermins, der zum Zeitpunkt der Angebotserstellung ermittelt werden kann..", art: "hinweis" },
  "903": { text: "Format: Möglicher Wert: 1", art: "format" },
  "906": { text: "Format: max. 3 Nachkommastellen", art: "format" },
  "908": { text: "Format: Mögliche Werte: 1 bis n", art: "format" },
  "911": { text: "Format: Mögliche Werte: 1 bis n, je Nachricht oder Segmentgruppe bei 1 beginnend und fortlaufend aufsteigend", art: "format" },
  "912": { text: "Format: max. 6 Nachkommastellen", art: "format" },
  "914": { text: "Format: Möglicher Wert: > 0", art: "format" },
  "931": { text: "Format: ZZZ = +00", art: "format" },
  "932": { text: "Format: HHMM = 2200", art: "format" },
  "933": { text: "Format: HHMM = 2300", art: "format" },
  "934": { text: "Format: HHMM = 0400", art: "format" },
  "935": { text: "Format: HHMM = 0500", art: "format" },
  "939": { text: "Format: Die Zeichenkette muss die Zeichen @ und . enthalten", art: "format" },
  "940": { text: "Format: Die Zeichenkette muss mit dem Zeichen + beginnen und danach dürfen nur noch Ziffern folgen", art: "format" },
  "942": { text: "Format: n1-n2-n1-n3", art: "format" },
  "950": { text: "Format: Marktlokations-ID", art: "format" },
  "951": { text: "Format: Zählpunktbezeichnung", art: "format" },
  "959": { text: "Format: n13-n2", art: "format" },
  "960": { text: "Format: Netzlokations-ID", art: "format" },
  "961": { text: "Format: SR-ID", art: "format" },
  "962": { text: "Format: max. 6 Vorkommastellen", art: "format" },
  "2042": { text: "Innerhalb dieser LIN- Position muss das PIA+Z02 (Artikel-ID) mindestens ein Mal angegeben werden und kann bis zu drei Mal angegeben werden.", art: "wiederholbarkeit" },
  "2060": { text: "Pro Nachricht ist die SG27 LIN+Z64 (Erforderliches Produkt Schaltzeitdefinitionen) maximal einmal anzugeben", art: "wiederholbarkeit" },
  "2061": { text: "Pro Nachricht ist die SG27 LIN++Z65 (Erforderliches Produkt Leistungskurvendefinitionen) maximal einmal anzugeben", art: "wiederholbarkeit" },
  "2062": { text: "Pro Nachricht ist die SG27 LIN++Z66 (Erforderliches Produkt Ad-hoc-Steuerkanal) maximal einmal anzugeben", art: "wiederholbarkeit" },
  "2063": { text: "Pro Nachricht ist die SG27 LIN++Z67 (Erforderliches Messprodukt für Werte nach Typ 2 aus Backend) maximal einmal anzugeben", art: "wiederholbarkeit" },
  "2064": { text: "Pro Nachricht ist die SG27 LIN++Z68 (Erforderliches Produkt Konfigurationserlaubnis für Werte nach Typ 2 aus SMGW) maximal einmal anzugeben", art: "wiederholbarkeit" },
  "2066": { text: "Diese SG28 ist so oft zu wiederholen, wie zu den unterschiedlichen Messprodukt- Position-Codes zu dem innerhalb derselben SG27 LIN im PIA+5 DE7140 (Erforderliches Produkt Konfigurationserlaubnis für Werte nach Typ 2 aus SMGW) angegebenen Produkt ein Produkt angegeben ist, das in der Codeliste der Konfigurationen im Kapitel 4.4 „Messprodukte mit Konfigurationserlaubnis für Werte nach Typ 2 aus SMGW“ in der Spalte \"Auslöser\" mit dem Wert \"Bei Schwellwertunter- / - überschreitung\" gekennzeichnet ist.", art: "wiederholbarkeit" },
  "2068": { text: "Pro SG27 LIN ist die SG31 PRI genau einmal anzugeben.", art: "wiederholbarkeit" },
  "2069": { text: "Pro SG27 LIN ist die SG31 PRI genau einmal anzugeben. Dabei muss in der SG31 PRI im DE5284 eine Mengenangabe mit dem Code H87 (Stück) im DE6411 angegeben sein.", art: "wiederholbarkeit" },
  "2070": { text: "Pro SG27 LIN ist die SG31 PRI zweimal anzugeben. Dabei muss genau eine SG31 PRI mit Preis- und Mengenangabe und dem Code H87 (Stück) im DE6411 und genau eine SG31 PRI mit Preis- und Mengenangabe unddem Code DAY (Tag) im DE6411 vorhanden sein.", art: "wiederholbarkeit" },
  "2071": { text: "Diese SG31 PRI (Preisangabe zur Position) ist bis zu dreimal anzugeben. Es ist so oftanzugeben, wie innerhalb derselben SG27 LIN (Erforderliches Messprodukt für Werte nach Typ2 aus Backend) das PIA+Z02 (Artikel-ID) vorhanden ist.", art: "wiederholbarkeit" },
  "2072": { text: "Diese SG31 PRI (Preisangabe zur Position) ist bis zu dreimal anzugeben. Es ist so oft anzugeben, wie innerhalb derselben SG27 LIN (Erforderliches Produkt Konfigurationserlaubnis für Werte nach Typ 2 aus SMGW) das PIA+Z02 (Artikel-ID) vorhanden ist.", art: "wiederholbarkeit" },
  "2073": { text: "Das PIA (OBIS-Kennzahl für Werte nach Typ 2 Backend) ist mindestens einmal anzugeben. Es kann in Abhängigkeit zu den anderen PIA Segmenten innerhalb derselben SG27 LIN (Erforderliches Messprodukt für Werte nach Typ2 aus Backend) maximal bis zu 23 mal angegeben werden sofern die anderen PIA Segmente innerhalb derselben SG27 LIN nicht mehr als einmal angegeben werden. Die maximale Anzahl an PIA-Segmenten je SG27 LIN ist 25.", art: "wiederholbarkeit" },
  "2074": { text: "Pro Nachricht ist diese SG27 so oft zu wiederholen, bis für jedes angefragte Produkt derselben SG27 aus der Anfrage eine Angebotsposition angegeben wurde.", art: "wiederholbarkeit" },
  "2075": { text: "Pro SG27 LIN kann die SG27 PIA+Z02 (Artikel-ID) bis zu zweimal angegeben werden. Einmal für die Artikel-ID gemäß Preisblatt B des MSB und einmal für die Artikel-ID \"9991000003030-01\" (Pauschale Kosten für das Scheitern der Änderung der Technik an einer Lokation) gemäß Preisblatt B des MSB. Hat der MSB in der angegebenen Version des Preisblatt B keine Artikel-ID für \"9991000003030-01\" (Pauschale Kosten für das Scheitern der Änderung der Technik einer Lokation) angegeben, kann die SG27 PIA+Z02 (Artikel-ID) nur einmal angegeben werden.", art: "wiederholbarkeit" },
  "2076": { text: "Pro SG27 LIN kann die SG31 Preisangabe zur Position nur einmal angegeben werden. Die Angabe der Preisangaben zur Position bezieht sich auf die Artikel-ID bei der es sich nicht um die Artikel-ID \"9991000003030- 01\" (Pauschale Kosten für das Scheitern der Änderung der Technik an einer Lokation) gemäß Preisblatt B des MSB handelt.", art: "wiederholbarkeit" },
};
if (typeof window!=='undefined') window.EdiBedingungen = Object.assign(window.EdiBedingungen||{}, quotesBedingungen);
if (typeof module!=='undefined') module.exports = quotesBedingungen;
