// _bedingungen.js (IFTSTA) - AHB-Bedingungen, extrahiert mit kohlrahbi (Hochfrequenz).
// Offizieller conditions-Scraper, Quelle FV2604.
var iftstaBedingungen = {
  "1": { text: "Wenn die Übermittlung nicht codierbarer Informationen nötig ist.", art: "voraussetzung" },
  "3": { text: "Wenn SG7 STS+Z01 nicht vorhanden.", art: "voraussetzung", check: {"tag": "STS", "qual": "Z01", "neg": true} },
  "4": { text: "Wenn SG7 STS+Z02 nicht vorhanden.", art: "voraussetzung", check: {"tag": "STS", "qual": "Z02", "neg": true} },
  "5": { text: "Wenn SG7 STS+Z03 nicht vorhanden.", art: "voraussetzung", check: {"tag": "STS", "qual": "Z03", "neg": true} },
  "6": { text: "Wenn für das 3-Tupel (MaBiS-ZP, Betrachtungszeitraum,Version der Summenzeitreihe) dem BIKO der Prüfstatus vorliegt, so ist dieser immer zusammen mit dem Datenstatus zu übertragen.", art: "voraussetzung" },
  "7": { text: "Wenn der Datenstatus \"Abgerechnete Daten\" bzw. \"Abgerechnete Daten Korrektur-BKA\" nicht vorhanden.", art: "voraussetzung" },
  "8": { text: "Wenn der Datenstatus einer NZR vom BIKO an NB nicht vorhanden.", art: "voraussetzung" },
  "10": { text: "Wenn Meldung des BKV/NB/ÜNB nach Frist eingeht.", art: "voraussetzung" },
  "16": { text: "Wenn MP-ID in SG1 NAD+MR in der Rolle BKV", art: "voraussetzung" },
  "17": { text: "Wenn Meldung des BKV auf falscher Aggregationsebene eingeht.", art: "voraussetzung" },
  "18": { text: "Wenn SG15 STS+Z19 nicht vorhanden.", art: "voraussetzung", check: {"tag": "STS", "qual": "Z19", "neg": true} },
  "19": { text: "Wenn SG15 STS+Z24 nicht vorhanden.", art: "voraussetzung", check: {"tag": "STS", "qual": "Z24", "neg": true} },
  "20": { text: "Wenn MP-ID in SG1 NAD+MR in der Rolle LF", art: "voraussetzung" },
  "23": { text: "Wenn SG15 STS+Z25+Z31+A06 / A09 / A10 /A11 / A13 / A14 / A15 / A16 vorhanden.", art: "voraussetzung" },
  "26": { text: "Wenn MP-ID in SG1 NAD+MR in der Rolle NB", art: "voraussetzung" },
  "27": { text: "Nur MP-ID aus Sparte Strom", art: "voraussetzung" },
  "28": { text: "Nur MP-ID aus Sparte Gas", art: "voraussetzung" },
  "29": { text: "Wenn MP-ID in SG1 NAD+MR in der Rolle ÜNB", art: "voraussetzung" },
  "30": { text: "Wenn in dieser SG15 STS+Z20+Z32+A07:E_0207 vorhanden.", art: "voraussetzung" },
  "31": { text: "Wenn in dieser SG16 in QTY in DE6411 KWH/K3 vorhanden.", art: "voraussetzung" },
  "32": { text: "Wenn in dieser SG16 in QTY in DE6411 KWT/K5 vorhanden.", art: "voraussetzung" },
  "33": { text: "Wenn in dieser SG16 DTM+163 vorhanden.", art: "voraussetzung" },
  "43": { text: "Wenn STS+Z01+Z07 vorhanden, dann sind nur Codes aus dem EBD-Cluster \"Zustimmung\" möglich.", art: "voraussetzung" },
  "44": { text: "Wenn STS+Z01+Z08 vorhanden, dann sind nur Codes aus dem EBD-Cluster \"Ablehnung\" möglich.", art: "voraussetzung" },
  "45": { text: "Wenn STS+Z03+Z07 vorhanden, dann sind nur Codes aus dem EBD-Cluster \"Zustimmung\" möglich.", art: "voraussetzung" },
  "46": { text: "Wenn STS+Z03+Z08 vorhanden, dann sind nur Codes aus dem EBD-Cluster \"Ablehnung\" möglich.", art: "voraussetzung" },
  "47": { text: "Es sind nur Codes aus dem EBD-Cluster \"Ablehnung\" möglich.", art: "voraussetzung" },
  "48": { text: "Es sind nur Codes aus dem EBD-Cluster \"Zustimmung\" möglich.", art: "voraussetzung" },
  "49": { text: "Wenn STS+Z25+Z30 vorhanden, dann sind nur Codes aus dem EBD-Cluster \"Zustimmung\" möglich.", art: "voraussetzung" },
  "50": { text: "Wenn STS+Z25+Z31 vorhanden, dann sind nur Codes aus dem EBD-Cluster \"Ablehnung\" möglich.", art: "voraussetzung" },
  "51": { text: "Es sind nur Codes aus dem EBD-Cluster \"Abweisung\" möglich.", art: "voraussetzung" },
  "52": { text: "Wenn STS+Z27+Z32 vorhanden", art: "voraussetzung" },
  "53": { text: "Wenn STS+Z28+Z32 vorhanden", art: "voraussetzung" },
  "54": { text: "Wenn STS+Z29+Z32 vorhanden", art: "voraussetzung" },
  "55": { text: "Wenn STS+Z30+Z32 vorhanden", art: "voraussetzung" },
  "56": { text: "Wenn in dieser SG15 STS das SG15 RFF+ACW nicht identisch mit dem SG15 RFF+ACW der SG15 STS+Z27 ist", art: "voraussetzung" },
  "57": { text: "Wenn in dieser SG15 STS das SG15 RFF+ACW nicht identisch mit dem SG15 RFF+ACW der SG15 STS+Z28 ist", art: "voraussetzung" },
  "58": { text: "Wenn in dieser SG15 STS das SG15 RFF+ACW nicht identisch mit dem SG15 RFF+ACW der SG15 STS+Z29 ist", art: "voraussetzung" },
  "59": { text: "Wenn in dieser SG15 STS das SG15 RFF+ACW nicht identisch mit dem SG15 RFF+ACW der SG15 STS+Z30 ist", art: "voraussetzung" },
  "60": { text: "Wenn zusätzlich zum Fahrplananteil auch die Ausfallarbeit zu identischem Wert aus RFF+ACW nicht o.k. ist", art: "voraussetzung" },
  "61": { text: "Wenn zusätzlich zur Ausfallarbeit auch der Fahrplananteil zu identischem Wert aus RFF+ACW nicht o.k. ist", art: "voraussetzung" },
  "62": { text: "Wenn STS+Z27+Z30 vorhanden, dann sind nur Codes aus dem EBD-Cluster \"Zustimmung\" möglich.", art: "voraussetzung" },
  "63": { text: "Wenn STS+Z27+Z32 vorhanden, dann sind nur Codes aus dem EBD-Cluster \"Ablehnung\" möglich.", art: "voraussetzung" },
  "64": { text: "Wenn STS+Z28+Z30 vorhanden, dann sind nur Codes aus dem EBD-Cluster \"Zustimmung\" möglich.", art: "voraussetzung" },
  "65": { text: "Wenn STS+Z28+Z32 vorhanden, dann sind nur Codes aus dem EBD-Cluster \"Ablehnung\" möglich.", art: "voraussetzung" },
  "66": { text: "Wenn STS+Z29+Z30 vorhanden, dann sind nur Codes aus dem EBD-Cluster \"Zustimmung\" möglich.", art: "voraussetzung" },
  "67": { text: "Wenn STS+Z29+Z32 vorhanden, dann sind nur Codes aus dem EBD-Cluster \"Ablehnung\" möglich.", art: "voraussetzung" },
  "68": { text: "Wenn STS+Z30+Z30 vorhanden, dann sind nur Codes aus dem EBD-Cluster \"Zustimmung\" möglich.", art: "voraussetzung" },
  "69": { text: "Wenn STS+Z30+Z32 vorhanden, dann sind nur Codes aus dem EBD-Cluster \"Ablehnung\" möglich.", art: "voraussetzung" },
  "70": { text: "Wenn zusätzlich zum Gegenvorschlag des Fahrplananteils auch der Gegenvorschlag der Ausfallarbeit zu identischem Wert aus RFF+ACW nicht o.k. ist", art: "voraussetzung" },
  "71": { text: "Wenn zusätzlich zum Gegenvorschlag der Ausfallarbeit auch der Gegenvorschlag des Fahrplananteils zu identischem Wert aus RFF+ACW nicht o.k. ist", art: "voraussetzung" },
  "72": { text: "Wenn Gegenvorschlag erstellt werden kann", art: "voraussetzung" },
  "76": { text: "Wenn MP-ID in SG1 NAD+MR in der Rolle ESA", art: "voraussetzung" },
  "77": { text: "Wenn STS+Z37+Z14 in dieser SG14 vorhanden", art: "voraussetzung" },
  "78": { text: "Wenn STS+Z38 in dieser SG14 nicht vorhanden", art: "voraussetzung" },
  "79": { text: "Wenn STS+Z37 in dieser SG14 nicht vorhanden", art: "voraussetzung" },
  "80": { text: "Wenn STS+Z38+Z14 in dieser SG14 vorhanden", art: "voraussetzung" },
  "83": { text: "Wenn STS+Z37+Z13+A04/ A05/A06:E_0472 in dieser SG14 vorhanden", art: "voraussetzung" },
  "84": { text: "Wenn STS+Z38+Z13+A02: E_0499 in dieser SG14 vorhanden", art: "voraussetzung" },
  "85": { text: "Wenn STS+Z37+Z32+A01: E_0501 in dieser SG14 vorhanden", art: "voraussetzung" },
  "86": { text: "Wenn MP-ID in SG1 NAD+MS in der Rolle LF", art: "voraussetzung" },
  "91": { text: "Wenn in diesem STS DE1131 = E_0472", art: "voraussetzung" },
  "92": { text: "Wenn in diesem STS DE1131 = E_0501", art: "voraussetzung" },
  "93": { text: "Wenn STS+Z37+Z13 vorhanden, dann sind nur Codes aus dem EBD-Cluster \"gescheitert\" möglich.", art: "voraussetzung" },
  "94": { text: "Wenn STS+Z37+Z14 vorhanden, dann sind nur Codes aus dem EBD-Cluster \"erfolgreich\"möglich.", art: "voraussetzung" },
  "95": { text: "Wenn in diesem STS DE1131 = E_0499", art: "voraussetzung" },
  "96": { text: "Wenn in diesem STS DE1131 = E_0487", art: "voraussetzung" },
  "97": { text: "Wenn STS+Z38+Z13 vorhanden, dann sind nur Codes aus dem EBD-Cluster \"gescheitert\" möglich.", art: "voraussetzung" },
  "98": { text: "Wenn STS+Z38+Z14 vorhanden, dann sind nur Codes aus dem EBD-Cluster \"erfolgreich\" möglich.", art: "voraussetzung" },
  "99": { text: "Wenn in diesem STS DE1131 = E_0487, dann ist nur der Code A01 möglich.", art: "voraussetzung" },
  "100": { text: "Wenn STS+Z43+Z47 vorhanden, dann sind nur Codes aus dem EBD-Cluster \"Änderung der Daten\" möglich.", art: "voraussetzung" },
  "101": { text: "Wenn STS+Z43+Z48 vorhanden, dann sind nur Codes aus dem EBD-Cluster \"keine Änderung der Daten\" möglich.", art: "voraussetzung" },
  "103": { text: "Wenn in diesem STS DE1131 nicht vorhanden", art: "voraussetzung" },
  "107": { text: "Wenn STS+Z37+Z32 vorhanden, dann sind nur Codes aus dem EBD-Cluster \"Ablehnung\" möglich.", art: "voraussetzung" },
  "114": { text: "Wenn MP-ID in SG1 NAD+MS in der Rolle MSB", art: "voraussetzung" },
  "115": { text: "Wenn MP-ID in SG1 NAD+MS in der Rolle NB", art: "voraussetzung" },
  "117": { text: "Wenn MP-ID in SG1 NAD+MR in der Rolle MSB", art: "voraussetzung" },
  "118": { text: "Wenn in diesem STS DE1131 = E_0526", art: "voraussetzung" },
  "119": { text: "Wenn in diesem STS DE1131 = E_0528", art: "voraussetzung" },
  "120": { text: "Wenn in diesem STS DE1131 = E_0529", art: "voraussetzung" },
  "121": { text: "Wenn in diesem STS DE1131 = E_0536", art: "voraussetzung" },
  "129": { text: "Wenn STS+Z20+Z32+A99:E_0524 in dieser SG14 vorhanden", art: "voraussetzung" },
  "130": { text: "Wenn STS+Z20+Z32+A99:E_0531 indieser SG14 vorhanden", art: "voraussetzung" },
  "131": { text: "Wenn STS+Z37+Z13+A04/ A05/A06:E_1003 in dieser SG14 vorhanden", art: "voraussetzung" },
  "132": { text: "Wenn STS+Z37+Z32+A01: E_1002 in dieser SG14 vorhanden", art: "voraussetzung" },
  "133": { text: "Wenn in diesem STS DE1131 = E_1003", art: "voraussetzung" },
  "134": { text: "Wenn in diesem STS DE1131 = E_1002", art: "voraussetzung" },
  "135": { text: "Wenn in dieser SG15 in STS+Z21 DE9013 = A99", art: "voraussetzung" },
  "136": { text: "Wenn STS+Z38+Z13+A02: E_1005 in dieser SG14 vorhanden", art: "voraussetzung" },
  "137": { text: "Wenn in diesem STS DE1131 = E_1005", art: "voraussetzung" },
  "138": { text: "Wenn in diesem STS DE1131= E_1020", art: "voraussetzung" },
  "139": { text: "Wenn in diesem STS DE1131 = E_1020, dann ist nur der Code A01 möglich.", art: "voraussetzung" },
  "140": { text: "Wenn in diesem STS DE9013 <> A01", art: "voraussetzung" },
  "141": { text: "Wenn in diesem STS DE9013 = A01", art: "voraussetzung" },
  "142": { text: "Wenn in diesem STS DE1131 = E_0535", art: "voraussetzung" },
  "143": { text: "Wenn mehr als ein Grund vorliegt und die voranstehenden DE9013 dieses STS nicht ausreichen", art: "voraussetzung" },
  "144": { text: "Wenn RFF+Z45 in dieser SG15 nicht vorhanden", art: "voraussetzung" },
  "145": { text: "Wenn RFF+Z17 in dieser SG15 nicht vorhanden", art: "voraussetzung" },
  "146": { text: "Wenn im DE3155 in demselben COM der Code EM vorhanden ist", art: "voraussetzung" },
  "147": { text: "Wenn im DE3155 in demselben COM der Code TE / FX / AJ / AL vorhanden ist", art: "voraussetzung" },
  "148": { text: "Wenn in dieser SG15 STS+Z43+Z48+A99:E_0595 vorhanden", art: "voraussetzung" },
  "149": { text: "Wenn in dieser SG14 STS DE1131 <> E_0278", art: "voraussetzung" },
  "150": { text: "Wenn in dieser SG14 STS DE1131 <> E_0281", art: "voraussetzung" },
  "151": { text: "Wenn STS+Z20+Z32+A99:E_0278 in dieser SG14 vorhanden", art: "voraussetzung" },
  "152": { text: "Wenn STS+Z20+Z32+A99:E_0281 in dieser SG14 vorhanden", art: "voraussetzung" },
  "153": { text: "Wenn in diesem STS DE1131 = E_0286", art: "voraussetzung" },
  "154": { text: "Wenn STS+Z15+Z13+A99: E_0286 in dieser SG14 vorhanden", art: "voraussetzung" },
  "155": { text: "Text im AHB nicht gefunden (bitte prüfen).", art: "voraussetzung" },
  "490": { text: "wenn Wert in diesem DE, an der Stelle CCYYMMDDHHMM ein Zeitpunkt aus dem angegeben Zeitraum der Tabelle Kapitel 3.5 „Übersicht gesetzliche deutsche Sommerzeit (MESZ)“ der Spalten:\n›\t„Sommerzeit (MESZ) von“ Darstellung in UTC und\n›\t„Sommerzeit (MESZ) bis“ Darstellung in UTC ist.", art: "voraussetzung" },
  "491": { text: "wenn Wert in diesem DE, an der Stelle CCYYMMDDHHMM ein Zeitpunkt aus dem angegeben Zeitraum der Tabelle Kapitel 3.6 „Übersicht gesetzliche deutsche Zeit (MEZ)“ der Spalten: \n›\t„Winterzeit (MEZ) von“ Darstellung in UTC und\n›\t„Winterzeit (MEZ) bis“ Darstellung in UTC ist.", art: "voraussetzung" },
  "492": { text: "wenn MP-ID in NAD+MR aus Sparte Strom", art: "voraussetzung" },
  "493": { text: "wenn MP-ID in NAD+MR aus Sparte Gas", art: "voraussetzung" },
  "494": { text: "Das hier genannte Datum muss der Zeitpunkt sein, zu dem das Dokument erstellt wurde, oder ein Zeitpunkt, der davor liegt", art: "voraussetzung" },
  "495": { text: "Der Zeitpunkt muss ≤ dem Wert im DE2380 des DTM+137 sein", art: "voraussetzung" },
  "496": { text: "Der Zeitpunkt muss > dem Wert im DE2380 des DTM+137 sein", art: "voraussetzung" },
  "501": { text: "Hinweis: Aus QUOTES BGM DE1004", art: "hinweis" },
  "502": { text: "Hinweis: Aus REQOTE BGM DE1004", art: "hinweis" },
  "503": { text: "Hinweis: Auf Selbsteinbau eines iMS oder einer mME wird verzichtet", art: "hinweis" },
  "504": { text: "Hinweis: Verwendung der ID des MaBiS-ZP", art: "hinweis" },
  "505": { text: "Hinweis: Verwendung der ID der Messlokation", art: "hinweis" },
  "506": { text: "Hinweis: Verwendung der ID der Marktlokation", art: "hinweis" },
  "510": { text: "Hinweis: Es ist neben der Information über die Ablehnung auch der unverändert gebliebene Datenstatus informell mitzugeben.", art: "hinweis" },
  "512": { text: "Hinweis: Aus MSCONS BGM DE1004", art: "hinweis" },
  "519": { text: "Hinweis: Aus ORDERS BGM DE1004", art: "hinweis" },
  "520": { text: "Hinweis: Zeitpunkt, zu dem der Wechsel erfolgt, falls er zustande kommt", art: "hinweis" },
  "521": { text: "Hinweis: Zeitpunkt, ab dem der MSBN tatsächlich den Messstellenbetrieb übernimmt", art: "hinweis" },
  "522": { text: "Hinweis: Zeitpunkt, ab dem der gMSB den Messstellenbetrieb übernimmt", art: "hinweis" },
  "523": { text: "Hinweis: Wert aus BGM DE1004 der MSCONS, auf die sich die Statusangabe bezieht", art: "hinweis" },
  "524": { text: "Hinweis: Wert aus BGM DE1004 der MSCONS, die den Gegenvorschlag enthält", art: "hinweis" },
  "525": { text: "Hinweis: Je SG14 sind nur Statusinformationen zu einer MSCONS enthalten", art: "hinweis" },
  "530": { text: "Hinweis: Hier ist die Arbeit bzw. Leistung anzugeben, die der Sender der IFTSTA im Lieferschein für den von ihm genannten Zeitraum / Leistungsperiode erwartet hätte.", art: "hinweis" },
  "531": { text: "Vom MSBN in Schritt 1 des SD verwendete Vorgangsnummer, damit der LF diese bei der Bestellung einer Konfiguration beim MSBN, unter dem Vorbehalt, dass der MSB-Wechsel an der Messlokation erfolgreich sein wird, verwenden kann.", art: "hinweis" },
  "532": { text: "Hinweis: Verwendung der ID der Netzlokation", art: "hinweis" },
  "533": { text: "Hinweis: Verwendung der ID der Steuerbaren Ressource", art: "hinweis" },
  "534": { text: "Hinweis: Es darf nur eine Information im DE3148 übermittelt werden", art: "hinweis" },
  "535": { text: "Hinweis: Aus UTILMD IDE DE7402", art: "hinweis" },
  "537": { text: "Hinweis: Der Code ist nötig, da dieser Anwendungsfall auch in allen Use- Cases zur Anwendung kommt, in denen sich die in diesem Segment zu übertragende Information nicht anhand eines Entscheidungsbaus ergibt.", art: "hinweis" },
  "538": { text: "Text im AHB nicht gefunden (bitte prüfen).", art: "hinweis" },
  "902": { text: "Format: Wert darf nur positiv oder 0 sein", art: "format" },
  "903": { text: "Format: Möglicher Wert: 1", art: "format" },
  "906": { text: "Format: max. 3 Nachkommastellen", art: "format" },
  "911": { text: "Format: Mögliche Werte: 1 bis n, je Nachricht bei 1 beginnend und fortlaufend aufsteigend", art: "format" },
  "931": { text: "Format: ZZZ = +00", art: "format" },
  "932": { text: "Format: HHMM = 2200", art: "format" },
  "933": { text: "Format: HHMM = 2300", art: "format" },
  "934": { text: "Format: HHMM = 0400", art: "format" },
  "935": { text: "Format: HHMM = 0500", art: "format" },
  "939": { text: "Format: Die Zeichenkette muss die Zeichen @ und . enthalten", art: "format" },
  "940": { text: "Format: Die Zeichenkette muss mit dem Zeichen + beginnen und danach dürfen nur noch Ziffern folgen", art: "format" },
  "950": { text: "Format: Marktlokations-ID", art: "format" },
  "951": { text: "Format: Zählpunktbezeichnu ng", art: "format" },
  "960": { text: "Format: Netzlokations-ID", art: "format" },
  "961": { text: "Format: SR-ID", art: "format" },
};
if (typeof window!=='undefined') window.EdiBedingungen = Object.assign(window.EdiBedingungen||{}, iftstaBedingungen);
if (typeof module!=='undefined') module.exports = iftstaBedingungen;
